import { PowerCheckItem } from "./power-checks";

// 200 executive communication tips — how to speak, pitch, disagree, close, and command a room
export const executiveCommunicationTips: PowerCheckItem[] = [
  // --- Speaking with Authority ---
  { id: "ec-1", label: "Eliminate filler words today: no 'um', 'like', 'basically', 'you know'. Silence between sentences is power.", theme: "exec-communication" },
  { id: "ec-2", label: "Speak in declarative sentences today: 'We should do X' not 'Maybe we could try X?' — remove the question mark", theme: "exec-communication" },
  { id: "ec-3", label: "Lower your pitch slightly when making a key point. Deeper voice = more authority. Practice this today.", theme: "exec-communication" },
  { id: "ec-4", label: "End sentences with a downward inflection, not upward. Upward sounds uncertain. Down sounds definitive.", theme: "exec-communication" },
  { id: "ec-5", label: "Use the 'power pause': pause for 2 seconds before your most important point. The silence creates anticipation.", theme: "exec-communication" },
  { id: "ec-6", label: "Speak 10% slower today, especially when making your key point. Rushing signals nervousness.", theme: "exec-communication" },
  { id: "ec-7", label: "Use shorter sentences when you want to be persuasive. Long sentences dilute impact. Short sentences punch.", theme: "exec-communication" },
  { id: "ec-8", label: "Replace 'I think' with 'I'm confident that' — same meaning, completely different energy", theme: "exec-communication" },
  { id: "ec-9", label: "Use the rule of three: present ideas in groups of three. 'Fast, reliable, and affordable.' Three sticks in memory.", theme: "exec-communication" },
  { id: "ec-10", label: "Start your sentences with verbs for impact: 'Consider this.' 'Imagine that.' 'Think about it.' — action language", theme: "exec-communication" },

  // --- The Art of Listening ---
  { id: "ec-11", label: "Practice reflective listening today: repeat back what someone said in your own words before responding", theme: "exec-communication" },
  { id: "ec-12", label: "Count to 3 after someone finishes speaking before you respond. This prevents interruption and shows respect.", theme: "exec-communication" },
  { id: "ec-13", label: "Listen for emotions, not just words. 'That sounds frustrating' is more powerful than solving the problem immediately.", theme: "exec-communication" },
  { id: "ec-14", label: "Ask follow-up questions that go deeper: 'Tell me more about that' or 'What led you to that conclusion?'", theme: "exec-communication" },
  { id: "ec-15", label: "Put your phone face-down in every conversation today. Full attention is the rarest gift in 2026.", theme: "exec-communication" },
  { id: "ec-16", label: "Notice what people DON'T say. The silence often reveals more than the words.", theme: "exec-communication" },
  { id: "ec-17", label: "When someone is talking, resist the urge to plan your response. Just listen. Your response will be better for it.", theme: "exec-communication" },
  { id: "ec-18", label: "Acknowledge before advising: 'I understand your concern' before 'Here's what I suggest' — order matters", theme: "exec-communication" },
  { id: "ec-19", label: "Use the 80/20 listening rule in sales: listen 80% of the time, talk 20%. The client sells themselves.", theme: "exec-communication" },
  { id: "ec-20", label: "Ask: 'What else?' after they finish. There's almost always something they held back. This question unlocks it.", theme: "exec-communication" },

  // --- Pitching & Selling ---
  { id: "ec-21", label: "Lead with the outcome, not the process: 'You'll save 20 hours/month' not 'We'll build a custom database system'", theme: "exec-communication" },
  { id: "ec-22", label: "Use the Problem → Agitation → Solution framework: name the pain, make them feel it, then offer the fix", theme: "exec-communication" },
  { id: "ec-23", label: "Never say 'I can do that for you.' Say 'Here's how we've solved this before.' — proof beats promises", theme: "exec-communication" },
  { id: "ec-24", label: "Use the 'imagine' technique: 'Imagine checking your dashboard at 9 AM and knowing exactly where every payment stands'", theme: "exec-communication" },
  { id: "ec-25", label: "The best pitch doesn't feel like a pitch. It feels like a conversation where THEY realize they need you.", theme: "exec-communication" },
  { id: "ec-26", label: "Use specific numbers: 'We reduced processing time from 45 minutes to 3 minutes' — specifics are credible", theme: "exec-communication" },
  { id: "ec-27", label: "End every pitch with a clear next step: 'Can I send you a one-page proposal by Wednesday?' — not 'Let me know'", theme: "exec-communication" },
  { id: "ec-28", label: "Practice the 30-second elevator pitch today: who you help, how you help them, and one proof point", theme: "exec-communication" },
  { id: "ec-29", label: "Use social proof naturally: 'When we did this for Sunil's samaj event, the feedback was...'", theme: "exec-communication" },
  { id: "ec-30", label: "Don't sell features — sell the transformation: 'From chaos to clarity' 'From manual to automatic'", theme: "exec-communication" },

  // --- Disagreeing Gracefully ---
  { id: "ec-31", label: "Practice the 'Yes, and...' technique: agree with their point, then add your perspective. Never start with 'But'.", theme: "exec-communication" },
  { id: "ec-32", label: "Disagree with data, not emotion: 'The numbers suggest otherwise...' is stronger than 'I disagree'", theme: "exec-communication" },
  { id: "ec-33", label: "Use the 'curious disagreement': 'That's interesting — I've seen the opposite. What makes you think that?' — question, don't attack", theme: "exec-communication" },
  { id: "ec-34", label: "Separate the person from the idea: 'The idea has merit, but the execution concerns me' — never make it personal", theme: "exec-communication" },
  { id: "ec-35", label: "Use the 'steel man' technique: make THEIR argument even stronger before you counter it. Shows intellectual honesty.", theme: "exec-communication" },
  { id: "ec-36", label: "Disagree privately, support publicly. If you must push back on a senior person, do it one-on-one, not in front of others.", theme: "exec-communication" },
  { id: "ec-37", label: "The phrase 'Help me understand...' is the most diplomatic way to challenge someone's logic", theme: "exec-communication" },
  { id: "ec-38", label: "When the room disagrees with you, try: 'I may be wrong — can we test this assumption before deciding?'", theme: "exec-communication" },
  { id: "ec-39", label: "Don't argue to win — argue to reach the best decision. Ask: 'What would change my mind?' and mean it.", theme: "exec-communication" },
  { id: "ec-40", label: "Sometimes the most powerful disagreement is a simple: 'I see it differently. Here's why.' — calm and direct.", theme: "exec-communication" },

  // --- Body Language in Communication ---
  { id: "ec-41", label: "Maintain open body language in every conversation today: uncrossed arms, facing the speaker, slight forward lean", theme: "exec-communication" },
  { id: "ec-42", label: "Use the triangle gaze: look at one eye, then the other, then the mouth. Cycle slowly. Creates deep connection.", theme: "exec-communication" },
  { id: "ec-43", label: "Nod slowly (not quickly) when listening. Slow nods signal thoughtful processing. Fast nods signal impatience.", theme: "exec-communication" },
  { id: "ec-44", label: "Steeple your fingers when making a point — fingertips touching, palms apart. It signals confidence and authority.", theme: "exec-communication" },
  { id: "ec-45", label: "When someone speaks to you, turn your whole body toward them, not just your head. Full attention = full respect.", theme: "exec-communication" },
  { id: "ec-46", label: "Mirror the other person's posture subtly — it builds unconscious rapport. If they lean forward, lean forward.", theme: "exec-communication" },
  { id: "ec-47", label: "Use purposeful hand gestures when speaking — they increase persuasion by 30%. Keep them between waist and shoulders.", theme: "exec-communication" },
  { id: "ec-48", label: "Don't fidget. No pen clicking, no phone checking, no watch glancing. Stillness signals composure.", theme: "exec-communication" },
  { id: "ec-49", label: "Smile when you greet someone, but not constantly. A strategic smile has more impact than a permanent one.", theme: "exec-communication" },
  { id: "ec-50", label: "When standing in a group, don't keep your hands in your pockets. It signals discomfort. Hold a drink or rest one hand on the other wrist.", theme: "exec-communication" },

  // --- Email & Written Communication ---
  { id: "ec-51", label: "Subject line tip: put the action needed in the subject. 'Decision needed: Project scope by Friday' — not 'Quick question'", theme: "exec-communication" },
  { id: "ec-52", label: "Start emails with the bottom line first: 'I recommend X because Y.' Then provide supporting details.", theme: "exec-communication" },
  { id: "ec-53", label: "Use bullet points instead of paragraphs. Busy executives scan, they don't read essays.", theme: "exec-communication" },
  { id: "ec-54", label: "End every email with a clear call to action: 'Please confirm by Thursday' not 'Let me know your thoughts'", theme: "exec-communication" },
  { id: "ec-55", label: "Keep WhatsApp messages to 3 lines max. Long messages don't get read on mobile. Break into multiple short messages.", theme: "exec-communication" },
  { id: "ec-56", label: "Use formatting for clarity: bold the key number, underline the deadline, bullet the action items", theme: "exec-communication" },
  { id: "ec-57", label: "Reply to important messages within 4 hours. Speed of response signals professionalism and eagerness.", theme: "exec-communication" },
  { id: "ec-58", label: "Before hitting send, read your message as the recipient. Does it answer their question? Is the ask clear?", theme: "exec-communication" },
  { id: "ec-59", label: "Use the 'TL;DR' technique for long updates: one-line summary at the top, details below for those who want them", theme: "exec-communication" },
  { id: "ec-60", label: "Professional sign-offs: 'Warm regards' (relationship), 'Best' (neutral), 'Looking forward' (action-oriented)", theme: "exec-communication" },

  // --- Storytelling in Business ---
  { id: "ec-61", label: "Every good business story has: a challenge, a turning point, and a result. Structure yours this way today.", theme: "exec-communication" },
  { id: "ec-62", label: "Open with a hook: 'Last month, a client called me in a panic...' — curiosity pulls people in", theme: "exec-communication" },
  { id: "ec-63", label: "Use specific details: 'At 11:30 PM on a Tuesday' is more memorable than 'late one night'", theme: "exec-communication" },
  { id: "ec-64", label: "Include the emotional moment: 'That's when he realized his entire membership data was in an Excel file that anyone could delete'", theme: "exec-communication" },
  { id: "ec-65", label: "End stories with the lesson, not just the outcome: 'And that's why we always build with backups from day one'", theme: "exec-communication" },
  { id: "ec-66", label: "Practice the 'customer hero' story: the client is the hero, you're the guide. They succeed because of your help.", theme: "exec-communication" },
  { id: "ec-67", label: "Use analogies from their world: 'Think of this like a fixed deposit vs. a savings account' — for financial people", theme: "exec-communication" },
  { id: "ec-68", label: "Keep business stories under 90 seconds. Any longer and you lose the room.", theme: "exec-communication" },
  { id: "ec-69", label: "Use the 'before and after' framework: 'Before, they spent 2 days on reports. Now, one click. 30 seconds.'", theme: "exec-communication" },
  { id: "ec-70", label: "Collect stories like currency. Every project, every conversation, every challenge is a potential story. Note them down.", theme: "exec-communication" },

  // --- Asking Powerful Questions ---
  { id: "ec-71", label: "Today's power question: 'What's the ONE thing that would make the biggest difference for your business right now?'", theme: "exec-communication" },
  { id: "ec-72", label: "Try this question: 'If you could wave a magic wand and fix one thing in your operations, what would it be?'", theme: "exec-communication" },
  { id: "ec-73", label: "Ask: 'What does your ideal week look like?' — reveals their priorities and pain points naturally", theme: "exec-communication" },
  { id: "ec-74", label: "Ask: 'What have you tried before and why didn't it work?' — learn from their history, avoid repeating mistakes", theme: "exec-communication" },
  { id: "ec-75", label: "Ask: 'How do you currently handle X?' before suggesting your solution. Understand before you prescribe.", theme: "exec-communication" },
  { id: "ec-76", label: "Ask: 'What would convince you this is worth doing?' — let them define their own decision criteria", theme: "exec-communication" },
  { id: "ec-77", label: "Ask: 'Who else needs to be involved in this decision?' — uncover the real decision-maker", theme: "exec-communication" },
  { id: "ec-78", label: "Ask: 'What's at stake if this doesn't get solved?' — they'll sell the urgency to themselves", theme: "exec-communication" },
  { id: "ec-79", label: "Ask: 'What would success look like for you personally?' — not just the business outcome, the personal one", theme: "exec-communication" },
  { id: "ec-80", label: "Ask: 'Is there anything I should know that you haven't mentioned yet?' — catches hidden concerns", theme: "exec-communication" },

  // --- Managing Difficult Conversations ---
  { id: "ec-81", label: "When delivering bad news: 'I want to be upfront with you about something...' — don't bury it", theme: "exec-communication" },
  { id: "ec-82", label: "Use the sandwich technique only when genuine: specific praise, constructive feedback, genuine encouragement", theme: "exec-communication" },
  { id: "ec-83", label: "When a client is angry: listen fully, acknowledge their feeling, own what's yours, propose the fix. In that order.", theme: "exec-communication" },
  { id: "ec-84", label: "Never say 'you're wrong.' Say 'That's one way to look at it — here's another angle that might help'", theme: "exec-communication" },
  { id: "ec-85", label: "When you've made a mistake: 'I take responsibility for X. Here's what I've already done to fix it and prevent recurrence.'", theme: "exec-communication" },
  { id: "ec-86", label: "When asked for a discount: 'I understand budget is a concern. Let me show you what we can adjust in scope to meet your number.'", theme: "exec-communication" },
  { id: "ec-87", label: "When a project is delayed: tell them BEFORE they ask. Proactive bad news builds more trust than reactive excuses.", theme: "exec-communication" },
  { id: "ec-88", label: "When someone talks too much: 'That's really helpful — let me make sure I capture the key points' — redirect without insulting", theme: "exec-communication" },
  { id: "ec-89", label: "When you need to say no: 'I want to be honest rather than overcommit. Here's what I CAN do...' — redirect to yes", theme: "exec-communication" },
  { id: "ec-90", label: "When someone undermines you: stay calm, respond with facts, and address it privately later. Never react in public.", theme: "exec-communication" },

  // --- Presentation Skills ---
  { id: "ec-91", label: "Start every presentation with a question or a surprising fact. Never start with 'Good morning, today I will...'", theme: "exec-communication" },
  { id: "ec-92", label: "Use the '10-20-30 rule': 10 slides, 20 minutes, 30-point minimum font size — Guy Kawasaki's formula", theme: "exec-communication" },
  { id: "ec-93", label: "One idea per slide. One. If you need more text, you need more slides. Or fewer words.", theme: "exec-communication" },
  { id: "ec-94", label: "Make eye contact with one person at a time for a full sentence. Then move to the next. This builds connection.", theme: "exec-communication" },
  { id: "ec-95", label: "Use the 'what, so what, now what' structure: here's the data, here's why it matters, here's what to do", theme: "exec-communication" },
  { id: "ec-96", label: "End with a clear ask: 'I need your approval on X by Y date' — don't end with 'any questions?'", theme: "exec-communication" },
  { id: "ec-97", label: "Practice the dramatic pause: say your key point, then stop for 3 full seconds. Let it land.", theme: "exec-communication" },
  { id: "ec-98", label: "If you're presenting a demo, narrate the user's journey: 'Imagine you're the secretary and it's event day...'", theme: "exec-communication" },
  { id: "ec-99", label: "Use 'you' more than 'I' in presentations. 'You'll see a 40% reduction' not 'I built a system that reduces...'", theme: "exec-communication" },
  { id: "ec-100", label: "Prepare for the 3 hardest questions you might get. If you're ready for those, everything else is easy.", theme: "exec-communication" },

  // --- Networking Conversations ---
  { id: "ec-101", label: "At Gymkhana today, try the FORD technique: Family, Occupation, Recreation, Dreams — conversation starters that go deep", theme: "exec-communication" },
  { id: "ec-102", label: "When meeting someone new: 'What's the most exciting thing you're working on right now?' — better than 'What do you do?'", theme: "exec-communication" },
  { id: "ec-103", label: "Give them a 'soundbite' about yourself: '25 years building software — now I help businesses like yours go digital' — crisp and clear", theme: "exec-communication" },
  { id: "ec-104", label: "Practice the 'exit and connect' move: end conversations gracefully with 'I'd love to continue this — can I WhatsApp you?'", theme: "exec-communication" },
  { id: "ec-105", label: "At group conversations, be the includer: 'Rajesh, what do you think about this?' — pulling quiet people in is leadership", theme: "exec-communication" },
  { id: "ec-106", label: "Don't dominate group conversations. Speak once, make it count, then listen. Quality over quantity.", theme: "exec-communication" },
  { id: "ec-107", label: "Remember details and reference them later: 'Last time you mentioned your daughter's wedding — how did it go?' — this is magic", theme: "exec-communication" },
  { id: "ec-108", label: "When someone asks 'How's business?', never say 'Slow.' Say 'Busy and growing — we just delivered a project for JSG.' — always forward", theme: "exec-communication" },
  { id: "ec-109", label: "Use the connector's line: 'You should meet X — you two have a lot in common' — being a connector makes you indispensable", theme: "exec-communication" },
  { id: "ec-110", label: "At events, don't cluster with people you know. Spend 30 minutes with new faces. That's where opportunities live.", theme: "exec-communication" },

  // --- WhatsApp & Digital Communication ---
  { id: "ec-111", label: "WhatsApp rule: always start with their name. 'Hi Sunil,' — not just 'Hi' — personalization matters even in text", theme: "exec-communication" },
  { id: "ec-112", label: "When following up on WhatsApp: add value, not just 'checking in'. Share an article, an idea, or a relevant update.", theme: "exec-communication" },
  { id: "ec-113", label: "Voice notes: keep under 60 seconds. Open with the key point. 'Quick update on the project — we're on track for Friday delivery.'", theme: "exec-communication" },
  { id: "ec-114", label: "Don't send multiple messages in a row — craft one complete message. Rapid-fire pings feel needy.", theme: "exec-communication" },
  { id: "ec-115", label: "Professional WhatsApp status: use it to showcase work. A screenshot of a dashboard you built. A client testimonial.", theme: "exec-communication" },
  { id: "ec-116", label: "Reply to group messages selectively — only when you add value. Being visible without being noisy is the goal.", theme: "exec-communication" },
  { id: "ec-117", label: "When sharing a link, add context: 'This article on digital transformation reminded me of our conversation about X'", theme: "exec-communication" },
  { id: "ec-118", label: "LinkedIn tip: comment thoughtfully on one post today. Add a genuine insight, not just 'Great post!' — visibility with substance.", theme: "exec-communication" },
  { id: "ec-119", label: "Email subject lines that get opened: use numbers, urgency, or curiosity. '3 ideas to save your team 10 hrs/week'", theme: "exec-communication" },
  { id: "ec-120", label: "Before sending any professional message, read it as the recipient. Does it sound confident? Clear? Warm but professional?", theme: "exec-communication" },

  // --- Influence & Persuasion ---
  { id: "ec-121", label: "Apply Cialdini's Reciprocity: give value first — a free audit, a quick fix, a connection — before asking for anything", theme: "exec-communication" },
  { id: "ec-122", label: "Apply Cialdini's Social Proof: 'Three samaj organizations in Mumbai already use our system' — people follow the crowd", theme: "exec-communication" },
  { id: "ec-123", label: "Apply Cialdini's Authority: mention SEBI credential naturally. Authority figures are more persuasive.", theme: "exec-communication" },
  { id: "ec-124", label: "Apply Cialdini's Scarcity: 'I can only take on 2 new projects this quarter' — limited availability increases desire", theme: "exec-communication" },
  { id: "ec-125", label: "Apply Cialdini's Liking: people buy from people they like. Be warm, genuine, and interested in THEM first.", theme: "exec-communication" },
  { id: "ec-126", label: "Apply Cialdini's Commitment: get a small yes first. 'Can I send you a one-pager?' leads to bigger yeses later.", theme: "exec-communication" },
  { id: "ec-127", label: "Use the 'because' principle: requests with a reason are 93% more effective. 'Can we meet Tuesday because I have an idea for you'", theme: "exec-communication" },
  { id: "ec-128", label: "Frame choices, don't give ultimatums: 'Would you prefer to start next week or the week after?' — both are yeses", theme: "exec-communication" },
  { id: "ec-129", label: "Use contrast principle: show the expensive option first, then your actual proposal looks like a bargain", theme: "exec-communication" },
  { id: "ec-130", label: "Create a 'future memory': 'When your team uses this next Diwali season, they'll save 3 days of manual work' — plant the vision", theme: "exec-communication" },

  // --- Executive Vocabulary Upgrades ---
  { id: "ec-131", label: "Replace 'cheap' with 'cost-effective' — same meaning, premium positioning", theme: "exec-communication" },
  { id: "ec-132", label: "Replace 'problem' with 'challenge' or 'opportunity' — language shapes perception", theme: "exec-communication" },
  { id: "ec-133", label: "Replace 'I can't' with 'Here's what I can do' — redirect to possibility", theme: "exec-communication" },
  { id: "ec-134", label: "Replace 'sorry for the delay' with 'thank you for your patience' — gratitude over apology", theme: "exec-communication" },
  { id: "ec-135", label: "Replace 'just checking in' with 'I wanted to share an update' — proactive, not passive", theme: "exec-communication" },
  { id: "ec-136", label: "Replace 'I'm not sure' with 'Let me get you a definitive answer' — certainty in uncertainty", theme: "exec-communication" },
  { id: "ec-137", label: "Replace 'Does that make sense?' with 'What questions do you have?' — assumes clarity, not confusion", theme: "exec-communication" },
  { id: "ec-138", label: "Replace 'To be honest' with nothing. Just be honest. The qualifier makes everything else sound dishonest.", theme: "exec-communication" },
  { id: "ec-139", label: "Replace 'I'll try' with 'I'll make it happen' or 'I'll get back to you with a timeline' — commit or clarify", theme: "exec-communication" },
  { id: "ec-140", label: "Replace 'No worries' with 'Happy to help' or 'My pleasure' — more professional, more warm", theme: "exec-communication" },

  // --- Reading the Room ---
  { id: "ec-141", label: "Watch for crossed arms — it signals resistance. Pause and ask 'What concerns do you have?' to open them up.", theme: "exec-communication" },
  { id: "ec-142", label: "If someone keeps checking their phone, you're losing them. Switch to a question to re-engage: 'What do you think?'", theme: "exec-communication" },
  { id: "ec-143", label: "If the room goes quiet after your proposal, wait. Don't fill the silence with justifications. Let them process.", theme: "exec-communication" },
  { id: "ec-144", label: "If someone leans back and steeples their fingers, they're evaluating. Present your strongest point now.", theme: "exec-communication" },
  { id: "ec-145", label: "If two people exchange glances during your pitch, there's an unspoken concern. Address it: 'I notice some hesitation — what's on your mind?'", theme: "exec-communication" },
  { id: "ec-146", label: "If the decision-maker is nodding, move to the close. Don't keep selling past the yes.", theme: "exec-communication" },
  { id: "ec-147", label: "Match the energy of the room: if they're formal, be formal. If they're relaxed, ease up. Mirroring creates belonging.", theme: "exec-communication" },
  { id: "ec-148", label: "If someone raises an objection, look at the decision-maker's reaction. Their face tells you how important it really is.", theme: "exec-communication" },
  { id: "ec-149", label: "If the conversation drifts to personal topics, let it. Relationship building IS the work. The deal follows the trust.", theme: "exec-communication" },
  { id: "ec-150", label: "If you sense the meeting is ending without a decision, say: 'Before we wrap up, can we agree on next steps?'", theme: "exec-communication" },

  // --- Handling Silence & Awkwardness ---
  { id: "ec-151", label: "After naming your price, stop talking. The first person to speak after a price loses. Let them respond.", theme: "exec-communication" },
  { id: "ec-152", label: "If someone asks a tough question, take a breath. 'That's a great question' buys you 3 seconds to think.", theme: "exec-communication" },
  { id: "ec-153", label: "Comfortable silence signals confidence. Don't rush to fill every gap. Let conversations breathe.", theme: "exec-communication" },
  { id: "ec-154", label: "If you don't know the answer: 'I want to give you accurate information — let me check and get back to you today.' Never bluff.", theme: "exec-communication" },
  { id: "ec-155", label: "If a joke falls flat, don't acknowledge it. Just move on smoothly. Dwelling on it makes it worse.", theme: "exec-communication" },
  { id: "ec-156", label: "If you're interrupted, wait calmly, then say: 'As I was saying...' — reclaims the floor without confrontation", theme: "exec-communication" },
  { id: "ec-157", label: "If someone disagrees harshly, respond with calm: 'I appreciate the directness. Here's my thinking...' — composure wins.", theme: "exec-communication" },
  { id: "ec-158", label: "If you lose your train of thought: 'Let me step back to the key point here...' — reset gracefully", theme: "exec-communication" },
  { id: "ec-159", label: "If the conversation gets heated, lower your voice. It forces others to lower theirs. Physics of de-escalation.", theme: "exec-communication" },
  { id: "ec-160", label: "If someone asks 'What do you charge?', don't answer immediately. Ask: 'Tell me more about what you need — pricing depends on scope.'", theme: "exec-communication" },

  // --- Building Rapport Fast ---
  { id: "ec-161", label: "Find common ground in the first 2 minutes: Gymkhana, kids' ages, sports, mutual connections, neighborhood", theme: "exec-communication" },
  { id: "ec-162", label: "Use their language back to them: if they say 'ROI', say 'ROI'. If they say 'paisa vasool', say 'paisa vasool'. Mirror.", theme: "exec-communication" },
  { id: "ec-163", label: "Share a mild vulnerability: 'I used to struggle with public speaking too' — vulnerability builds trust faster than perfection", theme: "exec-communication" },
  { id: "ec-164", label: "Laugh at their jokes generously (if genuine). Humor is the fastest bonding mechanism humans have.", theme: "exec-communication" },
  { id: "ec-165", label: "Remember and use their name at least 3 times in the first meeting. It's the sweetest sound to any person.", theme: "exec-communication" },
  { id: "ec-166", label: "Ask about their journey: 'How did you get started in this business?' — everyone loves their origin story", theme: "exec-communication" },
  { id: "ec-167", label: "Compliment their choice, not their possession: 'Great taste in watches' not 'Nice watch' — it's about them, not the thing", theme: "exec-communication" },
  { id: "ec-168", label: "Use the '5-minute favor': do something immediately helpful — 'Let me send you that contact right now'", theme: "exec-communication" },
  { id: "ec-169", label: "Show genuine curiosity: 'I've always wondered how the textile business works — walk me through a typical day'", theme: "exec-communication" },
  { id: "ec-170", label: "End conversations by referencing something they said: 'I'm going to remember what you said about X' — makes them feel heard", theme: "exec-communication" },

  // --- Commanding a Room ---
  { id: "ec-171", label: "Enter the room with purpose. Don't slink in. Walk in, make eye contact, greet someone by name.", theme: "exec-communication" },
  { id: "ec-172", label: "Sit at the center or head of the table, never at the far end. Position signals authority.", theme: "exec-communication" },
  { id: "ec-173", label: "Be the person who summarizes: 'So what I'm hearing is...' — the summarizer controls the narrative", theme: "exec-communication" },
  { id: "ec-174", label: "Speak last when the stakes are high. Let everyone share their view. Then synthesize and decide. This is CEO behavior.", theme: "exec-communication" },
  { id: "ec-175", label: "Use the 'pregnant pause' technique: pause for 3 seconds before your key statement. The room leans in.", theme: "exec-communication" },
  { id: "ec-176", label: "Address the most senior person first, but give attention to everyone. Hierarchy matters, but inclusion wins hearts.", theme: "exec-communication" },
  { id: "ec-177", label: "When someone makes a good point, acknowledge it publicly: 'That's exactly right' — generosity makes you the leader", theme: "exec-communication" },
  { id: "ec-178", label: "Use 'we' language when collaborating: 'We could approach this by...' — inclusive language builds alliance", theme: "exec-communication" },
  { id: "ec-179", label: "Project your voice to the back of the room. If you're speaking to 10 people, speak to the wall behind them.", theme: "exec-communication" },
  { id: "ec-180", label: "Control the agenda: 'Let's focus on the three things that matter most today...' — structure the room before it structures itself", theme: "exec-communication" },

  // --- Closing & Follow-Through ---
  { id: "ec-181", label: "Close with clarity: 'So the next step is X by Y date. I'll send a confirmation tonight.' — no ambiguity", theme: "exec-communication" },
  { id: "ec-182", label: "The same-day follow-up: send a thank you or summary within 4 hours of any important meeting", theme: "exec-communication" },
  { id: "ec-183", label: "Use the 'assumptive close': 'When would you like us to start?' — assumes the yes, moves to logistics", theme: "exec-communication" },
  { id: "ec-184", label: "After a good meeting, ask for the referral: 'Do you know anyone else who might benefit from this?' — timing is everything", theme: "exec-communication" },
  { id: "ec-185", label: "Keep promises EXACTLY. If you said 'by Wednesday', deliver Tuesday. Exceed expectations on delivery, always.", theme: "exec-communication" },
  { id: "ec-186", label: "Send the recap email with 3 sections: What we discussed, What we agreed, Next steps with dates and owners", theme: "exec-communication" },
  { id: "ec-187", label: "If they need to 'discuss internally', ask: 'When should I follow up? Thursday or Friday?' — set the date, don't leave it open", theme: "exec-communication" },
  { id: "ec-188", label: "Use the 'takeaway close': 'If you're not sure, let's pause. I want you to be fully confident.' — reverse psychology works.", theme: "exec-communication" },
  { id: "ec-189", label: "After closing a deal, immediately deliver something small. First impression post-sale sets the tone for the entire relationship.", theme: "exec-communication" },
  { id: "ec-190", label: "Send a handwritten thank-you note for big deals. In 2026, physical mail stands out like nothing else.", theme: "exec-communication" },

  // --- Daily Communication Challenges ---
  { id: "ec-191", label: "Challenge: have one conversation today where you only ask questions. Don't offer a single opinion. Just listen and ask.", theme: "exec-communication" },
  { id: "ec-192", label: "Challenge: use zero filler words today. Record yourself if needed. 'Um' and 'like' kill executive presence.", theme: "exec-communication" },
  { id: "ec-193", label: "Challenge: summarize a complex idea in exactly one sentence today. Brevity is the soul of executive communication.", theme: "exec-communication" },
  { id: "ec-194", label: "Challenge: make one cold outreach today using only 3 sentences. Intro, value prop, ask. That's it.", theme: "exec-communication" },
  { id: "ec-195", label: "Challenge: practice your elevator pitch in the mirror today. Time it. Under 30 seconds. Make it natural.", theme: "exec-communication" },
  { id: "ec-196", label: "Challenge: compliment someone's idea before adding your own today. 'Great point — building on that...'", theme: "exec-communication" },
  { id: "ec-197", label: "Challenge: end every conversation today with a clear next step. 'I'll send you X by tomorrow' — nothing left vague.", theme: "exec-communication" },
  { id: "ec-198", label: "Challenge: say 'no' to one request today that doesn't serve your priorities. Practice boundary-setting.", theme: "exec-communication" },
  { id: "ec-199", label: "Challenge: write a one-paragraph project update and send it to a client unprompted. Proactive updates build trust.", theme: "exec-communication" },
  { id: "ec-200", label: "Challenge: notice one non-verbal cue in a conversation today and respond to it. 'You seem thoughtful about that — what's on your mind?'", theme: "exec-communication" },
];
