import { PowerCheckItem } from "./power-checks";

// 200 financial fluency tips — business metrics, money talk, and investment language
export const financialFluencyTips: PowerCheckItem[] = [
  // --- Core Business Metrics ---
  { id: "ff-1", label: "Know this term: EBITDA — Earnings Before Interest, Tax, Depreciation & Amortization. The true profitability measure.", theme: "financial-fluency" },
  { id: "ff-2", label: "Know this term: ROI — Return on Investment. 'What's the ROI on this?' — the question every businessman asks", theme: "financial-fluency" },
  { id: "ff-3", label: "Know this term: Burn Rate — how fast you're spending money. 'What's your monthly burn rate?' — startup/VC vocabulary", theme: "financial-fluency" },
  { id: "ff-4", label: "Know this term: Runway — how many months you can survive at current burn rate. 'We have 6 months of runway.'", theme: "financial-fluency" },
  { id: "ff-5", label: "Know this term: Unit Economics — profit per customer/transaction. 'Are the unit economics positive?' — investor thinking", theme: "financial-fluency" },
  { id: "ff-6", label: "Know this term: CAC — Customer Acquisition Cost. How much it costs to get one client. Track yours.", theme: "financial-fluency" },
  { id: "ff-7", label: "Know this term: LTV — Lifetime Value. Total revenue from one client over the entire relationship. LTV should be 3x CAC minimum.", theme: "financial-fluency" },
  { id: "ff-8", label: "Know this term: Gross Margin — revenue minus direct costs. Software businesses should target 70%+ gross margins.", theme: "financial-fluency" },
  { id: "ff-9", label: "Know this term: Net Margin — what's left after ALL expenses. 'What's your net margin?' — asks how healthy the business really is.", theme: "financial-fluency" },
  { id: "ff-10", label: "Know this term: MRR — Monthly Recurring Revenue. The holy grail of software businesses. Build towards it.", theme: "financial-fluency" },

  // --- Revenue & Growth Metrics ---
  { id: "ff-11", label: "Know this: Revenue vs. Profit — Revenue is vanity, profit is sanity. A Rs 10L business with Rs 1L profit is worse than Rs 5L with Rs 3L profit.", theme: "financial-fluency" },
  { id: "ff-12", label: "Know this: ARR — Annual Recurring Revenue. MRR × 12. 'We're at Rs 12L ARR' sounds much more impressive than 'Rs 1L per month'.", theme: "financial-fluency" },
  { id: "ff-13", label: "Know this: Churn Rate — percentage of clients you lose per period. 5% monthly churn = 46% annual loss. Retention matters.", theme: "financial-fluency" },
  { id: "ff-14", label: "Know this: Revenue per Employee — total revenue ÷ team size. Software companies should target Rs 30L+ per person.", theme: "financial-fluency" },
  { id: "ff-15", label: "Know this: Pipeline Value — total potential revenue of all active prospects. 'My pipeline is Rs 15L' — sounds like a real business.", theme: "financial-fluency" },
  { id: "ff-16", label: "Know this: Conversion Rate — prospects → clients. If 1 in 5 meetings converts, you need 50 meetings for 10 clients. Work the math.", theme: "financial-fluency" },
  { id: "ff-17", label: "Know this: Average Deal Size — total revenue ÷ number of deals. Increasing this is the fastest path to Rs 1 crore.", theme: "financial-fluency" },
  { id: "ff-18", label: "Know this: Sales Cycle — average time from first contact to closed deal. Know yours. Shorter is better.", theme: "financial-fluency" },
  { id: "ff-19", label: "Know this: Win Rate — deals won ÷ deals attempted. Track this monthly. 30%+ is good for services.", theme: "financial-fluency" },
  { id: "ff-20", label: "Know this: Revenue Concentration Risk — if one client is >40% of revenue, you're vulnerable. Diversify.", theme: "financial-fluency" },

  // --- Cash Flow Management ---
  { id: "ff-21", label: "Cash is king: a profitable business can die from poor cash flow. Track when money comes IN, not when it's earned.", theme: "financial-fluency" },
  { id: "ff-22", label: "Invoice immediately upon delivery. Every day you delay invoicing is a day you delay getting paid.", theme: "financial-fluency" },
  { id: "ff-23", label: "Collect advance payments: 30-50% upfront is industry standard. It funds development and shows client commitment.", theme: "financial-fluency" },
  { id: "ff-24", label: "Know your payment terms: Net 15, Net 30, Net 45. Shorter terms = faster cash. Negotiate for shorter.", theme: "financial-fluency" },
  { id: "ff-25", label: "Track your DSO — Days Sales Outstanding. How long it takes clients to pay. Under 30 days is healthy.", theme: "financial-fluency" },
  { id: "ff-26", label: "Cash flow forecast: plot your expected income and expenses for the next 3 months. No surprises.", theme: "financial-fluency" },
  { id: "ff-27", label: "Milestone-based billing: break projects into 4-5 milestones, bill at each. Steady cash flow, reduced risk.", theme: "financial-fluency" },
  { id: "ff-28", label: "Never chase money verbally without a paper trail. Send a polite email/WhatsApp first: 'Gentle reminder on invoice #X'", theme: "financial-fluency" },
  { id: "ff-29", label: "Keep 3 months of operating expenses in reserve. This gives you the confidence to negotiate from strength.", theme: "financial-fluency" },
  { id: "ff-30", label: "Separate business and personal accounts. Professional financial management starts with clear boundaries.", theme: "financial-fluency" },

  // --- Pricing Strategy ---
  { id: "ff-31", label: "Never price by hours — price by value. A system that saves them Rs 5L/year is worth Rs 2L to build, regardless of hours.", theme: "financial-fluency" },
  { id: "ff-32", label: "The 10x rule: your solution should deliver at least 10x its cost in value. Rs 1L project should save/earn Rs 10L.", theme: "financial-fluency" },
  { id: "ff-33", label: "Use pricing tiers: Basic (Rs X), Professional (Rs 2X), Enterprise (Rs 4X). Most choose the middle. That's your target.", theme: "financial-fluency" },
  { id: "ff-34", label: "Anchor high: 'Our full package is Rs 5L, but for your scope, Rs 2L is more appropriate.' — the Rs 2L feels reasonable.", theme: "financial-fluency" },
  { id: "ff-35", label: "Monthly pricing feels smaller: Rs 25,000/month feels lighter than Rs 3,00,000/year. Same money, different psychology.", theme: "financial-fluency" },
  { id: "ff-36", label: "Never negotiate price — negotiate scope. 'I can reduce the price if we remove X and Y features.' — protects your rate.", theme: "financial-fluency" },
  { id: "ff-37", label: "Know your floor: the absolute minimum you'll accept. Below that, walk away. Walking away is powerful.", theme: "financial-fluency" },
  { id: "ff-38", label: "Add a maintenance/support tier: Rs 5K-15K/month ongoing. This is where recurring revenue lives.", theme: "financial-fluency" },
  { id: "ff-39", label: "Charge for discovery/consultation: even Rs 5K for a 'technology audit' qualifies serious buyers from time-wasters.", theme: "financial-fluency" },
  { id: "ff-40", label: "Package training separately: Rs 10K for 'team onboarding and training' — it's real value they'll happily pay for.", theme: "financial-fluency" },

  // --- Investment & Wealth Language ---
  { id: "ff-41", label: "Know this: CAGR — Compound Annual Growth Rate. 'My business grew at 40% CAGR last year' — investor-grade metric.", theme: "financial-fluency" },
  { id: "ff-42", label: "Know this: IRR — Internal Rate of Return. Used to compare investments. Higher IRR = better investment.", theme: "financial-fluency" },
  { id: "ff-43", label: "Know this: NPV — Net Present Value. Future money is worth less than today's money. Factor in time value.", theme: "financial-fluency" },
  { id: "ff-44", label: "Know this: P/E Ratio — Price to Earnings. For your business: if you earn Rs 10L/yr, at 5x P/E, your business is worth Rs 50L.", theme: "financial-fluency" },
  { id: "ff-45", label: "Know this: Multiple — businesses are valued as multiples of revenue or profit. SaaS businesses get 5-15x revenue multiples.", theme: "financial-fluency" },
  { id: "ff-46", label: "Know this: Equity vs. Debt — equity gives up ownership, debt must be repaid. Bootstrap when possible.", theme: "financial-fluency" },
  { id: "ff-47", label: "Know this: Angel Investment — early-stage funding from high-net-worth individuals. Your Gymkhana contacts ARE potential angels.", theme: "financial-fluency" },
  { id: "ff-48", label: "Know this: Bootstrap — building with your own revenue, no external funding. This is your path. Own it proudly.", theme: "financial-fluency" },
  { id: "ff-49", label: "Know this: Valuation — what your company is worth. Revenue × industry multiple. Start thinking in these terms.", theme: "financial-fluency" },
  { id: "ff-50", label: "Know this: Diversification — don't put all eggs in one basket. Multiple income streams = financial resilience.", theme: "financial-fluency" },

  // --- Tax & Compliance ---
  { id: "ff-51", label: "GST knowledge: software services attract 18% GST. Factor this into pricing. Rs 1L + GST = Rs 1.18L total invoice.", theme: "financial-fluency" },
  { id: "ff-52", label: "TDS awareness: clients may deduct 10% TDS on your invoices. Factor this into your cash flow calculations.", theme: "financial-fluency" },
  { id: "ff-53", label: "Section 44ADA: if turnover < Rs 75L, presumptive taxation allows 50% as expenses. Effective tax rate drops significantly.", theme: "financial-fluency" },
  { id: "ff-54", label: "Track all business expenses: software subscriptions, internet, phone, travel, meals with clients — they're all deductible.", theme: "financial-fluency" },
  { id: "ff-55", label: "Know the advance tax dates: June 15, Sept 15, Dec 15, March 15. Miss these and pay interest penalties.", theme: "financial-fluency" },
  { id: "ff-56", label: "Professional tax registration: mandatory in Maharashtra for professionals earning over Rs 75K/year.", theme: "financial-fluency" },
  { id: "ff-57", label: "Keep digital records of all invoices and payments. ITR scrutiny can go back 7 years. Be prepared.", theme: "financial-fluency" },
  { id: "ff-58", label: "When discussing money with clients, always mention 'plus GST' upfront. Avoid the surprise on the final invoice.", theme: "financial-fluency" },
  { id: "ff-59", label: "Consider a private limited company structure: it provides limited liability, credibility, and tax planning options.", theme: "financial-fluency" },
  { id: "ff-60", label: "Document everything: agreements, scope changes, payment terms. Verbal agreements don't hold up. Protect yourself.", theme: "financial-fluency" },

  // --- Talking Money with Confidence ---
  { id: "ff-61", label: "When asked 'What's your rate?': 'It depends on scope. Our projects typically range from Rs 50K to Rs 5L. Tell me what you need.'", theme: "financial-fluency" },
  { id: "ff-62", label: "When asked 'Can you do it cheaper?': 'I can adjust the scope to fit your budget. What's most important to you?'", theme: "financial-fluency" },
  { id: "ff-63", label: "When asked 'Why so expensive?': 'Let me show you what you're getting — and what it costs to do this wrong.'", theme: "financial-fluency" },
  { id: "ff-64", label: "When negotiating: always ask for their budget first. 'What budget have you allocated for this?' — they anchor, not you.", theme: "financial-fluency" },
  { id: "ff-65", label: "After stating your price, add: 'This includes X, Y, and Z' — immediately justify with value, not cost breakdown.", theme: "financial-fluency" },
  { id: "ff-66", label: "Present three options: 'Rs 1L for basic, Rs 2L for professional, Rs 3.5L for premium.' Most pick the middle. Design for that.", theme: "financial-fluency" },
  { id: "ff-67", label: "Use comparison anchoring: 'A full-time developer costs Rs 50K/month. My entire project costs less than 3 months of that salary.'", theme: "financial-fluency" },
  { id: "ff-68", label: "Frame cost as daily: 'Rs 2.4L over 12 months is just Rs 650/day — less than your daily chai budget for the office.'", theme: "financial-fluency" },
  { id: "ff-69", label: "When they say 'Let me think about it': 'Absolutely. What specific information would help you decide?' — uncover the real blocker.", theme: "financial-fluency" },
  { id: "ff-70", label: "Confidence phrase: 'We're not the cheapest option — and our clients are glad about that.' — own the premium position.", theme: "financial-fluency" },

  // --- Business Model Thinking ---
  { id: "ff-71", label: "Revenue model types: one-time (projects), recurring (SaaS/maintenance), usage-based (per transaction). Aim for mix of all three.", theme: "financial-fluency" },
  { id: "ff-72", label: "Know: Freemium model — give the basic version free, charge for premium. JSG ticket app → paid for other samaj organizations.", theme: "financial-fluency" },
  { id: "ff-73", label: "Know: Platform model — connect buyers and sellers, take a percentage. Could you build a community management platform?", theme: "financial-fluency" },
  { id: "ff-74", label: "Know: Retainer model — monthly fixed fee for ongoing support/development. Most stable cash flow. Build towards this.", theme: "financial-fluency" },
  { id: "ff-75", label: "Know: Licensing model — build once, sell many times. That member management system could be licensed to 100 samaj organizations.", theme: "financial-fluency" },
  { id: "ff-76", label: "Know: White-label model — build it, let others sell it under their brand. You provide the technology, they provide the market.", theme: "financial-fluency" },
  { id: "ff-77", label: "Know: Marketplace model — bring supply and demand together. Service marketplaces for community events, vendors, professionals.", theme: "financial-fluency" },
  { id: "ff-78", label: "Know: Productized service — standardized scope, fixed price, repeatable delivery. 'Community Website Package: Rs 75K, 4-week delivery.'", theme: "financial-fluency" },
  { id: "ff-79", label: "Know: Partnership model — revenue share with channel partners. Give gym secretaries 10% for every referral. Win-win.", theme: "financial-fluency" },
  { id: "ff-80", label: "Know: Tiered pricing — different feature sets at different price points. Let the client choose their level of investment.", theme: "financial-fluency" },

  // --- Financial Ratios Businessmen Use ---
  { id: "ff-81", label: "Current Ratio = Current Assets ÷ Current Liabilities. Above 1.5 is healthy. Below 1 means trouble. Know yours.", theme: "financial-fluency" },
  { id: "ff-82", label: "Debt-to-Equity Ratio: how much debt vs. owner's money. Lower is safer. Kutchi businessmen respect low-debt businesses.", theme: "financial-fluency" },
  { id: "ff-83", label: "Working Capital = Current Assets - Current Liabilities. Positive means you can pay bills. Track this monthly.", theme: "financial-fluency" },
  { id: "ff-84", label: "Profit Margin = Net Income ÷ Revenue × 100. Software businesses should target 30-50%. Know your number.", theme: "financial-fluency" },
  { id: "ff-85", label: "Revenue per Client: total revenue ÷ number of clients. If it's low, you need bigger clients, not more clients.", theme: "financial-fluency" },
  { id: "ff-86", label: "Utilization Rate: billable hours ÷ total hours. If you're at 40%, you're spending too much time on non-revenue activities.", theme: "financial-fluency" },
  { id: "ff-87", label: "Payback Period: how long before an investment pays for itself. 'This system pays for itself in 4 months of saved labor.'", theme: "financial-fluency" },
  { id: "ff-88", label: "Break-even Analysis: fixed costs ÷ (price - variable cost per unit). Know how many projects you need to break even.", theme: "financial-fluency" },
  { id: "ff-89", label: "Cash Conversion Cycle: how quickly you turn work into cash. Invoice fast, collect faster, spend wisely.", theme: "financial-fluency" },
  { id: "ff-90", label: "Customer Concentration: if top 3 clients = >70% revenue, diversify urgently. That's fragile, not successful.", theme: "financial-fluency" },

  // --- Investment & Wealth Building ---
  { id: "ff-91", label: "Rule of 72: divide 72 by your growth rate to see how long it takes to double. 15% growth = double in ~5 years.", theme: "financial-fluency" },
  { id: "ff-92", label: "Compound interest applied to business: reinvest 30% of profit into growth. Marketing, tools, skills, hiring. It compounds.", theme: "financial-fluency" },
  { id: "ff-93", label: "Your business IS your biggest investment. Every hour you put in builds an asset that generates returns.", theme: "financial-fluency" },
  { id: "ff-94", label: "Think about exit value: even if you never sell, build as if you will. It forces discipline and systems.", theme: "financial-fluency" },
  { id: "ff-95", label: "Revenue diversity = financial safety: project income + maintenance contracts + consulting + product licensing = resilience.", theme: "financial-fluency" },
  { id: "ff-96", label: "Asset-light business model: software needs no warehouse, no inventory, no heavy equipment. Your margins should reflect this.", theme: "financial-fluency" },
  { id: "ff-97", label: "Your hourly rate should fund your annual goal. Rs 1 crore ÷ 2000 billable hours = Rs 5000/hour minimum.", theme: "financial-fluency" },
  { id: "ff-98", label: "Track net worth quarterly, not just income. Assets - liabilities = net worth. This is the millionaire's real scoreboard.", theme: "financial-fluency" },
  { id: "ff-99", label: "Pay yourself first: before any business expense, allocate your personal income. The business serves you, not the reverse.", theme: "financial-fluency" },
  { id: "ff-100", label: "The fastest path to Rs 1 crore revenue: 10 clients × Rs 10L each. Or 20 clients × Rs 5L each. Pick your strategy.", theme: "financial-fluency" },

  // --- Speaking About Money in Meetings ---
  { id: "ff-101", label: "Use this phrase: 'Let's look at the numbers' — instantly positions you as analytical and serious", theme: "financial-fluency" },
  { id: "ff-102", label: "Use this phrase: 'What's the cost of doing nothing?' — quantifies inaction", theme: "financial-fluency" },
  { id: "ff-103", label: "Use this phrase: 'On a per-unit basis, this works out to...' — breaks big numbers into digestible ones", theme: "financial-fluency" },
  { id: "ff-104", label: "Use this phrase: 'The payback period on this is X months' — frames cost as a temporary investment", theme: "financial-fluency" },
  { id: "ff-105", label: "Use this phrase: 'This generates a Y% return' — speaks directly to the business mind", theme: "financial-fluency" },
  { id: "ff-106", label: "Use this phrase: 'Let me walk you through the P&L impact' — profit & loss, the language of business owners", theme: "financial-fluency" },
  { id: "ff-107", label: "Use this phrase: 'Cash-flow positive from month 3' — shows you think about when money flows, not just amounts", theme: "financial-fluency" },
  { id: "ff-108", label: "Use this phrase: 'The total cost of ownership is...' — includes hidden costs that cheap alternatives ignore", theme: "financial-fluency" },
  { id: "ff-109", label: "Use this phrase: 'What's this worth to your business annually?' — let them put a number on the value", theme: "financial-fluency" },
  { id: "ff-110", label: "Use this phrase: 'This is a capex investment, not an opex drain' — capital expenditure vs. operating expense framing", theme: "financial-fluency" },

  // --- Financial Planning for Your Business ---
  { id: "ff-111", label: "Create a simple financial plan: projected income - projected expenses = projected profit. Do this for the next 12 months.", theme: "financial-fluency" },
  { id: "ff-112", label: "Set a revenue target for each month. Write it down. Track it weekly. What gets measured gets managed.", theme: "financial-fluency" },
  { id: "ff-113", label: "Know your fixed costs: rent, internet, phone, subscriptions. These must be covered before any variable spending.", theme: "financial-fluency" },
  { id: "ff-114", label: "Know your variable costs: hosting, API usage, subcontractors. These scale with revenue — that's healthy.", theme: "financial-fluency" },
  { id: "ff-115", label: "Set a savings rate: aim to save/invest 20% of business income. Build a war chest for slow months.", theme: "financial-fluency" },
  { id: "ff-116", label: "Review finances weekly: 15 minutes every Friday. What came in? What went out? What's expected next week?", theme: "financial-fluency" },
  { id: "ff-117", label: "Quarterly review: compare actual vs. planned revenue. If behind, ask: what do I need to change in the next 90 days?", theme: "financial-fluency" },
  { id: "ff-118", label: "Year-end review: total revenue, total profit, total clients served, average deal size. Know your numbers cold.", theme: "financial-fluency" },
  { id: "ff-119", label: "Budget for learning: Rs 50K/year on courses, books, conferences. It's the highest-ROI investment you can make.", theme: "financial-fluency" },
  { id: "ff-120", label: "Budget for tools: the right software (hosting, analytics, project management) saves more time than it costs.", theme: "financial-fluency" },

  // --- Understanding Client Finances ---
  { id: "ff-121", label: "Know when budget cycles happen: most businesses plan budgets in March-April (fiscal year). Pitch in February.", theme: "financial-fluency" },
  { id: "ff-122", label: "Understand IT budgets: even small businesses allocate 3-5% of revenue to technology. A Rs 10 crore business = Rs 30-50L IT budget.", theme: "financial-fluency" },
  { id: "ff-123", label: "Know the difference: capex (one-time project) vs. opex (ongoing service). Different budget pockets, different approval processes.", theme: "financial-fluency" },
  { id: "ff-124", label: "Understand payment authority: who signs checks? The person you're talking to may not have spending authority. Find the decision-maker.", theme: "financial-fluency" },
  { id: "ff-125", label: "Ask about their current IT spending: 'What are you spending on technology today?' — positions your solution as replacement, not addition.", theme: "financial-fluency" },
  { id: "ff-126", label: "Understand their revenue model: if they make money per member, show how your system increases members. Align with their business.", theme: "financial-fluency" },
  { id: "ff-127", label: "Show them the 'hidden costs' of their current process: manual labor, errors, missed opportunities, frustrated members.", theme: "financial-fluency" },
  { id: "ff-128", label: "Frame your price against their cost of a full-time employee: 'My annual fee is less than one junior developer's salary.'", theme: "financial-fluency" },
  { id: "ff-129", label: "Use the 'cost per member' frame for samaj clients: 'Rs 2L ÷ 5000 members = Rs 40 per member per year. Less than a cup of chai.'", theme: "financial-fluency" },
  { id: "ff-130", label: "Understand their pain in financial terms: 'How much time does your team spend on X manually?' → convert to rupees.", theme: "financial-fluency" },

  // --- Proposal & Contract Financials ---
  { id: "ff-131", label: "Always itemize your proposal: development, design, testing, deployment, training, support. Transparency builds trust.", theme: "financial-fluency" },
  { id: "ff-132", label: "Include payment terms in every proposal: 30% advance, 30% at mid-milestone, 30% on delivery, 10% after 30-day support.", theme: "financial-fluency" },
  { id: "ff-133", label: "Add a validity period: 'This proposal is valid for 30 days.' Creates urgency and protects you from price changes.", theme: "financial-fluency" },
  { id: "ff-134", label: "Include a change request clause: 'Changes beyond agreed scope will be quoted separately.' — prevents scope creep.", theme: "financial-fluency" },
  { id: "ff-135", label: "Show ROI in the proposal: 'Investment: Rs 2L. Expected annual savings: Rs 8L. Payback: 3 months.' — irresistible math.", theme: "financial-fluency" },
  { id: "ff-136", label: "Add optional add-ons at the bottom: 'Optional: mobile app version (+Rs 1L), analytics dashboard (+Rs 50K)' — upsell elegantly.", theme: "financial-fluency" },
  { id: "ff-137", label: "Include a timeline with payment milestones tied to deliverables. Clients feel safer when payments are tied to tangible progress.", theme: "financial-fluency" },
  { id: "ff-138", label: "Always mention what's NOT included: hosting, domain, third-party API costs, future feature requests. Prevents disputes.", theme: "financial-fluency" },
  { id: "ff-139", label: "Offer an annual maintenance contract (AMC) at 15-20% of project cost. Rs 3L project = Rs 45K-60K annual recurring revenue.", theme: "financial-fluency" },
  { id: "ff-140", label: "Add a satisfaction guarantee if appropriate: '30-day money back if not satisfied.' Reduces risk for the client, increases conversion.", theme: "financial-fluency" },

  // --- Financial Vocabulary for Networking ---
  { id: "ff-141", label: "Drop naturally in conversation: 'The market cap of that sector is growing at 18% CAGR' — sounds like you read financial reports", theme: "financial-fluency" },
  { id: "ff-142", label: "Know: FOMO vs. fundamentals — when Gymkhana uncles talk stocks, ask 'What are the fundamentals?' — sounds like a pro investor", theme: "financial-fluency" },
  { id: "ff-143", label: "Know: Risk-adjusted returns — 'Sure, crypto returned 100%, but what's the risk-adjusted return?' — instant credibility", theme: "financial-fluency" },
  { id: "ff-144", label: "Know: Asset allocation — 'How's your portfolio allocated across debt, equity, and real estate?' — wealth management vocabulary", theme: "financial-fluency" },
  { id: "ff-145", label: "Know: Carry forward losses — stock market losses can be carried forward for 8 years to offset future gains. Know this.", theme: "financial-fluency" },
  { id: "ff-146", label: "Know: Capital gains — short term (< 1 year, 15% for equity) vs. long term (>1 year, 10% above Rs 1L for equity)", theme: "financial-fluency" },
  { id: "ff-147", label: "Know: Debt-to-income ratio — banks look at this for loans. Keep business debt under 40% of income.", theme: "financial-fluency" },
  { id: "ff-148", label: "Know: Working capital loan vs. term loan — working capital for daily operations, term loan for capital expenditure", theme: "financial-fluency" },
  { id: "ff-149", label: "Know: Cash flow statement vs. P&L — P&L shows profitability, cash flow shows liquidity. Both matter.", theme: "financial-fluency" },
  { id: "ff-150", label: "Know: Book value vs. market value — what your assets are worth on paper vs. what someone would pay. Build market value.", theme: "financial-fluency" },

  // --- Million-Rupee Mindset ---
  { id: "ff-151", label: "Rs 1 crore ÷ 12 months = Rs 8.33L/month. That's 2-3 medium projects per month. Achievable with the right pipeline.", theme: "financial-fluency" },
  { id: "ff-152", label: "Think in annual terms: Rs 50K/month in maintenance contracts × 10 clients = Rs 60L/year. That's your baseline.", theme: "financial-fluency" },
  { id: "ff-153", label: "The millionaire path: Rs 20L from projects + Rs 30L from products + Rs 10L from maintenance + Rs 40L from licensing = Rs 1 crore.", theme: "financial-fluency" },
  { id: "ff-154", label: "Price your time like a millionaire: if your goal is Rs 1 crore, your hourly rate should be Rs 5000. Act accordingly.", theme: "financial-fluency" },
  { id: "ff-155", label: "Track 'money left on the table': follow-ups you didn't send, proposals you didn't write, meetings you didn't take. That's lost revenue.", theme: "financial-fluency" },
  { id: "ff-156", label: "Calculate your 'revenue per hour of selling': every hour networking at Gymkhana should eventually generate X in revenue. Track it.", theme: "financial-fluency" },
  { id: "ff-157", label: "Think about wealth, not income: income stops when you stop working. Wealth grows while you sleep. Build assets.", theme: "financial-fluency" },
  { id: "ff-158", label: "Your software products are digital assets. Once built, they can generate income forever with minimal marginal cost. Build products.", theme: "financial-fluency" },
  { id: "ff-159", label: "Recurring revenue is the key to wealth: Rs 10L in MRR means Rs 1.2 crore ARR. Focus on building monthly recurring clients.", theme: "financial-fluency" },
  { id: "ff-160", label: "The 'millionaire math' check: are your daily activities aligned with Rs 1 crore/year? If not, what needs to change today?", theme: "financial-fluency" },

  // --- Investor & Partnership Language ---
  { id: "ff-161", label: "Know how to describe your business to an investor: TAM (total market), SAM (serviceable market), SOM (your realistic target)", theme: "financial-fluency" },
  { id: "ff-162", label: "Know: Revenue share vs. equity — partnership structures where you share revenue (lower risk) vs. share ownership (higher reward)", theme: "financial-fluency" },
  { id: "ff-163", label: "Know: Sweat equity — contributing work instead of money for ownership. Your code has value. Know its worth.", theme: "financial-fluency" },
  { id: "ff-164", label: "Know: Vesting — ownership earned over time. If partnering, use 4-year vesting with 1-year cliff. Protects everyone.", theme: "financial-fluency" },
  { id: "ff-165", label: "Know: Term sheet basics — if someone offers investment, key terms are: valuation, equity %, board seats, liquidation preference", theme: "financial-fluency" },
  { id: "ff-166", label: "Know: Founder-friendly terms — maintain majority control, anti-dilution protection, first right of refusal. Protect yourself.", theme: "financial-fluency" },
  { id: "ff-167", label: "Know: Convertible note — a loan that converts to equity later. Common for early-stage funding. Understand the conversion terms.", theme: "financial-fluency" },
  { id: "ff-168", label: "Know: Due diligence — what investors check before investing. Clean books, clear contracts, IP ownership. Be ready.", theme: "financial-fluency" },
  { id: "ff-169", label: "Know: Valuation methods — revenue multiple, profit multiple, comparable transactions. Know what your business is worth.", theme: "financial-fluency" },
  { id: "ff-170", label: "Know: Cap table — shows who owns what percentage. Keep it simple and clean. Avoid giving away equity casually.", theme: "financial-fluency" },

  // --- Financial Red Flags to Watch ---
  { id: "ff-171", label: "Red flag: client says 'money is no object' — it always is. Get the budget in writing.", theme: "financial-fluency" },
  { id: "ff-172", label: "Red flag: 'We'll pay you from the profits' — no guaranteed payment = no deal. Charge upfront.", theme: "financial-fluency" },
  { id: "ff-173", label: "Red flag: 'Just build it and we'll figure out the price later' — scope and price ALWAYS before work begins.", theme: "financial-fluency" },
  { id: "ff-174", label: "Red flag: frequent scope changes without price adjustments — this is scope creep eating your profit.", theme: "financial-fluency" },
  { id: "ff-175", label: "Red flag: client delays payments repeatedly despite reminders — escalate early. 'We need to discuss payment terms.'", theme: "financial-fluency" },
  { id: "ff-176", label: "Red flag: 'We'll give you more work later if you discount now' — future promises don't pay today's bills.", theme: "financial-fluency" },
  { id: "ff-177", label: "Red flag: client compares your price to Fiverr/Upwork — they don't understand value. Educate or walk away.", theme: "financial-fluency" },
  { id: "ff-178", label: "Red flag: no written agreement — ALWAYS have a signed proposal/contract before starting work. No exceptions.", theme: "financial-fluency" },
  { id: "ff-179", label: "Red flag: multiple stakeholders with conflicting budgets — find the actual decision-maker and align with them.", theme: "financial-fluency" },
  { id: "ff-180", label: "Red flag: 'Our last developer charged less' — respond: 'And that didn't work out, which is why you're talking to me.'", theme: "financial-fluency" },

  // --- Daily Financial Habits ---
  { id: "ff-181", label: "Check your bank balance every morning. Knowing your exact number removes anxiety and drives action.", theme: "financial-fluency" },
  { id: "ff-182", label: "Send one invoice or payment reminder today. Revenue doesn't arrive magically — you have to ask for it.", theme: "financial-fluency" },
  { id: "ff-183", label: "Record every business expense today, no matter how small. Tax deductions add up. Rs 500/day = Rs 1.5L/year.", theme: "financial-fluency" },
  { id: "ff-184", label: "Review your pipeline value today: how much potential revenue is in various stages? Is it enough to hit your target?", theme: "financial-fluency" },
  { id: "ff-185", label: "Think about one way to increase your average deal size. Add a premium tier? Bundle more services? Upsell maintenance?", theme: "financial-fluency" },
  { id: "ff-186", label: "Calculate today: how many billable hours did you work this week? Are you at your target utilization rate?", theme: "financial-fluency" },
  { id: "ff-187", label: "Ask yourself: 'What's one expense I can eliminate or reduce this month?' — frugality is underrated in wealth-building.", theme: "financial-fluency" },
  { id: "ff-188", label: "Think about one recurring revenue opportunity you haven't pursued. A client who might need monthly support? A product idea?", theme: "financial-fluency" },
  { id: "ff-189", label: "Review your pricing: when was the last time you raised rates? If it's been over a year, you're effectively taking a pay cut.", theme: "financial-fluency" },
  { id: "ff-190", label: "End the day knowing your exact financial position: cash in bank, outstanding invoices, upcoming expenses. Knowledge is power.", theme: "financial-fluency" },

  // --- Wealth Wisdom ---
  { id: "ff-191", label: "Warren Buffett: 'Rule No. 1: Never lose money. Rule No. 2: Never forget Rule No. 1.' — protect your capital first.", theme: "financial-fluency" },
  { id: "ff-192", label: "Charlie Munger: 'The first rule of compounding: never interrupt it unnecessarily.' — be patient with your business growth.", theme: "financial-fluency" },
  { id: "ff-193", label: "Naval Ravikant: 'Earn with your mind, not your time.' — build products and systems, not just services.", theme: "financial-fluency" },
  { id: "ff-194", label: "Peter Thiel: 'Competition is for losers.' — don't compete on price. Create a unique offering no one else can match.", theme: "financial-fluency" },
  { id: "ff-195", label: "Jeff Bezos: 'Your margin is my opportunity.' — if competitors have high margins, you can undercut. If they're cheap, go premium.", theme: "financial-fluency" },
  { id: "ff-196", label: "Dhirubhai Ambani: 'Think big, think fast, think ahead.' — vision + speed + foresight = wealth creation.", theme: "financial-fluency" },
  { id: "ff-197", label: "Ratan Tata: 'I don't believe in taking right decisions. I take decisions and then make them right.' — decide and commit.", theme: "financial-fluency" },
  { id: "ff-198", label: "Azim Premji: 'If people are not laughing at your goals, your goals are too small.' — Rs 1 crore is just the beginning.", theme: "financial-fluency" },
  { id: "ff-199", label: "NR Narayana Murthy: 'Growth is painful. Change is painful. But nothing is as painful as staying where you don't belong.'", theme: "financial-fluency" },
  { id: "ff-200", label: "Your own rule: 'Every rupee I earn is proof that my 25 years of experience has value. The market will reward persistence.'", theme: "financial-fluency" },
];
