import { PowerCheckItem } from "./power-checks";

// 200 corporate language tips — actual phrases and sentences to use in conversation
export const corporateLanguageTips: PowerCheckItem[] = [
  // --- Opening & Framing ---
  { id: "cl-1", label: "Use today: 'Let me give you the 30-second version...' — shows you respect their time", theme: "corporate-language" },
  { id: "cl-2", label: "Use today: 'The way I see it, there are three options...' — instantly sounds structured", theme: "corporate-language" },
  { id: "cl-3", label: "Use today: 'Let me cut to the chase...' — executives love directness", theme: "corporate-language" },
  { id: "cl-4", label: "Use today: 'Here's what I'm hearing...' — powerful way to summarize and take control", theme: "corporate-language" },
  { id: "cl-5", label: "Use today: 'Let me frame this differently...' — reposition any conversation elegantly", theme: "corporate-language" },
  { id: "cl-6", label: "Use today: 'The bottom line is...' — skip the noise, land the punch", theme: "corporate-language" },
  { id: "cl-7", label: "Use today: 'If I were in your shoes...' — builds instant empathy and trust", theme: "corporate-language" },
  { id: "cl-8", label: "Use today: 'Let me play devil's advocate for a moment...' — shows intellectual depth", theme: "corporate-language" },
  { id: "cl-9", label: "Use today: 'Here's the real question we should be asking...' — reframe like a CEO", theme: "corporate-language" },
  { id: "cl-10", label: "Use today: 'I want to be transparent about something...' — builds massive trust", theme: "corporate-language" },

  // --- Agreement & Alignment ---
  { id: "cl-11", label: "Use today: 'We're aligned on the vision, let's discuss execution' — separates strategy from tactics", theme: "corporate-language" },
  { id: "cl-12", label: "Use today: 'That's a valid point — and here's how it connects to...' — acknowledge before redirecting", theme: "corporate-language" },
  { id: "cl-13", label: "Use today: 'Let's make sure we're solving the right problem first' — sounds like a consultant", theme: "corporate-language" },
  { id: "cl-14", label: "Use today: 'I think we're violently agreeing here' — diffuse tension with humor", theme: "corporate-language" },
  { id: "cl-15", label: "Use today: 'Can we align on the success criteria before we go further?' — pure MBA thinking", theme: "corporate-language" },
  { id: "cl-16", label: "Use today: 'Let's park that for now and circle back' — graceful way to move past tangents", theme: "corporate-language" },
  { id: "cl-17", label: "Use today: 'I'm going to push back gently on that...' — disagree without being disagreeable", theme: "corporate-language" },
  { id: "cl-18", label: "Use today: 'That resonates with me' — more executive than 'I agree'", theme: "corporate-language" },
  { id: "cl-19", label: "Use today: 'Let me build on what you just said...' — makes them feel heard, you sound collaborative", theme: "corporate-language" },
  { id: "cl-20", label: "Use today: 'We need to be intellectually honest about this' — signals maturity", theme: "corporate-language" },

  // --- Business Discussion ---
  { id: "cl-21", label: "Use today: 'What's the opportunity cost of not doing this?' — flip any objection", theme: "corporate-language" },
  { id: "cl-22", label: "Use today: 'Let's talk about the value proposition here' — sounds like you think in business models", theme: "corporate-language" },
  { id: "cl-23", label: "Use today: 'This is a classic build-versus-buy decision' — shows strategic vocabulary", theme: "corporate-language" },
  { id: "cl-24", label: "Use today: 'What does the data tell us?' — data-driven people command respect", theme: "corporate-language" },
  { id: "cl-25", label: "Use today: 'Let's quantify the impact before we decide' — sounds like a CFO", theme: "corporate-language" },
  { id: "cl-26", label: "Use today: 'We need to think about this from the customer's perspective' — customer-centricity wins", theme: "corporate-language" },
  { id: "cl-27", label: "Use today: 'What's the total addressable market for this?' — TAM — classic investor language", theme: "corporate-language" },
  { id: "cl-28", label: "Use today: 'Is this scalable, or is it a one-off solution?' — think like a CEO, not a coder", theme: "corporate-language" },
  { id: "cl-29", label: "Use today: 'Let's focus on the 80/20 — what 20% of effort gives 80% of the result?' — Pareto thinking", theme: "corporate-language" },
  { id: "cl-30", label: "Use today: 'We're leaving money on the table if we don't...' — creates urgency around opportunity", theme: "corporate-language" },

  // --- Negotiation & Persuasion ---
  { id: "cl-31", label: "Use today: 'I'm not the cheapest option, and here's why that matters...' — own your pricing", theme: "corporate-language" },
  { id: "cl-32", label: "Use today: 'What would it take to make this a yes?' — direct, confident closing", theme: "corporate-language" },
  { id: "cl-33", label: "Use today: 'Let me share what's worked for other clients in your position...' — social proof", theme: "corporate-language" },
  { id: "cl-34", label: "Use today: 'I want to make sure this is a win-win' — partnership language, not vendor language", theme: "corporate-language" },
  { id: "cl-35", label: "Use today: 'The risk of inaction here is greater than the risk of action' — nudge to decision", theme: "corporate-language" },
  { id: "cl-36", label: "Use today: 'I'd rather be upfront now than surprise you later' — trust-building transparency", theme: "corporate-language" },
  { id: "cl-37", label: "Use today: 'This is an investment, not an expense' — reframe cost as value", theme: "corporate-language" },
  { id: "cl-38", label: "Use today: 'Happy to walk you through the numbers' — confidence in your pricing", theme: "corporate-language" },
  { id: "cl-39", label: "Use today: 'Let me show you the cost of the current approach' — make status quo expensive", theme: "corporate-language" },
  { id: "cl-40", label: "Use today: 'I'd love your honest feedback — what's holding you back?' — uncover the real objection", theme: "corporate-language" },

  // --- Meeting & Conversation Control ---
  { id: "cl-41", label: "Use today: 'Before we dive in, let me set the context...' — take ownership of any meeting", theme: "corporate-language" },
  { id: "cl-42", label: "Use today: 'Let me summarize where we are and what's next' — sounds like the person in charge", theme: "corporate-language" },
  { id: "cl-43", label: "Use today: 'That's a great question — let me think about that for a second' — pausing is power", theme: "corporate-language" },
  { id: "cl-44", label: "Use today: 'Let's not boil the ocean here — what's the MVP?' — focus on what matters", theme: "corporate-language" },
  { id: "cl-45", label: "Use today: 'I want to make sure we leave with clear action items' — sounds like a leader", theme: "corporate-language" },
  { id: "cl-46", label: "Use today: 'Who owns this going forward?' — accountability language executives use", theme: "corporate-language" },
  { id: "cl-47", label: "Use today: 'Let's time-box this discussion to 10 minutes' — shows you value efficiency", theme: "corporate-language" },
  { id: "cl-48", label: "Use today: 'Can I get a quick temperature check — where does everyone stand?' — reads the room", theme: "corporate-language" },
  { id: "cl-49", label: "Use today: 'Let me capture the key takeaways...' — the person who summarizes controls the narrative", theme: "corporate-language" },
  { id: "cl-50", label: "Use today: 'I want to respect everyone's time — let's prioritize' — executive time-consciousness", theme: "corporate-language" },

  // --- Problem-Solving Language ---
  { id: "cl-51", label: "Use today: 'Let's separate the signal from the noise here' — shows analytical thinking", theme: "corporate-language" },
  { id: "cl-52", label: "Use today: 'What's the root cause, not just the symptom?' — goes deeper than surface level", theme: "corporate-language" },
  { id: "cl-53", label: "Use today: 'Let's map out the dependencies before we commit' — project management thinking", theme: "corporate-language" },
  { id: "cl-54", label: "Use today: 'What are the second-order effects of this decision?' — think two steps ahead", theme: "corporate-language" },
  { id: "cl-55", label: "Use today: 'Let's stress-test this assumption' — sounds like a strategist", theme: "corporate-language" },
  { id: "cl-56", label: "Use today: 'What's our fallback if this doesn't work?' — contingency thinking", theme: "corporate-language" },
  { id: "cl-57", label: "Use today: 'Let's do a quick SWOT on this' — classic MBA framework drop", theme: "corporate-language" },
  { id: "cl-58", label: "Use today: 'We need to derisk this before scaling' — venture capital vocabulary", theme: "corporate-language" },
  { id: "cl-59", label: "Use today: 'Let me walk you through the tradeoffs' — engineers-turned-executives talk like this", theme: "corporate-language" },
  { id: "cl-60", label: "Use today: 'What does success look like in 6 months?' — future-focused thinking", theme: "corporate-language" },

  // --- Relationship & Networking Language ---
  { id: "cl-61", label: "Use today: 'I'd love to pick your brain on something...' — flattering way to start a conversation", theme: "corporate-language" },
  { id: "cl-62", label: "Use today: 'You know what I admire about your business?' — specific praise opens doors", theme: "corporate-language" },
  { id: "cl-63", label: "Use today: 'I think there might be synergies between what we do...' — partnership opener", theme: "corporate-language" },
  { id: "cl-64", label: "Use today: 'I have someone you should meet' — connectors are the most powerful people", theme: "corporate-language" },
  { id: "cl-65", label: "Use today: 'What's keeping you up at night these days?' — uncovers pain points naturally", theme: "corporate-language" },
  { id: "cl-66", label: "Use today: 'I've been following your growth — impressive trajectory' — shows you pay attention", theme: "corporate-language" },
  { id: "cl-67", label: "Use today: 'Let me know how I can add value to what you're doing' — service-first mindset", theme: "corporate-language" },
  { id: "cl-68", label: "Use today: 'Your perspective on this would be really valuable...' — make them the expert", theme: "corporate-language" },
  { id: "cl-69", label: "Use today: 'We should grab coffee — I have an idea I'd love to bounce off you' — creates intrigue", theme: "corporate-language" },
  { id: "cl-70", label: "Use today: 'I respect what you've built — it takes real conviction' — deeper than a compliment", theme: "corporate-language" },

  // --- Technology & Digital Transformation ---
  { id: "cl-71", label: "Use today: 'Technology should be an enabler, not a headache' — positions you as the solution", theme: "corporate-language" },
  { id: "cl-72", label: "Use today: 'Your competitors are already digitizing this...' — create urgency without fear", theme: "corporate-language" },
  { id: "cl-73", label: "Use today: 'The real ROI of software is the time it frees up for you' — sell outcomes, not features", theme: "corporate-language" },
  { id: "cl-74", label: "Use today: 'This can be automated — you shouldn't be spending mental energy on this' — positions technology as liberation", theme: "corporate-language" },
  { id: "cl-75", label: "Use today: 'Data is the new oil — but only if you can access it' — makes analytics sound essential", theme: "corporate-language" },
  { id: "cl-76", label: "Use today: 'We build systems that scale with your business, not against it' — growth-focused pitch", theme: "corporate-language" },
  { id: "cl-77", label: "Use today: 'The cost of maintaining outdated systems compounds every year' — technical debt for non-techies", theme: "corporate-language" },
  { id: "cl-78", label: "Use today: 'AI can handle the 80% — your team focuses on the 20% that needs human judgment' — AI positioning", theme: "corporate-language" },
  { id: "cl-79", label: "Use today: 'Think of software as your 24/7 employee that never takes leave' — powerful metaphor for Indian businessmen", theme: "corporate-language" },
  { id: "cl-80", label: "Use today: 'A dashboard gives you the pulse of your business in 30 seconds' — sell visibility", theme: "corporate-language" },

  // --- Leadership & Authority ---
  { id: "cl-81", label: "Use today: 'I take full ownership of this' — accountability is rare and magnetic", theme: "corporate-language" },
  { id: "cl-82", label: "Use today: 'Let me be direct with you...' — directness signals confidence", theme: "corporate-language" },
  { id: "cl-83", label: "Use today: 'Here's my recommendation...' — not 'I think maybe we could...'", theme: "corporate-language" },
  { id: "cl-84", label: "Use today: 'I've seen this pattern before — here's what works...' — leverage experience", theme: "corporate-language" },
  { id: "cl-85", label: "Use today: 'Let me take this offline and come back with a plan' — shows initiative", theme: "corporate-language" },
  { id: "cl-86", label: "Use today: 'I don't have the answer right now, but I'll find out' — honesty > bluffing", theme: "corporate-language" },
  { id: "cl-87", label: "Use today: 'That's outside my expertise, but I know someone who...' — connector, not pretender", theme: "corporate-language" },
  { id: "cl-88", label: "Use today: 'My commitment to you is...' — commitment language is powerful", theme: "corporate-language" },
  { id: "cl-89", label: "Use today: 'Here's what I need from you to make this happen' — clear asks show leadership", theme: "corporate-language" },
  { id: "cl-90", label: "Use today: 'The buck stops with me on this project' — old school accountability", theme: "corporate-language" },

  // --- Objection Handling ---
  { id: "cl-91", label: "Use today: 'I understand the concern — let me address that directly' — don't dodge objections", theme: "corporate-language" },
  { id: "cl-92", label: "Use today: 'You're right to be cautious — here's how we mitigate that risk...' — validate then solve", theme: "corporate-language" },
  { id: "cl-93", label: "When they say 'too expensive': 'Let me show you what it costs to NOT do this' — flip the frame", theme: "corporate-language" },
  { id: "cl-94", label: "When they say 'we'll think about it': 'Of course — what specific concerns should I address to help you decide?' — pin it down", theme: "corporate-language" },
  { id: "cl-95", label: "When they say 'we have someone': 'Great — I'd love to understand what's working and what's not' — find the gap", theme: "corporate-language" },
  { id: "cl-96", label: "Use today: 'Fair point — and here's the other side of that coin...' — elegant disagreement", theme: "corporate-language" },
  { id: "cl-97", label: "Use today: 'I hear you. Let me share a different data point...' — counter with evidence, not opinion", theme: "corporate-language" },
  { id: "cl-98", label: "When they go silent: 'I want to make sure I'm reading the room right — what's your gut telling you?'", theme: "corporate-language" },
  { id: "cl-99", label: "Use today: 'The concerns you're raising are exactly why this needs a professional approach' — turn objection into reason", theme: "corporate-language" },
  { id: "cl-100", label: "Use today: 'Let's look at this from a different angle...' — graceful pivot from a losing argument", theme: "corporate-language" },

  // --- Indian Business Context ---
  { id: "cl-101", label: "Use today: 'In our community, trust is everything — that's why I deliver first, invoice later' — Kutchi business values", theme: "corporate-language" },
  { id: "cl-102", label: "Use today: 'Your father built this with hard work — technology will protect that legacy' — generational respect", theme: "corporate-language" },
  { id: "cl-103", label: "Use today: 'I treat every client's business like my own — that's how I was raised' — family values angle", theme: "corporate-language" },
  { id: "cl-104", label: "Use today: 'The next generation expects digital — if not now, when?' — succession planning angle", theme: "corporate-language" },
  { id: "cl-105", label: "Use today: 'I understand samaj dynamics — this isn't just software, it's community building' — shows cultural awareness", theme: "corporate-language" },
  { id: "cl-106", label: "Use today: 'Your members deserve a modern experience — it reflects on the entire samaj' — pride angle", theme: "corporate-language" },
  { id: "cl-107", label: "Use today: 'I've worked with SEBI India — I understand what compliance means' — credential drop, not bragging", theme: "corporate-language" },
  { id: "cl-108", label: "Use today: 'In business, reputation compounds like interest — I never cut corners' — Warren Buffett meets Kutchi wisdom", theme: "corporate-language" },
  { id: "cl-109", label: "Use today: 'Main aapka kaam aise karunga jaise apna khud ka hai' — sincerity in Hindi hits different", theme: "corporate-language" },
  { id: "cl-110", label: "Use today: 'Paisa vasool — that's my promise. Every rupee justified.' — speaks their language", theme: "corporate-language" },

  // --- Confidence & Self-Positioning ---
  { id: "cl-111", label: "Use today: 'I've been building software for 25 years — I know what works and what doesn't' — own your experience", theme: "corporate-language" },
  { id: "cl-112", label: "Use today: 'I'm selective about the projects I take on — I want to ensure I deliver excellence' — scarcity positioning", theme: "corporate-language" },
  { id: "cl-113", label: "Use today: 'My team and I specialize in...' — always say 'my team', never 'just me'", theme: "corporate-language" },
  { id: "cl-114", label: "Use today: 'We've done this before — let me show you a case study' — proof over promises", theme: "corporate-language" },
  { id: "cl-115", label: "Use today: 'I bring 25 years of enterprise experience to every project, regardless of size' — position small work as premium", theme: "corporate-language" },
  { id: "cl-116", label: "Use today: 'Quality is non-negotiable for us — it's why our clients stay with us' — retention as proof", theme: "corporate-language" },
  { id: "cl-117", label: "Use today: 'We don't just build software — we solve business problems' — consultative positioning", theme: "corporate-language" },
  { id: "cl-118", label: "Use today: 'I'd rather say no than deliver something mediocre' — integrity positioning", theme: "corporate-language" },
  { id: "cl-119", label: "Use today: 'Our strength is understanding YOUR business, not just coding' — differentiate from freelancers", theme: "corporate-language" },
  { id: "cl-120", label: "Use today: 'I personally oversee every project — you're not handed off to a junior' — personal attention premium", theme: "corporate-language" },

  // --- Boardroom & Formal Settings ---
  { id: "cl-121", label: "Use today: 'The strategic imperative here is...' — boardroom language", theme: "corporate-language" },
  { id: "cl-122", label: "Use today: 'Let me present the business case for this...' — structures your pitch formally", theme: "corporate-language" },
  { id: "cl-123", label: "Use today: 'With due respect to the committee, I'd like to offer an alternative view...' — formal disagreement", theme: "corporate-language" },
  { id: "cl-124", label: "Use today: 'The fiduciary responsibility here demands we...' — governance language", theme: "corporate-language" },
  { id: "cl-125", label: "Use today: 'I'd like to table a proposal for the committee's consideration' — formal meeting language", theme: "corporate-language" },
  { id: "cl-126", label: "Use today: 'This aligns with the organization's long-term strategic vision' — connect to bigger picture", theme: "corporate-language" },
  { id: "cl-127", label: "Use today: 'The due diligence suggests...' — implies you've done thorough research", theme: "corporate-language" },
  { id: "cl-128", label: "Use today: 'For the record, I'd like to note that...' — formal documentation language", theme: "corporate-language" },
  { id: "cl-129", label: "Use today: 'Subject to the board's approval, I recommend...' — respectful of hierarchy", theme: "corporate-language" },
  { id: "cl-130", label: "Use today: 'This is consistent with industry best practices' — benchmarking language", theme: "corporate-language" },

  // --- Follow-Up & Relationship Maintenance ---
  { id: "cl-131", label: "Use today: 'Just circling back on our conversation last week...' — professional follow-up opener", theme: "corporate-language" },
  { id: "cl-132", label: "Use today: 'I was thinking about what you said about X — here's an idea...' — shows you listen and think", theme: "corporate-language" },
  { id: "cl-133", label: "Use today: 'I came across this article and thought of you...' — thoughtful touchpoint", theme: "corporate-language" },
  { id: "cl-134", label: "Use today: 'How did that initiative you mentioned turn out?' — remembering details builds trust", theme: "corporate-language" },
  { id: "cl-135", label: "Use today: 'I wanted to update you — we've made significant progress on...' — proactive communication", theme: "corporate-language" },
  { id: "cl-136", label: "Use today: 'I value our relationship and want to make sure we're on the same page' — relationship language", theme: "corporate-language" },
  { id: "cl-137", label: "Use today: 'Your feedback last time was incredibly helpful — here's what we did with it' — show you act on input", theme: "corporate-language" },
  { id: "cl-138", label: "Use today: 'I'd like to schedule a quarterly check-in — even if there's no project, let's stay connected' — long game", theme: "corporate-language" },
  { id: "cl-139", label: "Use today: 'Congratulations on X — well deserved' — celebrate their wins", theme: "corporate-language" },
  { id: "cl-140", label: "Use today: 'I mentioned your name to someone who could use your expertise' — give referrals to get referrals", theme: "corporate-language" },

  // --- Storytelling & Impact ---
  { id: "cl-141", label: "Use today: 'Let me give you a real example...' — stories beat statistics every time", theme: "corporate-language" },
  { id: "cl-142", label: "Use today: 'When we did this for XYZ, the result was...' — case study in conversation", theme: "corporate-language" },
  { id: "cl-143", label: "Use today: 'Imagine if your team didn't have to do X manually anymore...' — paint the after picture", theme: "corporate-language" },
  { id: "cl-144", label: "Use today: 'The turning point was when...' — storytelling structure that hooks people", theme: "corporate-language" },
  { id: "cl-145", label: "Use today: 'One of our clients had the exact same concern — here's what happened...' — objection through story", theme: "corporate-language" },
  { id: "cl-146", label: "Use today: 'Three months from now, you'll look back and wonder why you didn't start sooner' — future pacing", theme: "corporate-language" },
  { id: "cl-147", label: "Use today: 'The before-and-after is dramatic — let me show you...' — transformation narrative", theme: "corporate-language" },
  { id: "cl-148", label: "Use today: 'I learned this the hard way on a past project...' — vulnerability builds connection", theme: "corporate-language" },
  { id: "cl-149", label: "Use today: 'Here's what most people get wrong about...' — contrarian insight hooks attention", theme: "corporate-language" },
  { id: "cl-150", label: "Use today: 'The biggest risk isn't failure — it's staying where you are' — motivational close", theme: "corporate-language" },

  // --- Precision & Clarity ---
  { id: "cl-151", label: "Use today: 'To be specific...' — specificity signals expertise", theme: "corporate-language" },
  { id: "cl-152", label: "Use today: 'Let me clarify — there's an important distinction between X and Y' — shows deep understanding", theme: "corporate-language" },
  { id: "cl-153", label: "Use today: 'In concrete terms, that means...' — translate abstract to tangible", theme: "corporate-language" },
  { id: "cl-154", label: "Use today: 'The short answer is yes/no. The nuanced answer is...' — shows range", theme: "corporate-language" },
  { id: "cl-155", label: "Use today: 'Here's the one-liner version...' then deliver a crisp summary — brevity is power", theme: "corporate-language" },
  { id: "cl-156", label: "Use today: 'Let me quantify that for you...' — numbers > adjectives", theme: "corporate-language" },
  { id: "cl-157", label: "Use today: 'The key metric to watch here is...' — shows you think in KPIs", theme: "corporate-language" },
  { id: "cl-158", label: "Use today: 'There are two types of X — the kind that Y and the kind that Z' — categorization shows mastery", theme: "corporate-language" },
  { id: "cl-159", label: "Use today: 'Let me give you the executive summary...' — positions everything at C-suite level", theme: "corporate-language" },
  { id: "cl-160", label: "Use today: 'Net-net, the outcome is...' — cut through complexity to the bottom line", theme: "corporate-language" },

  // --- Emotional Intelligence in Business ---
  { id: "cl-161", label: "Use today: 'I sense there's something else on your mind — what is it?' — read between the lines", theme: "corporate-language" },
  { id: "cl-162", label: "Use today: 'That must be frustrating — I've been there' — empathy before solutions", theme: "corporate-language" },
  { id: "cl-163", label: "Use today: 'I appreciate you being candid with me' — reward honesty to get more of it", theme: "corporate-language" },
  { id: "cl-164", label: "Use today: 'I don't want to oversell this — let me set realistic expectations' — under-promise, over-deliver", theme: "corporate-language" },
  { id: "cl-165", label: "Use today: 'This is clearly important to you — tell me more about why' — explore motivation", theme: "corporate-language" },
  { id: "cl-166", label: "Use today: 'I respect that we see this differently — help me understand your perspective' — mature disagreement", theme: "corporate-language" },
  { id: "cl-167", label: "Use today: 'You've clearly thought about this deeply' — acknowledge their intelligence", theme: "corporate-language" },
  { id: "cl-168", label: "Use today: 'I'm not going to pretend I have all the answers — but I know how to find them' — confident humility", theme: "corporate-language" },
  { id: "cl-169", label: "Use today: 'What would make you feel confident about moving forward?' — address emotions, not just logic", theme: "corporate-language" },
  { id: "cl-170", label: "Use today: 'I want this to work for both of us — not just the project, but the relationship' — long-term thinking", theme: "corporate-language" },

  // --- Industry Jargon Done Right ---
  { id: "cl-171", label: "Use today: 'We need to move from reactive to proactive on this' — transformation language", theme: "corporate-language" },
  { id: "cl-172", label: "Use today: 'This creates a flywheel effect — each success feeds the next' — Amazon-style thinking", theme: "corporate-language" },
  { id: "cl-173", label: "Use today: 'Let's identify the low-hanging fruit first, then tackle the harder problems' — phased approach", theme: "corporate-language" },
  { id: "cl-174", label: "Use today: 'We need to create a single source of truth for this data' — data management language", theme: "corporate-language" },
  { id: "cl-175", label: "Use today: 'This gives you real-time visibility into operations' — sell transparency", theme: "corporate-language" },
  { id: "cl-176", label: "Use today: 'Let's future-proof this decision' — think ahead language", theme: "corporate-language" },
  { id: "cl-177", label: "Use today: 'The current approach doesn't scale — here's what will' — growth-oriented critique", theme: "corporate-language" },
  { id: "cl-178", label: "Use today: 'We're looking at a paradigm shift in how you operate' — big picture language", theme: "corporate-language" },
  { id: "cl-179", label: "Use today: 'This is about operational excellence, not just efficiency' — higher standard language", theme: "corporate-language" },
  { id: "cl-180", label: "Use today: 'Let's establish the baseline first, then measure improvement' — metrics-driven approach", theme: "corporate-language" },

  // --- Closing & Call to Action ---
  { id: "cl-181", label: "Use today: 'What's the logical next step from here?' — let them feel they're choosing", theme: "corporate-language" },
  { id: "cl-182", label: "Use today: 'I'll send you a one-page summary by tomorrow' — concrete deliverable shows seriousness", theme: "corporate-language" },
  { id: "cl-183", label: "Use today: 'Shall I put together a proposal, or do you want to discuss scope first?' — either answer moves forward", theme: "corporate-language" },
  { id: "cl-184", label: "Use today: 'I don't want to rush you — but I also don't want you to lose momentum' — gentle urgency", theme: "corporate-language" },
  { id: "cl-185", label: "Use today: 'Here's what I suggest as a pilot — low risk, high learning' — reduce commitment anxiety", theme: "corporate-language" },
  { id: "cl-186", label: "Use today: 'Why don't we start small and scale based on results?' — land-and-expand strategy", theme: "corporate-language" },
  { id: "cl-187", label: "Use today: 'I'm confident this will deliver value — I'm happy to put milestones around it' — accountability offer", theme: "corporate-language" },
  { id: "cl-188", label: "Use today: 'The best time to start was yesterday. The second best time is today.' — borrowed wisdom, powerful close", theme: "corporate-language" },
  { id: "cl-189", label: "Use today: 'Let's shake on the intent and I'll come back with the details' — move from discussion to action", theme: "corporate-language" },
  { id: "cl-190", label: "Use today: 'I'll block time this week to give this the attention it deserves' — shows priority", theme: "corporate-language" },

  // --- Power Phrases for Daily Use ---
  { id: "cl-191", label: "Use today: 'Absolutely' instead of 'yes' — more decisive, more executive", theme: "corporate-language" },
  { id: "cl-192", label: "Use today: 'I appreciate that' instead of 'thanks' — more professional weight", theme: "corporate-language" },
  { id: "cl-193", label: "Use today: 'My perspective is...' instead of 'I think...' — more authoritative", theme: "corporate-language" },
  { id: "cl-194", label: "Use today: 'I'm committed to...' instead of 'I'll try to...' — certainty over hesitation", theme: "corporate-language" },
  { id: "cl-195", label: "Use today: 'Let's explore that' instead of 'maybe' — open without being wishy-washy", theme: "corporate-language" },
  { id: "cl-196", label: "Use today: 'I'd recommend...' instead of 'you could...' — take a position", theme: "corporate-language" },
  { id: "cl-197", label: "Use today: 'In my experience...' instead of 'I think...' — grounds opinion in credibility", theme: "corporate-language" },
  { id: "cl-198", label: "Use today: 'Consider this...' instead of 'what about...' — more commanding phrasing", theme: "corporate-language" },
  { id: "cl-199", label: "Use today: 'The evidence suggests...' instead of 'I feel like...' — data over feelings", theme: "corporate-language" },
  { id: "cl-200", label: "Use today: 'I'll make it happen' instead of 'I'll try' — the most powerful phrase in business", theme: "corporate-language" },
];
