import { PowerCheckItem } from "./power-checks";

// 200 strategic thinking tips — frameworks, mental models, and questions that make you sound sharp
export const strategicThinkingTips: PowerCheckItem[] = [
  // --- First Principles Thinking ---
  { id: "st-1", label: "Ask yourself: 'What would this look like if it were easy?' — Tim Ferriss's simplification question", theme: "strategic-thinking" },
  { id: "st-2", label: "Before any decision today: 'What are we optimizing for?' — clarity before action", theme: "strategic-thinking" },
  { id: "st-3", label: "Apply the 5 Whys today — keep asking 'why?' until you hit the root cause of any problem", theme: "strategic-thinking" },
  { id: "st-4", label: "Think in first principles: 'What do we know to be absolutely true here?' — strip away assumptions", theme: "strategic-thinking" },
  { id: "st-5", label: "Invert the problem: 'How would I guarantee failure?' — then avoid those things", theme: "strategic-thinking" },
  { id: "st-6", label: "Ask: 'What would have to be true for this to work?' — reverse-engineer success", theme: "strategic-thinking" },
  { id: "st-7", label: "Apply Occam's Razor: the simplest explanation is usually correct. Don't overcomplicate today.", theme: "strategic-thinking" },
  { id: "st-8", label: "Think about: 'What's the constraint here? What's the bottleneck?' — Theory of Constraints", theme: "strategic-thinking" },
  { id: "st-9", label: "Ask: 'If I could only do one thing today to move the needle, what would it be?' — ruthless prioritization", theme: "strategic-thinking" },
  { id: "st-10", label: "Consider: 'Am I confusing activity with progress?' — busy ≠ productive", theme: "strategic-thinking" },

  // --- Competitive Strategy ---
  { id: "st-11", label: "Think Porter's Five Forces: who are the competitors, substitutes, new entrants in your space?", theme: "strategic-thinking" },
  { id: "st-12", label: "Ask: 'What's my competitive moat? What can I do that others can't easily copy?' — defensibility thinking", theme: "strategic-thinking" },
  { id: "st-13", label: "Consider: 'Am I competing on price or on value?' — always choose value", theme: "strategic-thinking" },
  { id: "st-14", label: "Think Blue Ocean: 'Where is there demand with no competition?' — don't fight in red oceans", theme: "strategic-thinking" },
  { id: "st-15", label: "Ask: 'What's my unfair advantage?' — 25 years experience + community trust + SEBI credential", theme: "strategic-thinking" },
  { id: "st-16", label: "Consider differentiation: 'What do I offer that Upwork freelancers never will?' — proximity, trust, Hindi/Gujarati, samaj understanding", theme: "strategic-thinking" },
  { id: "st-17", label: "Think about switching costs: 'Once a client is with me, how hard is it to leave?' — build stickiness", theme: "strategic-thinking" },
  { id: "st-18", label: "Apply the Innovator's Dilemma: your clients' existing IT vendors are too big to care about them. You're not.", theme: "strategic-thinking" },
  { id: "st-19", label: "Consider: 'What would a VC-backed startup do in my market?' — then do the version that works for a bootstrapped company", theme: "strategic-thinking" },
  { id: "st-20", label: "Think about positioning: 'In one sentence, why should they choose me over anyone else?'", theme: "strategic-thinking" },

  // --- Decision-Making Frameworks ---
  { id: "st-21", label: "Apply the Eisenhower Matrix today: what's urgent AND important? That's your only priority.", theme: "strategic-thinking" },
  { id: "st-22", label: "Use the 10/10/10 rule: How will you feel about this decision in 10 minutes? 10 months? 10 years?", theme: "strategic-thinking" },
  { id: "st-23", label: "Consider reversibility: 'Is this a one-way door or a two-way door?' — Amazon's decision framework", theme: "strategic-thinking" },
  { id: "st-24", label: "Apply the regret minimization framework: 'At 80, will I regret not trying this?' — Bezos's compass", theme: "strategic-thinking" },
  { id: "st-25", label: "Think about expected value: probability of success × size of reward. Even low-probability, high-reward bets are worth taking.", theme: "strategic-thinking" },
  { id: "st-26", label: "Use the premortem technique: 'It's 6 months from now and this failed. Why?' — then prevent those reasons", theme: "strategic-thinking" },
  { id: "st-27", label: "Apply the RICE framework to your tasks: Reach × Impact × Confidence ÷ Effort = Priority score", theme: "strategic-thinking" },
  { id: "st-28", label: "Consider second-order effects: 'If I do X, then Y happens, which causes Z' — think two moves ahead", theme: "strategic-thinking" },
  { id: "st-29", label: "Use the 'hell yes or no' filter: if it's not an obvious yes, it's a no. Protect your time.", theme: "strategic-thinking" },
  { id: "st-30", label: "Apply the ICE method: Impact, Confidence, Ease — score each opportunity and pick the highest", theme: "strategic-thinking" },

  // --- Growth Strategy ---
  { id: "st-31", label: "Think Ansoff Matrix: are you selling existing products to existing clients, or exploring new markets?", theme: "strategic-thinking" },
  { id: "st-32", label: "Consider the land-and-expand strategy: get in small, prove value, then grow within the account", theme: "strategic-thinking" },
  { id: "st-33", label: "Think about your flywheel: good work → referral → more work → more referrals. What accelerates this?", theme: "strategic-thinking" },
  { id: "st-34", label: "Apply the 1000 true fans theory: you only need ~20 high-paying clients to make Rs 1 crore/year", theme: "strategic-thinking" },
  { id: "st-35", label: "Consider productizing your service: 'Can I turn this custom work into a repeatable product?'", theme: "strategic-thinking" },
  { id: "st-36", label: "Think about recurring revenue: one-time projects vs. monthly retainers — which builds wealth?", theme: "strategic-thinking" },
  { id: "st-37", label: "Apply the Pareto Principle to clients: which 20% of clients generate 80% of revenue? Double down there.", theme: "strategic-thinking" },
  { id: "st-38", label: "Consider vertical integration: 'Can I own more of the value chain?' — design + build + host + maintain", theme: "strategic-thinking" },
  { id: "st-39", label: "Think about network effects: 'Does my product/service become more valuable as more people use it?'", theme: "strategic-thinking" },
  { id: "st-40", label: "Apply the barbell strategy: safe income from maintenance contracts + high-upside bets on new projects", theme: "strategic-thinking" },

  // --- Client & Market Understanding ---
  { id: "st-41", label: "Ask: 'What job is the client hiring me to do?' — Jobs-To-Be-Done framework by Clayton Christensen", theme: "strategic-thinking" },
  { id: "st-42", label: "Think about the whole product: it's not just code — it's reliability, support, trust, and peace of mind", theme: "strategic-thinking" },
  { id: "st-43", label: "Consider the buyer's journey: Unaware → Aware → Interested → Decided. Where is each prospect?", theme: "strategic-thinking" },
  { id: "st-44", label: "Apply the Value Proposition Canvas: what pains do your clients have? What gains do they want?", theme: "strategic-thinking" },
  { id: "st-45", label: "Think about ICP (Ideal Client Profile): Kutchi businessman, 50-70, owns traditional business, needs modernization", theme: "strategic-thinking" },
  { id: "st-46", label: "Consider: 'What does my client's client need?' — solve one level deeper and you become indispensable", theme: "strategic-thinking" },
  { id: "st-47", label: "Apply the Kano Model: what features delight vs. what's just expected? Exceed on delight features.", theme: "strategic-thinking" },
  { id: "st-48", label: "Think about total cost of ownership: your client compares your price to their pain, not to your cost", theme: "strategic-thinking" },
  { id: "st-49", label: "Consider the trust equation: Trust = (Credibility + Reliability + Intimacy) ÷ Self-Orientation", theme: "corporate-language" },
  { id: "st-50", label: "Ask: 'What does my client brag about to their friends?' — then give them something to brag about", theme: "strategic-thinking" },

  // --- Resource & Time Management ---
  { id: "st-51", label: "Apply the 2-minute rule: if something takes less than 2 minutes, do it NOW. Don't add it to a list.", theme: "strategic-thinking" },
  { id: "st-52", label: "Think about leverage: 'Where does 1 hour of my effort create 10x returns?' — code, content, relationships", theme: "strategic-thinking" },
  { id: "st-53", label: "Consider your hourly rate: if you charge Rs 2000/hr, anything below that should be delegated or automated", theme: "strategic-thinking" },
  { id: "st-54", label: "Apply time-blocking: your calendar should reflect your priorities. If it's not blocked, it won't happen.", theme: "strategic-thinking" },
  { id: "st-55", label: "Think about energy management, not just time management: do creative work when your energy peaks", theme: "strategic-thinking" },
  { id: "st-56", label: "Consider batching: group similar tasks (calls, emails, coding) to minimize context-switching costs", theme: "strategic-thinking" },
  { id: "st-57", label: "Apply Parkinson's Law: work expands to fill the time allotted. Set tighter deadlines for yourself.", theme: "strategic-thinking" },
  { id: "st-58", label: "Think about your 'not-to-do' list: what should you STOP doing? That's often more powerful than adding.", theme: "strategic-thinking" },
  { id: "st-59", label: "Consider the maker's schedule vs. manager's schedule: protect long unbroken blocks for coding", theme: "strategic-thinking" },
  { id: "st-60", label: "Apply the two-list strategy: write everything you want to do. Circle the top 5. Avoid the rest at all costs.", theme: "strategic-thinking" },

  // --- Systems Thinking ---
  { id: "st-61", label: "Think in systems, not events: 'What process creates this outcome?' — then fix the process, not the outcome", theme: "strategic-thinking" },
  { id: "st-62", label: "Consider feedback loops: positive (growth compounds) and negative (problems compound). Which are running?", theme: "strategic-thinking" },
  { id: "st-63", label: "Apply the map is not the territory: your mental model of the market may be outdated. Test it.", theme: "strategic-thinking" },
  { id: "st-64", label: "Think about leading vs. lagging indicators: pipeline meetings (leading) predict revenue (lagging)", theme: "strategic-thinking" },
  { id: "st-65", label: "Consider the Lindy Effect: things that have lasted long tend to last longer. Your 25 years of experience compounds.", theme: "strategic-thinking" },
  { id: "st-66", label: "Apply the Stockdale Paradox: confront the brutal facts AND maintain unwavering faith you'll prevail", theme: "strategic-thinking" },
  { id: "st-67", label: "Think about compounding: relationships, skills, reputation — what compounds? Invest there.", theme: "strategic-thinking" },
  { id: "st-68", label: "Consider survivorship bias: you see successful people, not the ones who failed doing the same thing. What actually works?", theme: "strategic-thinking" },
  { id: "st-69", label: "Apply Goodhart's Law: when a measure becomes a target, it ceases to be a good measure. Track the right things.", theme: "strategic-thinking" },
  { id: "st-70", label: "Think about emergence: small consistent actions create surprisingly large outcomes. Trust the daily process.", theme: "strategic-thinking" },

  // --- Innovation & Creativity ---
  { id: "st-71", label: "Apply the 'What if' technique: 'What if this cost zero?' 'What if this took 1 day instead of 1 month?'", theme: "strategic-thinking" },
  { id: "st-72", label: "Think about adjacent possibilities: what can you build with what you already have? No new resources needed.", theme: "strategic-thinking" },
  { id: "st-73", label: "Consider recombination: take an idea from one industry and apply it to another. JSG ticketing → Gymkhana events.", theme: "strategic-thinking" },
  { id: "st-74", label: "Apply the 'steal like an artist' principle: what's working for other software companies serving communities?", theme: "strategic-thinking" },
  { id: "st-75", label: "Think about minimum viable experiments: 'What's the cheapest way to test this idea before building it?'", theme: "strategic-thinking" },
  { id: "st-76", label: "Consider the SCAMPER technique: Substitute, Combine, Adapt, Modify, Put to other use, Eliminate, Reverse", theme: "strategic-thinking" },
  { id: "st-77", label: "Apply constraint-driven innovation: limited budget forces creativity. What can you build with just AI + your skills?", theme: "strategic-thinking" },
  { id: "st-78", label: "Think about the 'last mile' problem: your solution doesn't need to be perfect, just better than what they have now", theme: "strategic-thinking" },
  { id: "st-79", label: "Consider cross-pollination: what lessons from SEBI surveillance apply to business analytics?", theme: "strategic-thinking" },
  { id: "st-80", label: "Apply beginner's mind to an old problem: 'If I were starting from scratch, would I build it this way?'", theme: "strategic-thinking" },

  // --- Risk & Uncertainty ---
  { id: "st-81", label: "Think about asymmetric risk: find bets where you can lose a little but win a lot. Cold outreach is one.", theme: "strategic-thinking" },
  { id: "st-82", label: "Apply the Kelly Criterion mindset: bet proportional to your edge. Where do you have the biggest advantage?", theme: "strategic-thinking" },
  { id: "st-83", label: "Consider: 'What's the worst case, the best case, and the most likely case?' — scenario planning", theme: "strategic-thinking" },
  { id: "st-84", label: "Think about tail risks: low-probability, high-impact events. What happens if your biggest client leaves?", theme: "strategic-thinking" },
  { id: "st-85", label: "Apply the 'via negativa' approach: instead of adding things, what should you remove to reduce risk?", theme: "strategic-thinking" },
  { id: "st-86", label: "Consider optionality: make decisions that keep options open rather than closing doors prematurely", theme: "strategic-thinking" },
  { id: "st-87", label: "Think about the base rate: 'What percentage of similar attempts succeed?' — before assuming yours is special", theme: "strategic-thinking" },
  { id: "st-88", label: "Apply the margin of safety concept: build buffers into timelines, budgets, and promises", theme: "strategic-thinking" },
  { id: "st-89", label: "Consider sunk cost fallacy: 'Should I continue because of what I've already invested, or because of future returns?'", theme: "strategic-thinking" },
  { id: "st-90", label: "Think about antifragility: what gets STRONGER from stress? Your skills, your reputation, your resilience.", theme: "strategic-thinking" },

  // --- Pricing & Value Strategy ---
  { id: "st-91", label: "Think value-based pricing: price based on the value you create, not the hours you spend", theme: "strategic-thinking" },
  { id: "st-92", label: "Consider anchoring: always present the premium option first — it makes the standard option feel reasonable", theme: "strategic-thinking" },
  { id: "st-93", label: "Apply the 3-tier pricing strategy: Basic, Professional, Enterprise — let clients self-select", theme: "strategic-thinking" },
  { id: "st-94", label: "Think about price elasticity: which clients are price-sensitive and which value quality above all?", theme: "strategic-thinking" },
  { id: "st-95", label: "Consider bundling: software + training + support = higher total value than selling each separately", theme: "strategic-thinking" },
  { id: "st-96", label: "Apply the 'pain of paying' research: monthly payments feel smaller than annual. But annual secures commitment.", theme: "strategic-thinking" },
  { id: "st-97", label: "Think about lifetime value: a Rs 50K project that leads to Rs 5L over 3 years — price the first one for relationship", theme: "strategic-thinking" },
  { id: "st-98", label: "Consider the decoy effect: offer three options where the middle one is obviously the best value", theme: "strategic-thinking" },
  { id: "st-99", label: "Apply premium pricing psychology: higher price = higher perceived quality. Don't race to the bottom.", theme: "strategic-thinking" },
  { id: "st-100", label: "Think about the 'free sample' strategy: show them a dashboard mockup before they commit. Taste sells.", theme: "strategic-thinking" },

  // --- Negotiation Strategy ---
  { id: "st-101", label: "Apply BATNA thinking: 'What's my Best Alternative To a Negotiated Agreement?' — know your walkaway point", theme: "strategic-thinking" },
  { id: "st-102", label: "Think about ZOPA: Zone Of Possible Agreement — where does your acceptable range overlap with theirs?", theme: "strategic-thinking" },
  { id: "st-103", label: "Consider expanding the pie: 'What else can I offer that costs me little but has high value to them?'", theme: "strategic-thinking" },
  { id: "st-104", label: "Apply the nibble technique: after agreement, add a small request — 'Could you also provide the logo files?'", theme: "strategic-thinking" },
  { id: "st-105", label: "Think about the power of silence in negotiation: state your price and stop talking. Let them respond first.", theme: "strategic-thinking" },
  { id: "st-106", label: "Consider reciprocity: give something first (free audit, quick fix) — people feel obligated to return the favor", theme: "strategic-thinking" },
  { id: "st-107", label: "Apply the flinch: when they name a low price, react visibly. Even experienced negotiators adjust after a flinch.", theme: "strategic-thinking" },
  { id: "st-108", label: "Think about trades, not concessions: 'I can lower the price if we extend the timeline' — never give without getting", theme: "strategic-thinking" },
  { id: "st-109", label: "Consider the 'higher authority' technique: 'I need to check with my team on that pricing' — even if you decide alone", theme: "strategic-thinking" },
  { id: "st-110", label: "Apply deadline pressure ethically: 'This pricing is available until month-end' — scarcity drives decisions", theme: "strategic-thinking" },

  // --- Execution & Operations ---
  { id: "st-111", label: "Think about your Definition of Done: when is a project truly complete? Be specific. Prevent scope creep.", theme: "strategic-thinking" },
  { id: "st-112", label: "Apply the 80/20 rule to features: which 20% of features will deliver 80% of the value? Build those first.", theme: "strategic-thinking" },
  { id: "st-113", label: "Consider the critical path: what tasks must be done sequentially? What can run in parallel?", theme: "strategic-thinking" },
  { id: "st-114", label: "Think about your bus factor: if you're sick for a week, does the project stop? That's a risk.", theme: "strategic-thinking" },
  { id: "st-115", label: "Apply the concept of 'done > perfect': a shipped 80% solution beats a perfect solution that never launches", theme: "strategic-thinking" },
  { id: "st-116", label: "Consider the MVP mindset: what's the absolute minimum you can deliver that proves the concept?", theme: "strategic-thinking" },
  { id: "st-117", label: "Think about process automation: what do you do manually every day that could be a script or template?", theme: "strategic-thinking" },
  { id: "st-118", label: "Apply the One Thing principle: 'What's the one thing I can do such that by doing it, everything else becomes easier?'", theme: "strategic-thinking" },
  { id: "st-119", label: "Consider the Agile mindset: deliver in small increments, get feedback, adjust. Don't build for 3 months in isolation.", theme: "strategic-thinking" },
  { id: "st-120", label: "Think about your standard operating procedures: do you have templates for proposals, onboarding, project kickoff?", theme: "strategic-thinking" },

  // --- Mental Models for Business ---
  { id: "st-121", label: "Apply the Circle of Competence: stay where you know the most. Custom software for Indian communities = your zone.", theme: "strategic-thinking" },
  { id: "st-122", label: "Think about incentive structures: 'What behavior does this pricing/contract incentivize?' — for both parties", theme: "strategic-thinking" },
  { id: "st-123", label: "Consider the availability heuristic: people overweight recent experiences. One bad vendor = opportunity for you.", theme: "strategic-thinking" },
  { id: "st-124", label: "Apply the principle of least effort: people choose the easiest path. Make choosing you the easiest option.", theme: "strategic-thinking" },
  { id: "st-125", label: "Think about the Dunning-Kruger effect: your clients don't know what they don't know about software. Educate gently.", theme: "strategic-thinking" },
  { id: "st-126", label: "Consider the anchoring effect: the first number mentioned sets the frame. Always let them say their budget first.", theme: "strategic-thinking" },
  { id: "st-127", label: "Apply mental accounting: people treat money differently based on categories. 'IT budget' vs. 'marketing budget' — frame accordingly.", theme: "strategic-thinking" },
  { id: "st-128", label: "Think about status quo bias: people prefer the current state. Make change feel safe and gradual.", theme: "strategic-thinking" },
  { id: "st-129", label: "Consider the endowment effect: once someone owns something, they value it more. Give a trial/demo they can experience.", theme: "strategic-thinking" },
  { id: "st-130", label: "Apply loss aversion: people fear losing more than they desire gaining. Frame your pitch around what they'll lose without you.", theme: "strategic-thinking" },

  // --- Leadership Thinking ---
  { id: "st-131", label: "Think about servant leadership: 'How can I help my client succeed?' — their success IS your success", theme: "strategic-thinking" },
  { id: "st-132", label: "Apply the coach approach: ask questions instead of giving answers. Let clients discover the need themselves.", theme: "strategic-thinking" },
  { id: "st-133", label: "Consider the multiplier effect: one good system you build frees up dozens of hours for their team", theme: "strategic-thinking" },
  { id: "st-134", label: "Think about legacy: 'What will they say about my work 5 years from now?' — build for the long term", theme: "strategic-thinking" },
  { id: "st-135", label: "Apply the 'teach to learn' principle: explain your strategy to someone today. Teaching clarifies your own thinking.", theme: "strategic-thinking" },
  { id: "st-136", label: "Consider: 'Am I being a technician, a manager, or an entrepreneur today?' — aim for entrepreneur (E-Myth)", theme: "strategic-thinking" },
  { id: "st-137", label: "Think about your personal board of advisors: who are the 3-5 people whose opinion you trust most?", theme: "strategic-thinking" },
  { id: "st-138", label: "Apply the 'zoom in, zoom out' technique: details matter, but regularly zoom out to see the big picture", theme: "strategic-thinking" },
  { id: "st-139", label: "Consider your decision journal: write down important decisions and why. Review quarterly to improve judgment.", theme: "strategic-thinking" },
  { id: "st-140", label: "Think about the 'CEO test': would a CEO of a 100-person company spend time on what you're doing right now?", theme: "strategic-thinking" },

  // --- Market & Industry Analysis ---
  { id: "st-141", label: "Apply the PESTEL framework: what Political, Economic, Social, Tech, Environmental, Legal factors affect your market?", theme: "strategic-thinking" },
  { id: "st-142", label: "Think about India's digital transformation wave: UPI changed payments. What's the next wave? Member management for communities.", theme: "strategic-thinking" },
  { id: "st-143", label: "Consider demographic shifts: the next generation of Kutchi businessmen are digital natives. Position for them NOW.", theme: "strategic-thinking" },
  { id: "st-144", label: "Apply trend analysis: what's growing? AI, automation, mobile-first, WhatsApp Business. Ride these waves.", theme: "strategic-thinking" },
  { id: "st-145", label: "Think about the technology adoption curve: your clients are late majority. Make technology feel safe and familiar.", theme: "strategic-thinking" },
  { id: "st-146", label: "Consider the platform vs. product debate: should you build a platform that serves many communities, or bespoke products?", theme: "strategic-thinking" },
  { id: "st-147", label: "Apply the 'crossing the chasm' concept: you need a beachhead market. Kutchi samaj software IS your beachhead.", theme: "strategic-thinking" },
  { id: "st-148", label: "Think about regulatory trends: GST, digital compliance, data privacy — each creates demand for software", theme: "strategic-thinking" },
  { id: "st-149", label: "Consider the remote work shift: you can serve clients anywhere in India. Geography is no longer a constraint.", theme: "strategic-thinking" },
  { id: "st-150", label: "Apply the S-curve model: every technology has growth → maturity → decline. Where is your current offering?", theme: "strategic-thinking" },

  // --- Personal Strategy ---
  { id: "st-151", label: "Think about your personal brand: what do people say about you when you're not in the room?", theme: "strategic-thinking" },
  { id: "st-152", label: "Apply the T-shaped skills model: deep in one area (software), broad in many (business, community, AI)", theme: "strategic-thinking" },
  { id: "st-153", label: "Consider your Ikigai: where does what you love, what you're good at, what pays, and what the world needs intersect?", theme: "strategic-thinking" },
  { id: "st-154", label: "Think about your 10-year plan: where do you want to be at 61? Work backwards to today.", theme: "strategic-thinking" },
  { id: "st-155", label: "Apply the 'assets vs. liabilities' framework to your time: which activities build long-term assets?", theme: "strategic-thinking" },
  { id: "st-156", label: "Consider your positioning statement: 'I help [who] achieve [what] through [how]' — can you say it in 10 seconds?", theme: "strategic-thinking" },
  { id: "st-157", label: "Think about your skill stack: software + community knowledge + AI + personality = unique combination", theme: "strategic-thinking" },
  { id: "st-158", label: "Apply the compound interest metaphor to skills: every day you practice selling, you get 0.1% better. That compounds.", theme: "strategic-thinking" },
  { id: "st-159", label: "Consider your 'Hell Yeah' list: what 3 things, if you achieved them this year, would make everything worth it?", theme: "strategic-thinking" },
  { id: "st-160", label: "Think about your professional narrative: victim or protagonist? Choose protagonist — every setback is a plot twist.", theme: "strategic-thinking" },

  // --- Financial Thinking ---
  { id: "st-161", label: "Apply the Rule of 72: to double your money at X% return, divide 72 by X. At 15% growth, double in ~5 years.", theme: "strategic-thinking" },
  { id: "st-162", label: "Think about cash flow timing: revenue recognized ≠ cash in hand. Always track when money actually arrives.", theme: "strategic-thinking" },
  { id: "st-163", label: "Consider your break-even point: how many projects per month do you need to cover all expenses?", theme: "strategic-thinking" },
  { id: "st-164", label: "Apply the 50/30/20 rule to business revenue: 50% operations, 30% growth investment, 20% personal income", theme: "strategic-thinking" },
  { id: "st-165", label: "Think about revenue diversification: if one client is >50% of income, that's a risk. Spread the base.", theme: "strategic-thinking" },
  { id: "st-166", label: "Consider the cost of delay: every month a prospect waits, they're losing money on inefficiency. Quantify it for them.", theme: "strategic-thinking" },
  { id: "st-167", label: "Apply the concept of economic moats to your pricing: brand, switching costs, network effects, cost advantages", theme: "strategic-thinking" },
  { id: "st-168", label: "Think about unit economics: what does it cost you to acquire and serve one client? Is the math positive?", theme: "strategic-thinking" },
  { id: "st-169", label: "Consider opportunity cost: every hour on a low-value task is an hour NOT spent on a high-value opportunity", theme: "strategic-thinking" },
  { id: "st-170", label: "Apply the 'invest in yourself' principle: Rs 10K on a course that gets you one Rs 2L client = 20x return", theme: "strategic-thinking" },

  // --- Relationship Strategy ---
  { id: "st-171", label: "Think about relationship capital: it depletes when you only withdraw (ask). Deposit first (give value, connect, help).", theme: "strategic-thinking" },
  { id: "st-172", label: "Apply the Dunbar number: you can maintain ~150 meaningful relationships. Who are your most strategic 150?", theme: "strategic-thinking" },
  { id: "st-173", label: "Consider the warm introduction principle: a referral from a trusted person is 10x more effective than cold outreach", theme: "strategic-thinking" },
  { id: "st-174", label: "Think about your network map: who knows who? Can you connect two people and create value for both?", theme: "strategic-thinking" },
  { id: "st-175", label: "Apply the 5-5-5 networking rule: 5 new contacts per week, 5 follow-ups, 5 value-adds (articles, intros, ideas)", theme: "strategic-thinking" },
  { id: "st-176", label: "Consider the power of weak ties: people you know casually often provide the best opportunities (Granovetter)", theme: "strategic-thinking" },
  { id: "st-177", label: "Think about trust velocity: how quickly can you build trust? Deliver something small and excellent, fast.", theme: "strategic-thinking" },
  { id: "st-178", label: "Apply the 'give first' principle: share knowledge, make introductions, offer help — without expecting immediate return", theme: "strategic-thinking" },
  { id: "st-179", label: "Consider your reputation ripple: every interaction sends ripples. One great delivery echoes through the community for months.", theme: "strategic-thinking" },
  { id: "st-180", label: "Think about the power of proximity: being at Gymkhana every day is a strategic asset most people undervalue", theme: "strategic-thinking" },

  // --- Daily Strategic Questions ---
  { id: "st-181", label: "Morning question: 'What's my #1 revenue-generating activity today?' — do it before anything else", theme: "strategic-thinking" },
  { id: "st-182", label: "Before any meeting: 'What's my desired outcome here?' — never walk in without a goal", theme: "strategic-thinking" },
  { id: "st-183", label: "After every conversation: 'Is there a follow-up I should send within 24 hours?' — speed of follow-up = deal velocity", theme: "strategic-thinking" },
  { id: "st-184", label: "Evening question: 'Did I move the needle today? What would I do differently tomorrow?'", theme: "strategic-thinking" },
  { id: "st-185", label: "Weekly question: 'Which relationships did I invest in this week? Which did I neglect?'", theme: "strategic-thinking" },
  { id: "st-186", label: "Monthly question: 'Am I getting closer to Rs 1 crore/year? What needs to change if not?'", theme: "strategic-thinking" },
  { id: "st-187", label: "Before saying yes: 'Does this align with my top 3 priorities right now? If not, it's a no.'", theme: "strategic-thinking" },
  { id: "st-188", label: "When stuck: 'Who has already solved this problem? Can I learn from them instead of reinventing?'", theme: "strategic-thinking" },
  { id: "st-189", label: "When overwhelmed: 'What would this look like if it were simple?' — strip complexity until the core remains", theme: "strategic-thinking" },
  { id: "st-190", label: "When anxious about money: 'What's the smallest step I can take RIGHT NOW to generate income?'", theme: "strategic-thinking" },

  // --- Wisdom & Philosophy ---
  { id: "st-191", label: "Remember: 'The best time to plant a tree was 20 years ago. The second best time is now.' — start today.", theme: "strategic-thinking" },
  { id: "st-192", label: "Apply stoic thinking: 'What's in my control?' — focus only there. Release everything else.", theme: "strategic-thinking" },
  { id: "st-193", label: "Consider: 'What would the best version of me do today?' — then do that. Don't negotiate with your lesser self.", theme: "strategic-thinking" },
  { id: "st-194", label: "Think about the 'cathedral' mindset: each project is a brick. You're building something much bigger than any single project.", theme: "strategic-thinking" },
  { id: "st-195", label: "Apply the 'play long-term games with long-term people' principle — Naval Ravikant's wisdom for wealth building", theme: "strategic-thinking" },
  { id: "st-196", label: "Consider: 'Specific knowledge + accountability + leverage = wealth' — Naval's formula. Which are you weak on?", theme: "strategic-thinking" },
  { id: "st-197", label: "Think about Nassim Taleb's 'skin in the game': you deliver for clients because your reputation is on the line. That's your edge.", theme: "strategic-thinking" },
  { id: "st-198", label: "Apply the 'hell is other people's opinions' antidote: care about the opinion of 5 people max. Ignore the rest.", theme: "strategic-thinking" },
  { id: "st-199", label: "Consider the 'memento mori' principle: life is short. Are you spending it on things that matter?", theme: "strategic-thinking" },
  { id: "st-200", label: "Remember: strategy without execution is fantasy. Execution without strategy is chaos. You need both, every single day.", theme: "strategic-thinking" },
];
