import { PowerCheckItem } from "./power-checks";

// 200 "What they say → What they actually mean" decoder tips
// Each tip teaches you to RECOGNIZE and USE business language with plain English meaning
export const decoderTips: PowerCheckItem[] = [
  // --- Financial Language Decoded ---
  { id: "dec-1", label: "They say: 'We have 6 months of runway.' → Means: We can survive 6 months at our current spending rate before we run out of money.", theme: "decoder" },
  { id: "dec-2", label: "They say: 'What's the burn rate?' → Means: How much money are you spending per month? They want to know how fast cash is going out.", theme: "decoder" },
  { id: "dec-3", label: "They say: 'The unit economics don't work.' → Means: We lose money on each customer/transaction. The per-unit math is negative.", theme: "decoder" },
  { id: "dec-4", label: "They say: 'We need to look at the EBITDA.' → Means: What's the actual profit before accounting tricks? Are we really making money?", theme: "decoder" },
  { id: "dec-5", label: "They say: 'What's the ROI on this?' → Means: If I spend this money, how much will I get back? Show me the return.", theme: "decoder" },
  { id: "dec-6", label: "They say: 'The CAC is too high.' → Means: It's costing us too much to get each new customer. We need cheaper ways to attract them.", theme: "decoder" },
  { id: "dec-7", label: "They say: 'Focus on LTV.' → Means: Don't just get customers — keep them spending over time. The lifetime value matters more than the first sale.", theme: "decoder" },
  { id: "dec-8", label: "They say: 'We need positive cash flow.' → Means: More money must come IN than goes OUT each month. Profit on paper doesn't matter if we can't pay bills.", theme: "decoder" },
  { id: "dec-9", label: "They say: 'What's the gross margin?' → Means: After direct costs, how much profit is left? If you sell for Rs 100 and it costs Rs 40 to make, margin is 60%.", theme: "decoder" },
  { id: "dec-10", label: "They say: 'We're raising a bridge round.' → Means: We need emergency short-term funding to survive until the next big funding round.", theme: "decoder" },

  { id: "dec-11", label: "They say: 'Let's look at the P&L.' → Means: Profit & Loss statement — total income minus total expenses. The scorecard of business health.", theme: "decoder" },
  { id: "dec-12", label: "They say: 'Revenue is vanity, profit is sanity.' → Means: High revenue means nothing if you're spending it all. Profit — what's LEFT — is what counts.", theme: "decoder" },
  { id: "dec-13", label: "They say: 'What's your MRR?' → Means: Monthly Recurring Revenue — how much guaranteed money comes in each month from subscriptions/retainers.", theme: "decoder" },
  { id: "dec-14", label: "They say: 'We need to derisk this.' → Means: Reduce the chance of failure. Find ways to make this safer before betting big.", theme: "decoder" },
  { id: "dec-15", label: "They say: 'The opex is killing us.' → Means: Operating expenses (rent, salaries, subscriptions) are too high relative to income.", theme: "decoder" },
  { id: "dec-16", label: "They say: 'Capex vs. opex decision.' → Means: Buy it once (capital expense) or pay monthly (operating expense)? Different budget, different approval.", theme: "decoder" },
  { id: "dec-17", label: "They say: 'We're bootstrapped.' → Means: No outside investors. Built entirely from own revenue and savings. Implies self-reliance and scrappiness.", theme: "decoder" },
  { id: "dec-18", label: "They say: 'What's the TAM?' → Means: Total Addressable Market — the maximum possible revenue if you captured every customer in your market.", theme: "decoder" },
  { id: "dec-19", label: "They say: 'We're pre-revenue.' → Means: No money coming in yet. Still building the product/service. Translation: they have no income.", theme: "decoder" },
  { id: "dec-20", label: "They say: 'Net 30 payment terms.' → Means: They'll pay your invoice 30 days after receiving it. Net 15 = 15 days. Net 60 = 2 months.", theme: "decoder" },

  // --- Strategy Language Decoded ---
  { id: "dec-21", label: "They say: 'What's your moat?' → Means: What stops competitors from copying you? What makes you hard to replace? Your unique defense.", theme: "decoder" },
  { id: "dec-22", label: "They say: 'We need to pivot.' → Means: Our current approach isn't working. We need to change direction significantly.", theme: "decoder" },
  { id: "dec-23", label: "They say: 'Let's do a SWOT analysis.' → Means: List our Strengths, Weaknesses, Opportunities, and Threats. Simple framework for strategic thinking.", theme: "decoder" },
  { id: "dec-24", label: "They say: 'This is a blue ocean opportunity.' → Means: There's no competition here. It's a new market with unmet demand.", theme: "decoder" },
  { id: "dec-25", label: "They say: 'We're in a red ocean.' → Means: Too many competitors fighting over the same customers. Bloody competition. Hard to win.", theme: "decoder" },
  { id: "dec-26", label: "They say: 'What's the value proposition?' → Means: Why should a customer choose us? What specific value do we offer that others don't?", theme: "decoder" },
  { id: "dec-27", label: "They say: 'We need product-market fit.' → Means: We need to build something people actually WANT and are willing to PAY for.", theme: "decoder" },
  { id: "dec-28", label: "They say: 'Let's focus on the ICP.' → Means: Ideal Customer Profile — the exact type of customer most likely to buy and benefit from our product.", theme: "decoder" },
  { id: "dec-29", label: "They say: 'We need to build a flywheel.' → Means: Create a self-reinforcing cycle where each success feeds the next one automatically.", theme: "decoder" },
  { id: "dec-30", label: "They say: 'This is a build vs. buy decision.' → Means: Should we create this ourselves or purchase an existing solution? Which is cheaper/faster?", theme: "decoder" },

  { id: "dec-31", label: "They say: 'Let's productize this.' → Means: Turn a custom/manual service into a standardized product that can be sold repeatedly.", theme: "decoder" },
  { id: "dec-32", label: "They say: 'What's the go-to-market strategy?' → Means: How will we actually sell this? Through which channels, to whom, at what price?", theme: "decoder" },
  { id: "dec-33", label: "They say: 'We need a land-and-expand strategy.' → Means: Start small with a client, prove value, then gradually sell them more services.", theme: "decoder" },
  { id: "dec-34", label: "They say: 'The switching costs are high.' → Means: It's expensive/painful for clients to leave us and go to a competitor. Good for retention.", theme: "decoder" },
  { id: "dec-35", label: "They say: 'Let's talk about market penetration.' → Means: How much of the available market have we captured? What percentage are our customers?", theme: "decoder" },
  { id: "dec-36", label: "They say: 'We need a beachhead market.' → Means: One specific, small market to dominate first before expanding. Win one battle before the war.", theme: "decoder" },
  { id: "dec-37", label: "They say: 'There's a first-mover advantage.' → Means: Being first in a market gives you an edge — brand recognition, customer loyalty, market share.", theme: "decoder" },
  { id: "dec-38", label: "They say: 'We need network effects.' → Means: Our product becomes more valuable as more people use it. WhatsApp, UPI — each user adds value.", theme: "decoder" },
  { id: "dec-39", label: "They say: 'The long tail matters.' → Means: Many small customers/products can add up to more than a few big ones. Don't ignore the small fish.", theme: "decoder" },
  { id: "dec-40", label: "They say: 'What's the competitive landscape?' → Means: Who else is in this market? How strong are they? Where are the gaps we can exploit?", theme: "decoder" },

  // --- Meeting & Corporate Language Decoded ---
  { id: "dec-41", label: "They say: 'Let's take this offline.' → Means: Let's discuss this privately, not in front of everyone. Could mean it's sensitive or off-topic.", theme: "decoder" },
  { id: "dec-42", label: "They say: 'Let's circle back on that.' → Means: We'll revisit this topic later. Sometimes genuine, sometimes means 'I want to drop this.'", theme: "decoder" },
  { id: "dec-43", label: "They say: 'Let's align on this.' → Means: Let's make sure we all agree and are heading in the same direction before proceeding.", theme: "decoder" },
  { id: "dec-44", label: "They say: 'What's the bandwidth situation?' → Means: Does the team/person have time and capacity to take this on? Are they overloaded?", theme: "decoder" },
  { id: "dec-45", label: "They say: 'We need to socialize this idea.' → Means: Share it informally with key people before the formal meeting, so it's not a surprise.", theme: "decoder" },
  { id: "dec-46", label: "They say: 'Let me loop in stakeholders.' → Means: I need to bring in other people who are affected by or have authority over this decision.", theme: "decoder" },
  { id: "dec-47", label: "They say: 'This needs to go up the chain.' → Means: I don't have authority to decide. A senior person needs to approve this.", theme: "decoder" },
  { id: "dec-48", label: "They say: 'Let's park this for now.' → Means: Let's put this aside temporarily. We'll come back to it (maybe). Translation: not a priority.", theme: "decoder" },
  { id: "dec-49", label: "They say: 'We need more visibility into this.' → Means: We can't see what's happening. We need dashboards, reports, or regular updates.", theme: "decoder" },
  { id: "dec-50", label: "They say: 'What's the delta here?' → Means: What's the difference? The gap between current state and desired state. Or between two options.", theme: "decoder" },

  { id: "dec-51", label: "They say: 'Let's boil the ocean.' → Means: We're trying to do too much at once. (Usually said as 'Let's NOT boil the ocean' = let's focus.)", theme: "decoder" },
  { id: "dec-52", label: "They say: 'Move the needle.' → Means: Make a meaningful impact. Not just busy work — something that actually changes results.", theme: "decoder" },
  { id: "dec-53", label: "They say: 'What's the ask here?' → Means: What do you need from me? Cut to the chase — what's the specific request?", theme: "decoder" },
  { id: "dec-54", label: "They say: 'We need to be scrappy.' → Means: Do more with less. Be resourceful. Don't wait for perfect conditions — make it work.", theme: "decoder" },
  { id: "dec-55", label: "They say: 'This is table stakes.' → Means: This is the minimum expected. Not a differentiator — just the basic requirement to compete.", theme: "decoder" },
  { id: "dec-56", label: "They say: 'Let me push back on that.' → Means: I disagree and I'm going to explain why. A polite way of saying 'you're wrong.'", theme: "decoder" },
  { id: "dec-57", label: "They say: 'We're leaving money on the table.' → Means: We're missing revenue opportunities. There's money available that we're not capturing.", theme: "decoder" },
  { id: "dec-58", label: "They say: 'What's the lift here?' → Means: How much effort/resources will this require? Is it a small task or a major undertaking?", theme: "decoder" },
  { id: "dec-59", label: "They say: 'We need to level-set.' → Means: Let's make sure everyone has the same understanding before proceeding. Reset expectations.", theme: "decoder" },
  { id: "dec-60", label: "They say: 'This is a non-starter.' → Means: This is completely unacceptable. Don't even bring it up. It's off the table.", theme: "decoder" },

  // --- Sales & Client Language Decoded ---
  { id: "dec-61", label: "They say: 'We'll think about it.' → Actually means: Probably no. They're being polite. Follow up with 'What would help you decide?'", theme: "decoder" },
  { id: "dec-62", label: "They say: 'Send me a proposal.' → Could mean: Genuine interest OR 'go away politely.' Test with: 'When should I expect feedback?'", theme: "decoder" },
  { id: "dec-63", label: "They say: 'Our budget is tight.' → Actually means: Either truly tight, or 'I want a discount.' Response: 'What budget are you working with?'", theme: "decoder" },
  { id: "dec-64", label: "They say: 'We're happy with our current vendor.' → Means: I don't want to switch. But ask: 'What would make you even happier?' — find the gap.", theme: "decoder" },
  { id: "dec-65", label: "They say: 'This is great, we should do this.' → Watch for: no specific next step = probably not happening. Push for: 'When do we start?'", theme: "decoder" },
  { id: "dec-66", label: "They say: 'Let me discuss with my partner.' → Means: Either genuine or stalling. Ask: 'Can I join that conversation to answer technical questions?'", theme: "decoder" },
  { id: "dec-67", label: "They say: 'We're evaluating multiple vendors.' → Means: You're being compared. Differentiate NOW: 'What criteria are most important to you?'", theme: "decoder" },
  { id: "dec-68", label: "They say: 'Your price is too high.' → Could mean: 'I want a discount' or 'I don't see the value yet.' Respond: 'Compared to what?' — find their anchor.", theme: "decoder" },
  { id: "dec-69", label: "They say: 'We need it yesterday.' → Means: They're under pressure and need fast delivery. Opportunity: charge a premium for urgency.", theme: "decoder" },
  { id: "dec-70", label: "They say: 'Can you do a proof of concept?' → Means: I'm interested but not convinced. Build me something small to prove it works. Charge for this.", theme: "decoder" },

  { id: "dec-71", label: "They say: 'We have a limited budget.' → What to do: 'Let me design a solution that fits your budget and delivers maximum value within it.'", theme: "decoder" },
  { id: "dec-72", label: "They say: 'I'll get back to you.' → If no date given = likely cold. Always respond: 'When should I follow up if I don't hear back?'", theme: "decoder" },
  { id: "dec-73", label: "They say: 'Interesting.' → Means: They're thinking, not necessarily agreeing. Follow with: 'What specifically interests you about this?'", theme: "decoder" },
  { id: "dec-74", label: "They say: 'We're not ready yet.' → Means: Timing issue, not interest issue. Stay in touch: 'When would be a better time to revisit this?'", theme: "decoder" },
  { id: "dec-75", label: "They say: 'We tried something like this before.' → Means: It failed. They're skeptical. Ask: 'What went wrong? I'll make sure we avoid that.'", theme: "decoder" },
  { id: "dec-76", label: "They say: 'My nephew/son can do this.' → Means: They think it's easy/cheap. Response: 'That's great! What specific experience do they have with [complex thing]?'", theme: "decoder" },
  { id: "dec-77", label: "They say: 'We want a partnership, not a vendor.' → Means: They want shared risk. Could be good (long-term) or bad (free work). Clarify terms.", theme: "decoder" },
  { id: "dec-78", label: "They say: 'What's your best price?' → Means: 'I want a discount.' Response: 'This IS my best price. Let me show you why it's worth every rupee.'", theme: "decoder" },
  { id: "dec-79", label: "They say: 'We need something simple.' → Means: Budget-conscious. But also: 'simple' doesn't mean 'cheap to build.' Educate on complexity underneath.", theme: "decoder" },
  { id: "dec-80", label: "They say: 'Can you match this quote?' → Means: Someone else quoted lower. Ask to see the scope. Lower price usually means less work/quality.", theme: "decoder" },

  // --- Tech & Business Buzzwords Decoded ---
  { id: "dec-81", label: "They say: 'We need digital transformation.' → Means: We want to use technology to improve how we work. Often they don't know exactly what they need.", theme: "decoder" },
  { id: "dec-82", label: "They say: 'We need AI in this.' → Means: They want it to sound modern. Ask: 'What specific problem should AI solve for you?' — ground it in reality.", theme: "decoder" },
  { id: "dec-83", label: "They say: 'Make it scalable.' → Means: Build it so it works for 10 users today and 10,000 users tomorrow without rebuilding everything.", theme: "decoder" },
  { id: "dec-84", label: "They say: 'We need an ecosystem.' → Means: Multiple connected products/services that work together. Not just one app — a system.", theme: "decoder" },
  { id: "dec-85", label: "They say: 'What about data analytics?' → Means: Can the software give us insights, charts, patterns from our data? Not just store it — analyze it.", theme: "decoder" },
  { id: "dec-86", label: "They say: 'Cloud-based solution.' → Means: Hosted on the internet, not on their local computer. Accessible from anywhere. No server maintenance.", theme: "decoder" },
  { id: "dec-87", label: "They say: 'We need a dashboard.' → Means: A visual screen showing key numbers and status at a glance. Like a car dashboard but for business.", theme: "decoder" },
  { id: "dec-88", label: "They say: 'What about API integration?' → Means: Can our system talk to other systems automatically? Sharing data without manual copy-paste.", theme: "decoder" },
  { id: "dec-89", label: "They say: 'SaaS model.' → Means: Software as a Service — pay monthly to use it, don't buy it outright. Like a subscription.", theme: "decoder" },
  { id: "dec-90", label: "They say: 'We need automation.' → Means: Tasks that humans do manually should happen automatically. Reduce human effort and errors.", theme: "decoder" },

  // --- What People REALLY Mean (Hidden Agendas) ---
  { id: "dec-91", label: "When they keep rescheduling → They're not interested but don't want to say no. Give them an out: 'Should we reconnect when timing is better?'", theme: "decoder" },
  { id: "dec-92", label: "When they ask for references repeatedly → They're nervous about committing. Offer a small pilot project to build confidence instead.", theme: "decoder" },
  { id: "dec-93", label: "When they CC their boss on emails → They're escalating or covering themselves. Treat every email as if the boss is reading it directly.", theme: "decoder" },
  { id: "dec-94", label: "When they suddenly go formal after being casual → Something changed. They're creating distance. Ask directly: 'Is everything okay with the project?'", theme: "decoder" },
  { id: "dec-95", label: "When they ask 'How long have you been doing this?' → They're assessing credibility. Answer with confidence + proof: '25 years, including SEBI India.'", theme: "decoder" },
  { id: "dec-96", label: "When they compare you to a big company → They want big-company quality at small-company prices. Position: 'You get my personal attention, which no big firm offers.'", theme: "decoder" },
  { id: "dec-97", label: "When they say 'We'll do it in-house' → Either genuine or 'we don't want to pay.' Response: 'Great — if you need support later, I'm here.'", theme: "decoder" },
  { id: "dec-98", label: "When they ask many detailed questions → Good sign! Detailed questions mean they're seriously considering. Answer thoroughly.", theme: "decoder" },
  { id: "dec-99", label: "When they avoid talking about budget → They either don't have one or it's low. Bring it up: 'What range are you comfortable with?'", theme: "decoder" },
  { id: "dec-100", label: "When they say 'money is no object' → It ALWAYS is. Nail down the budget early. This phrase often leads to payment disputes later.", theme: "decoder" },

  // --- Negotiation Language Decoded ---
  { id: "dec-101", label: "They say: 'That's our final offer.' → Rarely final. If you walk away politely, they often come back. Scarcity creates urgency.", theme: "decoder" },
  { id: "dec-102", label: "They say: 'We need to do due diligence.' → Means: We're going to investigate thoroughly before committing. Prepare documentation.", theme: "decoder" },
  { id: "dec-103", label: "They say: 'This sets a precedent.' → Means: If we agree to this, we'll have to do the same for everyone else. They're worried about consistency.", theme: "decoder" },
  { id: "dec-104", label: "They say: 'Let's split the difference.' → Means: Meet in the middle of our two positions. Seems fair but may not be if their starting point was extreme.", theme: "decoder" },
  { id: "dec-105", label: "They say: 'We need more skin in the game.' → Means: They want you to share the risk. Are you willing to tie payment to results?", theme: "decoder" },
  { id: "dec-106", label: "They say: 'What's your walk-away point?' → Means: They're trying to find your minimum. Never answer directly. 'My price reflects the value I deliver.'", theme: "decoder" },
  { id: "dec-107", label: "They say: 'We value the relationship.' → Means: Either genuine OR 'please give us a discount for the sake of our friendship.' Clarify which.", theme: "decoder" },
  { id: "dec-108", label: "They say: 'Let's make this a win-win.' → Means: I want a deal that benefits both of us. Genuine collaboration signal. Build on it.", theme: "decoder" },
  { id: "dec-109", label: "They say: 'We have other options.' → Means: Creating competition to lower your price. Stay confident: 'Choose the option that gives you most value.'", theme: "decoder" },
  { id: "dec-110", label: "They say: 'This needs to be future-proof.' → Means: Build it so it doesn't need rebuilding soon. Use modern tech. Plan for growth.", theme: "decoder" },

  // --- Body Language Decoded ---
  { id: "dec-111", label: "They lean forward + uncross arms → Means: They're interested. Whatever you just said resonated. Keep going in this direction.", theme: "decoder" },
  { id: "dec-112", label: "They lean back + cross arms → Means: Resistance or disinterest. Change your approach. Ask a question to re-engage.", theme: "decoder" },
  { id: "dec-113", label: "They touch their chin while listening → Means: They're evaluating what you're saying. This is your moment — present your strongest point.", theme: "decoder" },
  { id: "dec-114", label: "They look at their watch/phone → Means: You're losing them. Summarize quickly: 'Let me get to the key point.'", theme: "decoder" },
  { id: "dec-115", label: "They nod but say nothing → Means: Could be agreement, could be 'I'm listening, continue.' Don't assume agreement — check: 'What are your thoughts?'", theme: "decoder" },
  { id: "dec-116", label: "They mirror your posture → Means: They're building rapport with you, consciously or not. Good sign — trust is forming.", theme: "decoder" },
  { id: "dec-117", label: "They avoid eye contact → Means: Discomfort, disagreement, or shyness. Don't push — create safety: 'I'd love your honest opinion on this.'", theme: "decoder" },
  { id: "dec-118", label: "They tap fingers or bounce leg → Means: Impatience or anxiety. They want you to get to the point faster. Shorten your pitch.", theme: "decoder" },
  { id: "dec-119", label: "They turn their body away from you → Means: They want to leave or disengage. Wrap up: 'I know you're busy — what's the one thing I should send you?'", theme: "decoder" },
  { id: "dec-120", label: "They smile but their eyes don't crinkle → Means: Polite/fake smile. They're being courteous, not genuinely engaged. Dig deeper.", theme: "decoder" },

  // --- Indian Business Culture Decoded ---
  { id: "dec-121", label: "They say: 'Agle hafte baat karte hain' → Often means: Not right now. Maybe never. Follow up once, then move on if no response.", theme: "decoder" },
  { id: "dec-122", label: "They say: 'Hum log family jaisa hai' → Means: They expect loyalty, flexibility, and sometimes free work. Set boundaries lovingly.", theme: "decoder" },
  { id: "dec-123", label: "They say: 'Pehle kaam dikhao, phir price discuss karte hain' → Red flag: they want free work. Response: 'Scope and pricing go together.'", theme: "decoder" },
  { id: "dec-124", label: "They say: 'Mera bhatija bhi coding seekh raha hai' → Means: 'Why should I pay you when my nephew can do it?' Response: smile and show your SEBI credential.", theme: "decoder" },
  { id: "dec-125", label: "They say: 'Aap toh hamare hi hai' → Means: 'You're one of us, so give us a discount.' Response: 'I give my best work to my community. That's more valuable than discount.'", theme: "decoder" },
  { id: "dec-126", label: "They say: 'Committee mein discuss karenge' → Means: Decision will be slow, political, and involve many opinions. Build allies one-on-one before the committee.", theme: "decoder" },
  { id: "dec-127", label: "They say: 'Budget abhi nahi hai' → Could mean: Genuinely tight OR lower priority. Ask: 'When does the next budget cycle start? I'll connect then.'", theme: "decoder" },
  { id: "dec-128", label: "They say: 'Sab theek hai' (everything is fine) → Watch their body language. In Indian culture, direct complaints are avoided. 'Fine' may mean 'not fine.'", theme: "decoder" },
  { id: "dec-129", label: "They say: 'Hamara purana developer ne bahut paisa liya' → Means: They got burned before and are price-sensitive. Show ROI and transparency.", theme: "decoder" },
  { id: "dec-130", label: "They say: 'Dekh lenge' (we'll see) → 80% of the time means no. 20% means genuine consideration. Don't invest too much hope. Follow up once.", theme: "decoder" },

  // --- Investor & Boardroom Language Decoded ---
  { id: "dec-131", label: "They say: 'What's your traction?' → Means: Show me proof of progress — users, revenue, growth rate. They want numbers, not promises.", theme: "decoder" },
  { id: "dec-132", label: "They say: 'What's your exit strategy?' → Means: How will investors get their money back (and more)? Acquisition? IPO? Revenue share?", theme: "decoder" },
  { id: "dec-133", label: "They say: 'What's the valuation?' → Means: How much is the company worth? Calculated as revenue or profit × an industry multiplier.", theme: "decoder" },
  { id: "dec-134", label: "They say: 'Show me the cap table.' → Means: Who owns what percentage of the company? They want to see the ownership structure.", theme: "decoder" },
  { id: "dec-135", label: "They say: 'What's the dilution?' → Means: How much of my ownership percentage will shrink if new investors come in?", theme: "decoder" },
  { id: "dec-136", label: "They say: 'We need governance.' → Means: Proper oversight, rules, reporting, and accountability structure. Not just informal management.", theme: "decoder" },
  { id: "dec-137", label: "They say: 'What's the fiduciary duty?' → Means: Legal obligation to act in the best interest of stakeholders (members, shareholders, etc.)", theme: "decoder" },
  { id: "dec-138", label: "They say: 'There's a conflict of interest.' → Means: Someone has personal benefit that might compromise their professional judgment.", theme: "decoder" },
  { id: "dec-139", label: "They say: 'Let's look at the balance sheet.' → Means: Show me what the company OWNS (assets) vs. what it OWES (liabilities). The financial health snapshot.", theme: "decoder" },
  { id: "dec-140", label: "They say: 'What's the CAGR?' → Means: Compound Annual Growth Rate — the smoothed annual growth rate over multiple years. Shows consistent trajectory.", theme: "decoder" },

  // --- Project & Delivery Language Decoded ---
  { id: "dec-141", label: "They say: 'What's the scope?' → Means: Exactly what will you build? What's included and what's not? Define boundaries clearly.", theme: "decoder" },
  { id: "dec-142", label: "They say: 'Scope creep is happening.' → Means: The project is growing beyond what was agreed, usually without additional payment. Bad sign.", theme: "decoder" },
  { id: "dec-143", label: "They say: 'What are the deliverables?' → Means: What tangible things will I receive? List every document, feature, screen, and handoff.", theme: "decoder" },
  { id: "dec-144", label: "They say: 'What's the SLA?' → Means: Service Level Agreement — guaranteed response times, uptime, support hours. Your commitment in writing.", theme: "decoder" },
  { id: "dec-145", label: "They say: 'We need an MVP.' → Means: Minimum Viable Product — the smallest possible version that works and proves the concept.", theme: "decoder" },
  { id: "dec-146", label: "They say: 'Let's do a sprint.' → Means: A short, focused burst of work (usually 1-2 weeks) with clear goals. Agile methodology term.", theme: "decoder" },
  { id: "dec-147", label: "They say: 'What's the tech stack?' → Means: What technologies are you using to build this? (Programming language, database, hosting, etc.)", theme: "decoder" },
  { id: "dec-148", label: "They say: 'Is this production-ready?' → Means: Is it stable and reliable enough for real users with real data? Not a prototype or demo.", theme: "decoder" },
  { id: "dec-149", label: "They say: 'We need UAT.' → Means: User Acceptance Testing — the client tests the system before final approval. Last checkpoint before go-live.", theme: "decoder" },
  { id: "dec-150", label: "They say: 'What about legacy systems?' → Means: Old existing software that still runs but is outdated. Will your new system work with it?", theme: "decoder" },

  // --- More Hidden Meanings in Conversation ---
  { id: "dec-151", label: "When they praise your competitor: → They're testing your reaction. Stay confident: 'They do good work. We do different work. Let me explain.'", theme: "decoder" },
  { id: "dec-152", label: "When they ask 'Do you have a team?' → They're worried you're a solo operation. Answer: 'Yes, I work with specialists for design, testing, and support.'", theme: "decoder" },
  { id: "dec-153", label: "When they say 'Keep it simple.' → They might mean 'Keep it cheap.' Clarify: 'Simple to use, or simple to build? They're very different things.'", theme: "decoder" },
  { id: "dec-154", label: "When they say 'We'll do Phase 2 later.' → 60% of the time, Phase 2 never happens. Get Phase 1 right and self-contained.", theme: "decoder" },
  { id: "dec-155", label: "When they say 'Just one small change.' → Rarely small. Ask: 'Can you describe exactly what you mean? I'll assess the effort.' — protect your time.", theme: "decoder" },
  { id: "dec-156", label: "When they invite you to chai but don't discuss business → They're evaluating you as a person first. Don't push business. Build the relationship.", theme: "decoder" },
  { id: "dec-157", label: "When they name-drop big companies → They want to feel important. Acknowledge it, then redirect: 'That's great company to keep. Here's how we can add to that.'", theme: "decoder" },
  { id: "dec-158", label: "When they ask 'Can you guarantee results?' → They're risk-averse. Offer milestones: 'I guarantee the deliverables. The results depend on both of us.'", theme: "decoder" },
  { id: "dec-159", label: "When they say 'We're in no rush.' → Either genuine patience OR code for 'not a priority.' Follow up in 2 weeks. If still delayed, deprioritize.", theme: "decoder" },
  { id: "dec-160", label: "When they say 'We just want to explore.' → Early stage. Don't invest too much time. Offer a paid discovery session to qualify serious buyers.", theme: "decoder" },

  // --- Emotional Subtext Decoded ---
  { id: "dec-161", label: "When they're overly friendly suddenly → They may need something from you. Enjoy the warmth but be aware — a request is probably coming.", theme: "decoder" },
  { id: "dec-162", label: "When they avoid your calls but reply to texts → They're uncomfortable with direct conversation. Something's wrong. Address it in text: 'Everything okay?'", theme: "decoder" },
  { id: "dec-163", label: "When they keep talking about other people's failures → They're afraid of failing too. Provide reassurance and small proof points.", theme: "decoder" },
  { id: "dec-164", label: "When they agree to everything immediately → Either very trusting OR not paying attention. Get written confirmation of key decisions.", theme: "decoder" },
  { id: "dec-165", label: "When they say 'I trust you completely.' → Nice to hear, but still document everything. Trust and professionalism go hand in hand.", theme: "decoder" },
  { id: "dec-166", label: "When they suddenly involve a third person → Power shift happening. The third person may be the real decision-maker. Redirect attention.", theme: "decoder" },
  { id: "dec-167", label: "When they ask you to explain the same thing twice → They don't understand but won't admit it. Simplify further. No jargon. Use analogies.", theme: "decoder" },
  { id: "dec-168", label: "When they say 'My wife/partner doesn't think we need this.' → The real objection is at home. Offer to present to both: 'Happy to walk through it together.'", theme: "decoder" },
  { id: "dec-169", label: "When they say 'Everyone says that.' → Your pitch sounds generic. Differentiate NOW with a specific example unique to their situation.", theme: "decoder" },
  { id: "dec-170", label: "When they laugh nervously → They're uncomfortable. Something you said triggered anxiety. Ease up: 'No pressure — this is just a conversation.'", theme: "decoder" },

  // --- Power Dynamics Decoded ---
  { id: "dec-171", label: "When the boss lets someone else talk first → That person's opinion matters to the boss. Win THAT person over, and you've won the boss.", theme: "decoder" },
  { id: "dec-172", label: "When they make you wait → Intentional or not, it's a power play. Don't show irritation. Use the time productively. Be gracious when they arrive.", theme: "decoder" },
  { id: "dec-173", label: "When they sit you in a lower chair → Classic power positioning. Sit upright, lean forward slightly. Don't shrink into the chair.", theme: "decoder" },
  { id: "dec-174", label: "When they interrupt you → They either value their time more than your point, or they're testing dominance. Calmly: 'If I may finish...'", theme: "decoder" },
  { id: "dec-175", label: "When they take a call during your meeting → Your meeting isn't their priority. Either shorten your pitch or reschedule: 'Shall we continue when it's more convenient?'", theme: "decoder" },
  { id: "dec-176", label: "When someone whispers to another during your presentation → They're forming an opinion privately. Pause and address: 'Any questions so far?'", theme: "decoder" },
  { id: "dec-177", label: "When they keep mentioning how busy they are → They want you to feel grateful for their time. Don't grovel. Be efficient and confident.", theme: "decoder" },
  { id: "dec-178", label: "When they say 'You should be grateful for this opportunity.' → Power play. Real opportunities don't need this qualifier. Value yourself.", theme: "decoder" },
  { id: "dec-179", label: "When they introduce you to someone powerful → They're either helping you genuinely OR showing off their network. Either way, make a great impression.", theme: "decoder" },
  { id: "dec-180", label: "When the room goes silent after your proposal → They're processing. Don't panic-fill the silence. Let it sit. The next person to speak will reveal the direction.", theme: "decoder" },

  // --- Modern Business Terms Decoded ---
  { id: "dec-181", label: "They say: 'We need to be agile.' → Means: Move fast, adapt quickly, don't plan for 6 months before doing anything. Short cycles, frequent feedback.", theme: "decoder" },
  { id: "dec-182", label: "They say: 'What's the north star metric?' → Means: The ONE number that shows if we're succeeding. For Gymkhana: active member engagement rate.", theme: "decoder" },
  { id: "dec-183", label: "They say: 'We need to iterate.' → Means: Build a version, get feedback, improve, repeat. Don't try to build the perfect thing on the first try.", theme: "decoder" },
  { id: "dec-184", label: "They say: 'Growth hacking.' → Means: Finding clever, low-cost ways to grow users/revenue fast. Often through product features, not traditional marketing.", theme: "decoder" },
  { id: "dec-185", label: "They say: 'We need a single source of truth.' → Means: One central place where all data lives. No more conflicting Excel files on different computers.", theme: "decoder" },
  { id: "dec-186", label: "They say: 'What's the tech debt?' → Means: Shortcuts taken during development that will need to be fixed later. Like financial debt — it compounds.", theme: "decoder" },
  { id: "dec-187", label: "They say: 'We need to sunset this.' → Means: Gradually phase out and retire an old product/system. Not kill it suddenly — wind it down gracefully.", theme: "decoder" },
  { id: "dec-188", label: "They say: 'Customer success.' → Means: Not just customer service (fixing problems) but proactively helping customers get value. Higher-level support.", theme: "decoder" },
  { id: "dec-189", label: "They say: 'What's the churn?' → Means: What percentage of customers/members leave per month/year? Lower churn = healthier business.", theme: "decoder" },
  { id: "dec-190", label: "They say: 'We need to be data-driven.' → Means: Make decisions based on numbers and evidence, not gut feeling or opinions. Track, measure, act.", theme: "decoder" },

  // --- Final Wisdom Decoders ---
  { id: "dec-191", label: "The golden rule of decoding: listen to what they DON'T say as much as what they do. Silence, pauses, and omissions tell the real story.", theme: "decoder" },
  { id: "dec-192", label: "The 'watch the feet' rule: words lie, feet don't. If their body points away, their mind is already elsewhere. Wrap up.", theme: "decoder" },
  { id: "dec-193", label: "The 'follow the money' rule: when confused about someone's motivation, ask 'Who benefits financially?' — that's usually the real driver.", theme: "decoder" },
  { id: "dec-194", label: "The 'three times' rule: if someone says the same concern three times in different ways, THAT's the real issue. Address it head-on.", theme: "decoder" },
  { id: "dec-195", label: "The 'energy shift' rule: notice when the energy in a conversation changes. That moment — the topic, the word — is where the truth lives.", theme: "decoder" },
  { id: "dec-196", label: "The 'what would I mean?' rule: when decoding others, ask 'If I said that, what would I mean?' — your gut often knows the answer.", theme: "decoder" },
  { id: "dec-197", label: "The 'context over content' rule: the same words mean different things in different contexts. 'Let's do lunch' at Gymkhana ≠ 'Let's do lunch' in a cold email.", theme: "decoder" },
  { id: "dec-198", label: "The 'pattern recognition' rule: track what people DO after they SAY things. Their actions reveal their true meaning over time.", theme: "decoder" },
  { id: "dec-199", label: "The 'ask, don't assume' rule: when in doubt about what someone meant, ask: 'I want to make sure I understand — can you elaborate?' — clarity > assumption.", theme: "decoder" },
  { id: "dec-200", label: "The ultimate decoder: every conversation has 3 layers — what they say, what they mean, and what they want you to do. Listen for all three.", theme: "decoder" },
];
