import { PowerCheckItem } from "./power-checks";

// 500 CEO-level tips: attitude, composure, stress, difficult people, body language, super sentences
export const ceoSpeaksTips: PowerCheckItem[] = [
  // ============================================================
  // SECTION 1: SUPER SENTENCES THAT CHANGE THE ROOM (100)
  // ============================================================

  // --- Power Openers ---
  { id: "ceo-1", label: "CEO sentence: 'I've thought about this carefully, and here's where I stand.' — decisive, considered, final.", theme: "ceo-speaks" },
  { id: "ceo-2", label: "CEO sentence: 'Let me be clear about one thing.' — instantly commands attention", theme: "ceo-speaks" },
  { id: "ceo-3", label: "CEO sentence: 'The world doesn't owe us anything. We earn it. Every single day.' — ownership mindset", theme: "ceo-speaks" },
  { id: "ceo-4", label: "CEO sentence: 'I don't hope for the best — I prepare for it.' — proactive, not wishful", theme: "ceo-speaks" },
  { id: "ceo-5", label: "CEO sentence: 'Results speak. Everything else is noise.' — shut down excuses elegantly", theme: "ceo-speaks" },
  { id: "ceo-6", label: "CEO sentence: 'I'm not interested in blame. I'm interested in solutions.' — leadership in one line", theme: "ceo-speaks" },
  { id: "ceo-7", label: "CEO sentence: 'The standard I walk past is the standard I accept.' — military leadership wisdom", theme: "ceo-speaks" },
  { id: "ceo-8", label: "CEO sentence: 'I measure progress, not promises.' — action-oriented thinking", theme: "ceo-speaks" },
  { id: "ceo-9", label: "CEO sentence: 'My reputation is my most valuable asset. I protect it with every decision.' — integrity", theme: "ceo-speaks" },
  { id: "ceo-10", label: "CEO sentence: 'If it's worth doing, it's worth doing right.' — quality mindset", theme: "ceo-speaks" },

  // --- Sentences That Show Depth ---
  { id: "ceo-11", label: "CEO sentence: 'The best deals are the ones where everyone walks away feeling they won.' — abundance thinking", theme: "ceo-speaks" },
  { id: "ceo-12", label: "CEO sentence: 'I don't chase. I attract. What belongs to me will simply find me.' — magnetic confidence", theme: "ceo-speaks" },
  { id: "ceo-13", label: "CEO sentence: 'I'd rather lose the deal than lose my integrity.' — this one HITS in Kutchi business circles", theme: "ceo-speaks" },
  { id: "ceo-14", label: "CEO sentence: 'Patience is not passive. It's strategic waiting.' — reframe patience as power", theme: "ceo-speaks" },
  { id: "ceo-15", label: "CEO sentence: 'The market rewards consistency, not heroics.' — steady effort wins", theme: "ceo-speaks" },
  { id: "ceo-16", label: "CEO sentence: 'I don't need everyone to agree with me. I need the right people to trust me.' — selective authority", theme: "ceo-speaks" },
  { id: "ceo-17", label: "CEO sentence: 'The hardest part isn't starting. It's continuing when no one is watching.' — discipline", theme: "ceo-speaks" },
  { id: "ceo-18", label: "CEO sentence: 'I invest in relationships the way others invest in stocks — for the long term.' — powerful metaphor", theme: "ceo-speaks" },
  { id: "ceo-19", label: "CEO sentence: 'Success without fulfillment is the ultimate failure.' — Tony Robbins wisdom, reframed", theme: "ceo-speaks" },
  { id: "ceo-20", label: "CEO sentence: 'Every setback has taught me something I couldn't learn from success.' — growth mindset", theme: "ceo-speaks" },

  // --- Sentences for Business Situations ---
  { id: "ceo-21", label: "When someone doubts you: 'I understand your concern. Let my work speak.' — calm, unshakeable.", theme: "ceo-speaks" },
  { id: "ceo-22", label: "When asked to discount: 'My price reflects my value. I don't discount my experience.' — firm, not arrogant.", theme: "ceo-speaks" },
  { id: "ceo-23", label: "When a project fails: 'We learned something expensive. Now let's make it pay off.' — resilience.", theme: "ceo-speaks" },
  { id: "ceo-24", label: "When someone brags: 'That's impressive. Tell me more.' — let them talk. Information is power.", theme: "ceo-speaks" },
  { id: "ceo-25", label: "When criticized: 'Thank you for the feedback. I'll consider it seriously.' — grace under fire.", theme: "ceo-speaks" },
  { id: "ceo-26", label: "When you win a deal: 'I'm grateful for the trust. Now let me exceed your expectations.' — humble, driven.", theme: "ceo-speaks" },
  { id: "ceo-27", label: "When losing a deal: 'I respect your decision. My door stays open.' — professional, dignified exit.", theme: "ceo-speaks" },
  { id: "ceo-28", label: "When someone is late: say nothing. Start without them. That's the power move.", theme: "ceo-speaks" },
  { id: "ceo-29", label: "When asked 'How's business?': 'Growing. We're in an exciting phase.' — ALWAYS forward, NEVER down.", theme: "ceo-speaks" },
  { id: "ceo-30", label: "When someone shares bad news: 'Thank you for telling me directly. What's the plan to fix it?' — solution mode.", theme: "ceo-speaks" },

  // --- Sentences That Build Character ---
  { id: "ceo-31", label: "Say today: 'I am exactly where I need to be. And I'm building something extraordinary.' — affirm your position.", theme: "ceo-speaks" },
  { id: "ceo-32", label: "Say today: 'My past doesn't define me. My next move does.' — forward-looking energy.", theme: "ceo-speaks" },
  { id: "ceo-33", label: "Say today: 'I am not competing with anyone. I am outdoing my yesterday.' — personal growth focus.", theme: "ceo-speaks" },
  { id: "ceo-34", label: "Say today: 'The comeback is always stronger than the setback.' — resilience mantra.", theme: "ceo-speaks" },
  { id: "ceo-35", label: "Say today: 'I carry myself like someone who has already achieved what I'm working toward.' — act the part.", theme: "ceo-speaks" },
  { id: "ceo-36", label: "Say today: 'Discomfort is the price of growth. I pay it gladly.' — embrace the struggle.", theme: "ceo-speaks" },
  { id: "ceo-37", label: "Say today: 'My energy is my currency. I invest it wisely.' — protect what fuels you.", theme: "ceo-speaks" },
  { id: "ceo-38", label: "Say today: 'I don't react. I respond.' — space between stimulus and response is where power lives.", theme: "ceo-speaks" },
  { id: "ceo-39", label: "Say today: 'I am the CEO of my life. No one else gets that title.' — radical ownership.", theme: "ceo-speaks" },
  { id: "ceo-40", label: "Say today: 'People are watching how I handle this. I will handle it with grace.' — reputation in real time.", theme: "ceo-speaks" },

  // --- Sentences That Close Rooms ---
  { id: "ceo-41", label: "Closing sentence: 'I believe we're done here. Let's make it happen.' — end meetings with action, not ambiguity.", theme: "ceo-speaks" },
  { id: "ceo-42", label: "Closing sentence: 'The next step is clear. Who's owning it?' — accountability in one question.", theme: "ceo-speaks" },
  { id: "ceo-43", label: "Closing sentence: 'I've heard enough. Here's what we're doing.' — decisive and directional.", theme: "ceo-speaks" },
  { id: "ceo-44", label: "Closing sentence: 'Let's not overthink this. Ship it.' — bias for action.", theme: "ceo-speaks" },
  { id: "ceo-45", label: "Closing sentence: 'Good talk. I'll send you the summary tonight.' — own the narrative.", theme: "ceo-speaks" },
  { id: "ceo-46", label: "Closing sentence: 'I appreciate your time. You'll hear from me within 24 hours.' — urgency + professionalism.", theme: "ceo-speaks" },
  { id: "ceo-47", label: "Closing sentence: 'This is going to be great. Let's begin.' — optimism + action.", theme: "ceo-speaks" },
  { id: "ceo-48", label: "Closing sentence: 'I'm confident in this direction. Let's execute.' — certainty drives others to act.", theme: "ceo-speaks" },
  { id: "ceo-49", label: "Closing sentence: 'We have alignment. Now we need velocity.' — move from agreement to speed.", theme: "ceo-speaks" },
  { id: "ceo-50", label: "Closing sentence: 'Thank you for this. I don't take your trust lightly.' — gratitude + gravitas.", theme: "ceo-speaks" },

  // --- More Power Sentences ---
  { id: "ceo-51", label: "CEO sentence: 'I don't have competitors. I have my own path.' — refuse to play comparison games.", theme: "ceo-speaks" },
  { id: "ceo-52", label: "CEO sentence: 'Silence is my first response to chaos. Clarity is my second.' — composure.", theme: "ceo-speaks" },
  { id: "ceo-53", label: "CEO sentence: 'I protect my peace like I protect my portfolio.' — mental health = asset management.", theme: "ceo-speaks" },
  { id: "ceo-54", label: "CEO sentence: 'My word is my contract. When I commit, it's done.' — old-world integrity, new-world power.", theme: "ceo-speaks" },
  { id: "ceo-55", label: "CEO sentence: 'I'm not building a business. I'm building a legacy.' — elevate the purpose.", theme: "ceo-speaks" },
  { id: "ceo-56", label: "CEO sentence: 'Being kind is not being weak. It's being secure enough to be generous.' — redefine strength.", theme: "ceo-speaks" },
  { id: "ceo-57", label: "CEO sentence: 'I don't burn bridges. I build longer roads.' — strategic patience.", theme: "ceo-speaks" },
  { id: "ceo-58", label: "CEO sentence: 'Every person I meet is either a teacher, a student, or a mirror.' — learn from everyone.", theme: "ceo-speaks" },
  { id: "ceo-59", label: "CEO sentence: 'Urgency without anxiety. Speed without panic. Drive without desperation.' — the CEO temperament.", theme: "ceo-speaks" },
  { id: "ceo-60", label: "CEO sentence: 'I'd rather be respected than liked. But when you do both, you're unstoppable.' — the goal.", theme: "ceo-speaks" },

  { id: "ceo-61", label: "CEO sentence: 'The quality of my questions determines the quality of my life.' — curiosity as superpower.", theme: "ceo-speaks" },
  { id: "ceo-62", label: "CEO sentence: 'I show up early. I stay late. And I deliver before the deadline.' — work ethic statement.", theme: "ceo-speaks" },
  { id: "ceo-63", label: "CEO sentence: 'I don't explain my choices to people who aren't part of my journey.' — boundaries.", theme: "ceo-speaks" },
  { id: "ceo-64", label: "CEO sentence: 'When in doubt, I choose the harder right over the easier wrong.' — moral courage.", theme: "ceo-speaks" },
  { id: "ceo-65", label: "CEO sentence: 'Small minds discuss people. Average minds discuss events. Great minds discuss ideas.' — Eleanor Roosevelt.", theme: "ceo-speaks" },
  { id: "ceo-66", label: "CEO sentence: 'My success is inevitable. The timeline is the only variable.' — unwavering belief.", theme: "ceo-speaks" },
  { id: "ceo-67", label: "CEO sentence: 'I don't just want a seat at the table. I want to set the table.' — create your own opportunities.", theme: "ceo-speaks" },
  { id: "ceo-68", label: "CEO sentence: 'Knowledge speaks. Wisdom listens.' — Jimi Hendrix, applied to business.", theme: "ceo-speaks" },
  { id: "ceo-69", label: "CEO sentence: 'I am not what happened to me. I am what I choose to become.' — Jung, adapted.", theme: "ceo-speaks" },
  { id: "ceo-70", label: "CEO sentence: 'People will forget what you said. They'll never forget how you made them feel.' — Maya Angelou.", theme: "ceo-speaks" },

  { id: "ceo-71", label: "CEO sentence: 'Execution eats strategy for breakfast.' — do the work, don't just plan it.", theme: "ceo-speaks" },
  { id: "ceo-72", label: "CEO sentence: 'I don't manage time. I manage energy and attention.' — next-level productivity.", theme: "ceo-speaks" },
  { id: "ceo-73", label: "CEO sentence: 'If you want to go fast, go alone. If you want to go far, go together.' — African proverb.", theme: "ceo-speaks" },
  { id: "ceo-74", label: "CEO sentence: 'I'm always the most prepared person in the room.' — preparation IS the edge.", theme: "ceo-speaks" },
  { id: "ceo-75", label: "CEO sentence: 'Comfort zone is a beautiful place, but nothing ever grows there.' — push yourself daily.", theme: "ceo-speaks" },
  { id: "ceo-76", label: "CEO sentence: 'The way you do anything is the way you do everything.' — excellence is a habit.", theme: "ceo-speaks" },
  { id: "ceo-77", label: "CEO sentence: 'I turn obstacles into stepping stones.' — not poetry, a daily practice.", theme: "ceo-speaks" },
  { id: "ceo-78", label: "CEO sentence: 'There is no traffic jam on the extra mile.' — go further than expected.", theme: "ceo-speaks" },
  { id: "ceo-79", label: "CEO sentence: 'I'm building in silence. Let success make the noise.' — let results announce you.", theme: "ceo-speaks" },
  { id: "ceo-80", label: "CEO sentence: 'A lion doesn't concern itself with the opinions of sheep.' — selective attention.", theme: "ceo-speaks" },

  { id: "ceo-81", label: "CEO sentence: 'My net worth is not my self-worth.' — separate identity from bank balance.", theme: "ceo-speaks" },
  { id: "ceo-82", label: "CEO sentence: 'I don't lose. I either win or I learn.' — Nelson Mandela's philosophy.", theme: "ceo-speaks" },
  { id: "ceo-83", label: "CEO sentence: 'Be so good they can't ignore you.' — Steve Martin's career advice.", theme: "ceo-speaks" },
  { id: "ceo-84", label: "CEO sentence: 'Price is what you pay. Value is what you get.' — Buffett, applied to your pricing.", theme: "ceo-speaks" },
  { id: "ceo-85", label: "CEO sentence: 'Done is better than perfect.' — ship it, iterate, improve.", theme: "ceo-speaks" },
  { id: "ceo-86", label: "CEO sentence: 'I collect relationships, not possessions.' — wealth that compounds forever.", theme: "ceo-speaks" },
  { id: "ceo-87", label: "CEO sentence: 'In chaos, I am the calm. In doubt, I am the clarity.' — be the anchor.", theme: "ceo-speaks" },
  { id: "ceo-88", label: "CEO sentence: 'I show respect to everyone. Not because of who they are, but because of who I am.' — character.", theme: "ceo-speaks" },
  { id: "ceo-89", label: "CEO sentence: 'My scars are my credentials.' — 25 years of experience includes failures. Own them.", theme: "ceo-speaks" },
  { id: "ceo-90", label: "CEO sentence: 'I am not available for mediocrity.' — set the standard.", theme: "ceo-speaks" },

  { id: "ceo-91", label: "CEO sentence: 'The best revenge is massive success.' — Frank Sinatra. Channel frustration into fuel.", theme: "ceo-speaks" },
  { id: "ceo-92", label: "CEO sentence: 'What I lack in resources, I make up in resourcefulness.' — hustle.", theme: "ceo-speaks" },
  { id: "ceo-93", label: "CEO sentence: 'I don't wait for opportunity. I create it.' — proactive mindset.", theme: "ceo-speaks" },
  { id: "ceo-94", label: "CEO sentence: 'Pressure makes diamonds.' — embrace it, don't run from it.", theme: "ceo-speaks" },
  { id: "ceo-95", label: "CEO sentence: 'I am the average of the five people I spend the most time with.' — Jim Rohn. Choose wisely.", theme: "ceo-speaks" },
  { id: "ceo-96", label: "CEO sentence: 'Talk is cheap. Execution is expensive. That's why I focus on execution.' — action > words.", theme: "ceo-speaks" },
  { id: "ceo-97", label: "CEO sentence: 'I don't need motivation. I have discipline.' — discipline > motivation, always.", theme: "ceo-speaks" },
  { id: "ceo-98", label: "CEO sentence: 'Your vibe attracts your tribe.' — energy management is business strategy.", theme: "ceo-speaks" },
  { id: "ceo-99", label: "CEO sentence: 'I play the long game. Today's seed is next year's harvest.' — patience with purpose.", theme: "ceo-speaks" },
  { id: "ceo-100", label: "CEO sentence: 'I am not for everyone. And that's exactly as it should be.' — confidence in niche.", theme: "ceo-speaks" },

  // ============================================================
  // SECTION 2: ATTITUDE MODIFICATION TECHNIQUES (100)
  // ============================================================

  { id: "att-1", label: "Attitude reset: before stepping out, ask 'What energy am I bringing today?' — make it intentional, not accidental.", theme: "attitude" },
  { id: "att-2", label: "Attitude shift: replace 'I have to' with 'I get to' — I GET to go to Gymkhana. I GET to work on this project.", theme: "attitude" },
  { id: "att-3", label: "Attitude practice: catch yourself in a negative thought. Stop. Replace with one positive fact. This is a muscle — train it.", theme: "attitude" },
  { id: "att-4", label: "Attitude technique: the 5-second rule — when you feel hesitation, count 5-4-3-2-1 and ACT. Break the overthinking loop.", theme: "attitude" },
  { id: "att-5", label: "Attitude shift: stop saying 'I can't afford it.' Start saying 'How can I afford it?' — opens the mind to solutions.", theme: "attitude" },
  { id: "att-6", label: "Attitude practice: write down 3 wins from yesterday, no matter how small. This rewires your brain to see progress.", theme: "attitude" },
  { id: "att-7", label: "Attitude technique: the reframe — 'This client is difficult' → 'This client is helping me build patience and resilience.'", theme: "attitude" },
  { id: "att-8", label: "Attitude shift: stop comparing your chapter 1 to someone's chapter 20. Everyone is on a different timeline.", theme: "attitude" },
  { id: "att-9", label: "Attitude practice: smile at yourself in the mirror for 30 seconds. It sounds silly, but it triggers real serotonin.", theme: "attitude" },
  { id: "att-10", label: "Attitude technique: the 'as if' method — act AS IF you're already successful. Walk like it. Talk like it. Decide like it.", theme: "attitude" },

  { id: "att-11", label: "Attitude reset: when frustrated, ask 'Will this matter in 5 years?' If no, release it. If yes, fix it calmly.", theme: "attitude" },
  { id: "att-12", label: "Attitude shift: replace 'Why is this happening TO me?' with 'What is this teaching me?' — victim to student.", theme: "attitude" },
  { id: "att-13", label: "Attitude practice: compliment a stranger today. Genuine kindness lifts YOUR mood more than theirs.", theme: "attitude" },
  { id: "att-14", label: "Attitude technique: journaling — write 5 minutes about what's bothering you. Externalizing thoughts reduces their power.", theme: "attitude" },
  { id: "att-15", label: "Attitude shift: stop seeking validation. Your work speaks. Your character shows. The right people will notice.", theme: "attitude" },
  { id: "att-16", label: "Attitude practice: gratitude before complaint. For every one complaint, name five blessings. The ratio matters.", theme: "attitude" },
  { id: "att-17", label: "Attitude technique: visualization — spend 2 minutes seeing yourself in a successful client meeting. Your brain rehearses success.", theme: "attitude" },
  { id: "att-18", label: "Attitude shift: stop apologizing for taking up space. You belong in every room you enter. EVERY room.", theme: "attitude" },
  { id: "att-19", label: "Attitude practice: do one uncomfortable thing before 10 AM. Call a prospect. Post on LinkedIn. Ask for money owed.", theme: "attitude" },
  { id: "att-20", label: "Attitude technique: the power stance — stand for 2 minutes with hands on hips, chin up. It literally changes your cortisol.", theme: "attitude" },

  { id: "att-21", label: "Attitude reset: when jealous of someone's success, convert it to curiosity. 'What did they do that I can learn from?'", theme: "attitude" },
  { id: "att-22", label: "Attitude shift: 'Nobody gives me work' → 'I haven't asked the right person in the right way yet.' — ownership.", theme: "attitude" },
  { id: "att-23", label: "Attitude practice: celebrate small wins. Sent a proposal? Win. Got a reply? Win. Had a good conversation? Win.", theme: "attitude" },
  { id: "att-24", label: "Attitude technique: 'What would the confident version of me do right now?' — then do that. Bypass the fear.", theme: "attitude" },
  { id: "att-25", label: "Attitude shift: stop thinking 'I'm too old for this.' 51 with 25 years experience = PEAK earning years.", theme: "attitude" },
  { id: "att-26", label: "Attitude practice: when someone annoys you, pause and think 'They're fighting a battle I know nothing about.' — compassion diffuses anger.", theme: "attitude" },
  { id: "att-27", label: "Attitude technique: morning affirmation — 'I am capable. I am valuable. I create opportunities.' — say it out loud.", theme: "attitude" },
  { id: "att-28", label: "Attitude shift: 'Market is bad' → 'Market is adjusting, and adjustment creates opportunity.' — every downturn is a setup.", theme: "attitude" },
  { id: "att-29", label: "Attitude practice: physical first — 10 pushups or a 5-minute walk when you feel mentally stuck. Body leads mind.", theme: "attitude" },
  { id: "att-30", label: "Attitude technique: the 'done list' — at the end of each day, write what you accomplished, not what's left. Focus on progress.", theme: "attitude" },

  { id: "att-31", label: "Attitude reset: when overwhelmed, write down everything on your mind. Then circle the top 3. Do those. Release the rest.", theme: "attitude" },
  { id: "att-32", label: "Attitude shift: 'I'm just a freelancer' → 'I run a technology consulting firm with 25 years of enterprise experience.' — language matters.", theme: "attitude" },
  { id: "att-33", label: "Attitude practice: dress like the person you want to become. Your wardrobe is a daily attitude adjustment tool.", theme: "attitude" },
  { id: "att-34", label: "Attitude technique: the 'opposite action' — when you feel like isolating, go to Gymkhana. When you want to hide, show up.", theme: "attitude" },
  { id: "att-35", label: "Attitude shift: stop waiting for motivation. Take action first. Motivation follows movement, not the other way around.", theme: "attitude" },
  { id: "att-36", label: "Attitude practice: when you catch yourself gossiping, stop. Say something good about the person instead. It rewires your brain.", theme: "attitude" },
  { id: "att-37", label: "Attitude technique: the 'zoom out' — when a problem feels huge, ask 'How does this look from 10,000 feet?' — it's usually smaller than you think.", theme: "attitude" },
  { id: "att-38", label: "Attitude shift: 'I failed' → 'That approach didn't work. Let me try another.' — failure is data, not identity.", theme: "attitude" },
  { id: "att-39", label: "Attitude practice: help someone today with zero expectation of return. Pure giving generates a real energetic shift.", theme: "attitude" },
  { id: "att-40", label: "Attitude technique: environmental design — surround yourself with energy-givers, not energy-drainers. Ruthlessly curate your circle.", theme: "attitude" },

  { id: "att-41", label: "Attitude reset: 'What would I tell my daughter if she felt this way?' — give yourself the same compassion you'd give your child.", theme: "attitude" },
  { id: "att-42", label: "Attitude shift: 'Nobody respects me' → 'I respect myself. Others will follow.' — self-respect is the foundation.", theme: "attitude" },
  { id: "att-43", label: "Attitude practice: read one page of a motivational book before sleeping. Small input, big compound effect.", theme: "attitude" },
  { id: "att-44", label: "Attitude technique: the 'anchor' — pick a physical gesture (like touching your watch) and pair it with a confident state. Use it before meetings.", theme: "attitude" },
  { id: "att-45", label: "Attitude shift: 'Money is hard to make' → 'Money flows to those who create value. I create immense value.' — abundance mindset.", theme: "attitude" },
  { id: "att-46", label: "Attitude practice: when negative self-talk starts, say 'Stop.' out loud. Then replace with one true positive statement.", theme: "attitude" },
  { id: "att-47", label: "Attitude technique: focus on 'controllables' — you can't control the market, but you CAN control your daily actions.", theme: "attitude" },
  { id: "att-48", label: "Attitude shift: 'I wasted my best years' → 'My best years are RIGHT NOW. I'm healthier, wiser, and more experienced than ever.'", theme: "attitude" },
  { id: "att-49", label: "Attitude practice: forgive yourself for yesterday's mistakes. Self-punishment reduces tomorrow's energy. Let it go.", theme: "attitude" },
  { id: "att-50", label: "Attitude technique: the 'identity switch' — don't just change behavior, change identity. You're not trying to sell. You ARE a trusted advisor.", theme: "attitude" },

  { id: "att-51", label: "Attitude reset: take 3 deep breaths before any high-stakes conversation. Oxygen is the cheapest performance enhancer.", theme: "attitude" },
  { id: "att-52", label: "Attitude shift: 'My family depends on me' → reframe to 'My family INSPIRES me to be extraordinary.' — love as fuel, not pressure.", theme: "attitude" },
  { id: "att-53", label: "Attitude practice: walk into Gymkhana today with your head high, regardless of how you feel. Fake it until you become it.", theme: "attitude" },
  { id: "att-54", label: "Attitude technique: gratitude meditation — 60 seconds, eyes closed, list everything you're grateful for. Resets emotional baseline.", theme: "attitude" },
  { id: "att-55", label: "Attitude shift: stop saying 'sorry' when you mean 'excuse me' or 'thank you.' Excessive apology erodes authority.", theme: "attitude" },
  { id: "att-56", label: "Attitude practice: accept a compliment fully today. Don't deflect. Say 'Thank you, I appreciate that.' — receive gracefully.", theme: "attitude" },
  { id: "att-57", label: "Attitude technique: the 'pre-frame' — before any meeting, set an intention: 'I will leave this conversation having added value.'", theme: "attitude" },
  { id: "att-58", label: "Attitude shift: 'Competition is fierce' → 'My positioning is unique. No one else offers what I offer, the way I offer it.'", theme: "attitude" },
  { id: "att-59", label: "Attitude practice: laugh today. Genuinely, deeply. Watch something funny. Laughter releases endorphins and resets stress.", theme: "attitude" },
  { id: "att-60", label: "Attitude technique: evening reflection — 'What went well today? What would I do differently?' — no judgment, just growth.", theme: "attitude" },

  { id: "att-61", label: "Attitude reset: when anxiety hits, ground yourself: 5 things you see, 4 you touch, 3 you hear, 2 you smell, 1 you taste.", theme: "attitude" },
  { id: "att-62", label: "Attitude shift: 'I have too many problems' → 'I have challenges worth solving.' — problems mean you're alive and growing.", theme: "attitude" },
  { id: "att-63", label: "Attitude practice: stand in front of a mirror and say 'I am the kind of person who builds million-rupee businesses.' — identity reinforcement.", theme: "attitude" },
  { id: "att-64", label: "Attitude technique: limit news consumption to 15 minutes. Excess negative news programs your mind for fear, not action.", theme: "attitude" },
  { id: "att-65", label: "Attitude shift: 'No one understands me' → 'The right people will understand when they see my results.' — patience.", theme: "attitude" },
  { id: "att-66", label: "Attitude practice: cold water face splash when mentally foggy. 30 seconds of cold water activates the vagus nerve. Instant reset.", theme: "attitude" },
  { id: "att-67", label: "Attitude technique: 'What advice would I give a friend in my situation?' — we're kinder to others than ourselves. Be your own friend.", theme: "attitude" },
  { id: "att-68", label: "Attitude shift: 'Kutchi community doesn't value software' → 'I haven't shown them the value clearly enough yet.' — keep refining.", theme: "attitude" },
  { id: "att-69", label: "Attitude practice: spend 10 minutes in silence today. No phone, no music, no input. Let your mind process and reset.", theme: "attitude" },
  { id: "att-70", label: "Attitude technique: habit stacking — attach a new positive behavior to an existing habit. After morning tea → 3 gratitudes.", theme: "attitude" },

  { id: "att-71", label: "Attitude reset: you are ONE conversation away from a life-changing opportunity. That conversation could happen today at Gymkhana.", theme: "attitude" },
  { id: "att-72", label: "Attitude shift: 'Why me?' → 'Try me.' — challenge accepted, not challenge feared.", theme: "attitude" },
  { id: "att-73", label: "Attitude practice: delete one negative contact from your mental space today. Distance from energy vampires.", theme: "attitude" },
  { id: "att-74", label: "Attitude technique: 'What's the BEST thing that could happen today?' — prime your brain for opportunity, not disaster.", theme: "attitude" },
  { id: "att-75", label: "Attitude shift: 'I need to be perfect' → 'I need to be consistent.' — consistency beats perfection every single time.", theme: "attitude" },
  { id: "att-76", label: "Attitude practice: give yourself permission to rest without guilt. Rest is productive. Burnout is not.", theme: "attitude" },
  { id: "att-77", label: "Attitude technique: positive self-talk during exercise — 'I am strong. I am capable. I am building something great.'", theme: "attitude" },
  { id: "att-78", label: "Attitude shift: 'Stock market took my money' → 'The market taught me an expensive lesson. Now I build real assets — my business.'", theme: "attitude" },
  { id: "att-79", label: "Attitude practice: notice 3 beautiful things today. A sunset, a kind gesture, a child's laugh. Beauty restores perspective.", theme: "attitude" },
  { id: "att-80", label: "Attitude technique: 'What would Ashish at 60 be proud of me for doing today?' — your future self as compass.", theme: "attitude" },

  { id: "att-81", label: "Attitude reset: remember your girls look up to you. The way you handle adversity is the lesson they'll carry forever.", theme: "attitude" },
  { id: "att-82", label: "Attitude shift: 'Life was easier before' → 'I have more skills, knowledge, and connections now than ever before.'", theme: "attitude" },
  { id: "att-83", label: "Attitude practice: do something nice for your wife today. Unexpectedly. Positive home energy = positive work energy.", theme: "attitude" },
  { id: "att-84", label: "Attitude technique: embodiment — how does a confident person breathe? Slowly. Walk? Deliberately. Speak? Calmly. Copy the physiology.", theme: "attitude" },
  { id: "att-85", label: "Attitude shift: 'I don't deserve success' → 'After 25 years of hard work, I deserve exactly what I'm building.'", theme: "attitude" },
  { id: "att-86", label: "Attitude practice: call one person you admire today. Just to say hello. Positive connections elevate your state.", theme: "attitude" },
  { id: "att-87", label: "Attitude technique: box breathing when stressed — 4 seconds in, 4 hold, 4 out, 4 hold. Navy SEALs use this. It works.", theme: "attitude" },
  { id: "att-88", label: "Attitude shift: 'What if I fail?' → 'What if I succeed beyond my wildest imagination?' — same energy, opposite direction.", theme: "attitude" },
  { id: "att-89", label: "Attitude practice: end every day by writing tomorrow's #1 priority. Going to bed with a plan reduces anxiety.", theme: "attitude" },
  { id: "att-90", label: "Attitude technique: choose your hard — being broke is hard, building a business is hard. Choose the hard that builds something.", theme: "attitude" },

  { id: "att-91", label: "Attitude reset: you've built surveillance systems for SEBI India. Most people can't even imagine that. You ARE capable.", theme: "attitude" },
  { id: "att-92", label: "Attitude shift: 'Nobody cares' → 'The right people care deeply. I just need to find them.' — quality over quantity.", theme: "attitude" },
  { id: "att-93", label: "Attitude practice: walk barefoot on grass for 5 minutes. Grounding reduces cortisol and resets the nervous system.", theme: "attitude" },
  { id: "att-94", label: "Attitude technique: the 'let it go' breath — inhale the situation, exhale the reaction. Release what you can't control.", theme: "attitude" },
  { id: "att-95", label: "Attitude shift: 'I'm not a natural salesperson' → 'I'm a natural problem-solver. That IS selling at the highest level.'", theme: "attitude" },
  { id: "att-96", label: "Attitude practice: physical posture check right now — are you slouching? Sit up. Shoulders back. Posture changes mood instantly.", theme: "attitude" },
  { id: "att-97", label: "Attitude technique: 'Progress, not perfection' mantra — repeat when paralyzed. Any forward motion counts.", theme: "attitude" },
  { id: "att-98", label: "Attitude shift: 'I'm starting over' → 'I'm starting over WITH 25 years of experience. Most people start with zero.'", theme: "attitude" },
  { id: "att-99", label: "Attitude practice: before reacting to anything stressful today, count to 10. Ten seconds of space changes everything.", theme: "attitude" },
  { id: "att-100", label: "Attitude technique: end every day with 'I did my best today. Tomorrow I'll be even better.' — self-compassion + ambition.", theme: "attitude" },

  // ============================================================
  // SECTION 3: HANDLING STRESS & REMAINING CALM (100)
  // ============================================================

  { id: "calm-1", label: "Stress tip: when your heart races before a meeting, slow your exhale. Breathe in 4 seconds, out 8 seconds. Activates parasympathetic.", theme: "stress-calm" },
  { id: "calm-2", label: "Stress tip: the 90-second rule — any emotion lasts only 90 seconds chemically. After that, you're choosing to continue it.", theme: "stress-calm" },
  { id: "calm-3", label: "Stress tip: cold water on your wrists for 30 seconds instantly lowers body temperature and calms the nervous system.", theme: "stress-calm" },
  { id: "calm-4", label: "Composure: before reacting to bad news, say 'Let me process this.' — buys time and prevents emotional outbursts.", theme: "stress-calm" },
  { id: "calm-5", label: "Stress tip: progressive muscle relaxation — tense each muscle group for 5 seconds, release. Start from toes, go to head. Takes 5 minutes.", theme: "stress-calm" },
  { id: "calm-6", label: "Composure: when someone is hostile, match your breathing to a slower pace. Their intensity will unconsciously mirror your calm.", theme: "stress-calm" },
  { id: "calm-7", label: "Stress tip: the 'worry window' — schedule 15 minutes to worry. Outside that window, redirect anxious thoughts to action.", theme: "stress-calm" },
  { id: "calm-8", label: "Composure: lower your voice when tension rises. The softer you speak, the more people lean in and the calmer the room becomes.", theme: "stress-calm" },
  { id: "calm-9", label: "Stress tip: exercise is the most effective anti-anxiety tool. Your daily badminton and swimming are literally saving your mental health.", theme: "stress-calm" },
  { id: "calm-10", label: "Composure: never make a decision when angry. Say 'I'll think about this and respond by tomorrow.' — protect yourself from reactive choices.", theme: "stress-calm" },

  { id: "calm-11", label: "Stress tip: when overwhelmed, use the 'brain dump' — write EVERYTHING in your head on paper. Empty the mental RAM.", theme: "stress-calm" },
  { id: "calm-12", label: "Composure: treat every stressful situation as a performance. 'How would a CEO handle this?' — then act accordingly.", theme: "stress-calm" },
  { id: "calm-13", label: "Stress tip: caffeine amplifies anxiety. If you're already stressed, switch to water. Hydration calms, caffeine escalates.", theme: "stress-calm" },
  { id: "calm-14", label: "Composure: the phrase 'I understand your frustration' immediately de-escalates 80% of tense conversations.", theme: "stress-calm" },
  { id: "calm-15", label: "Stress tip: sunlight exposure in the first 30 minutes of waking regulates cortisol. Step outside before checking your phone.", theme: "stress-calm" },
  { id: "calm-16", label: "Composure: when you feel the urge to vent, channel it into a journal or voice note instead of a person. Process, then communicate.", theme: "stress-calm" },
  { id: "calm-17", label: "Stress tip: the 4-7-8 breathing technique — inhale 4 seconds, hold 7 seconds, exhale 8 seconds. Repeat 3 times. Clinically proven.", theme: "stress-calm" },
  { id: "calm-18", label: "Composure: develop a 'nothing face' — a neutral, calm expression you can deploy under pressure. Practice in the mirror.", theme: "stress-calm" },
  { id: "calm-19", label: "Stress tip: bilateral stimulation — tap alternating knees while sitting. This activates both brain hemispheres and reduces anxiety.", theme: "stress-calm" },
  { id: "calm-20", label: "Composure: when losing your temper, press your tongue to the roof of your mouth. It disrupts the anger response physically.", theme: "stress-calm" },

  { id: "calm-21", label: "Stress tip: identify your stress triggers. Is it money? Rejection? Uncertainty? Name it. Named stress is half-managed stress.", theme: "stress-calm" },
  { id: "calm-22", label: "Composure: practice the 'observe, don't absorb' technique — notice other people's stress without taking it on as your own.", theme: "stress-calm" },
  { id: "calm-23", label: "Stress tip: if you wake up anxious, don't check your phone for 30 minutes. Let your cortisol settle naturally first.", theme: "stress-calm" },
  { id: "calm-24", label: "Composure: when someone pushes your buttons, remember: 'No one can make me angry without my permission.'", theme: "stress-calm" },
  { id: "calm-25", label: "Stress tip: laughter yoga — even fake laughter for 1 minute triggers real endorphins. Your body can't tell the difference.", theme: "stress-calm" },
  { id: "calm-26", label: "Composure: develop a pre-meeting ritual: 3 deep breaths, review your goal, visualize success. Same ritual every time.", theme: "stress-calm" },
  { id: "calm-27", label: "Stress tip: magnesium-rich foods (almonds, dark chocolate, spinach) reduce cortisol naturally. Snack smart.", theme: "stress-calm" },
  { id: "calm-28", label: "Composure: 'This too shall pass' is not just a saying — it's a neurological fact. All emotional states are temporary.", theme: "stress-calm" },
  { id: "calm-29", label: "Stress tip: nature exposure for 20 minutes reduces cortisol by 13%. Even a park bench counts.", theme: "stress-calm" },
  { id: "calm-30", label: "Composure: when criticized publicly, respond with 'Thank you for raising that. Let's discuss the details offline.' — deflect gracefully.", theme: "stress-calm" },

  { id: "calm-31", label: "Stress management: ask 'Is this my problem to solve?' — not everything that feels urgent is yours to carry.", theme: "stress-calm" },
  { id: "calm-32", label: "Composure: maintain your morning routine on stressful days ESPECIALLY. Routine is the anchor when everything else is chaotic.", theme: "stress-calm" },
  { id: "calm-33", label: "Stress tip: the 'container' visualization — imagine putting your worry in a box, closing the lid. You can open it during your worry window.", theme: "stress-calm" },
  { id: "calm-34", label: "Composure: if your voice shakes under pressure, slow down dramatically. Slow speech hides nervousness and projects authority.", theme: "stress-calm" },
  { id: "calm-35", label: "Stress tip: social connection reduces cortisol. One 5-minute genuine conversation with a friend = measurable stress reduction.", theme: "stress-calm" },
  { id: "calm-36", label: "Composure: the power of a calm smile during tension — it confuses aggressors and signals 'I'm in control here.'", theme: "stress-calm" },
  { id: "calm-37", label: "Stress tip: avoid making phone calls when stressed. Draft the message, wait 30 minutes, then send or call when calm.", theme: "stress-calm" },
  { id: "calm-38", label: "Composure: when things go wrong publicly, your first sentence sets the tone. Start calm, stay calm, end calm.", theme: "stress-calm" },
  { id: "calm-39", label: "Stress tip: tension in your jaw? That's stored stress. Open your mouth wide, stretch your jaw, then close gently. Instant relief.", theme: "stress-calm" },
  { id: "calm-40", label: "Composure: master the art of 'stepping back' — when emotions run high, excuse yourself for 5 minutes. It's not weakness, it's strategy.", theme: "stress-calm" },

  { id: "calm-41", label: "Stress tip: financial anxiety specifically — write down your worst-case scenario. Then write your plan for that scenario. Preparation kills fear.", theme: "stress-calm" },
  { id: "calm-42", label: "Composure: control what you can, release what you can't. Your actions are yours. Other people's responses are theirs.", theme: "stress-calm" },
  { id: "calm-43", label: "Stress tip: music therapy — listen to 432Hz or classical music for 10 minutes when overwhelmed. Measurable stress reduction.", theme: "stress-calm" },
  { id: "calm-44", label: "Composure: in a crisis, speak in short sentences. 'Here's what happened. Here's what we're doing. Here's the timeline.' — clarity under pressure.", theme: "stress-calm" },
  { id: "calm-45", label: "Stress tip: the 'serenity prayer' approach — accept what you can't change, change what you can, and have wisdom to know the difference.", theme: "stress-calm" },
  { id: "calm-46", label: "Composure: never let them see you sweat. Before entering a high-stress meeting, wipe your palms, straighten your clothes, take one deep breath.", theme: "stress-calm" },
  { id: "calm-47", label: "Stress tip: power nap — 20 minutes in the afternoon reduces cortisol by 20% and improves decision-making. Set an alarm.", theme: "stress-calm" },
  { id: "calm-48", label: "Composure: the 'controlled delay' — 'Let me sleep on this and respond tomorrow.' — 24 hours transforms reactive decisions into strategic ones.", theme: "stress-calm" },
  { id: "calm-49", label: "Stress tip: limit your exposure to other people's drama. Set boundaries. 'I'd rather not discuss that — let me know how I can help.'", theme: "stress-calm" },
  { id: "calm-50", label: "Composure: practice your 'crisis face' — calm, attentive, slightly serious. No panic, no dismissal. People feel safe with you.", theme: "stress-calm" },

  { id: "calm-51", label: "Stress recovery: after a hard day, don't ruminate — do a physical reset. Swim, walk, exercise. Move the stress out of your body.", theme: "stress-calm" },
  { id: "calm-52", label: "Composure: never send an angry email. Write it, save as draft, read it tomorrow. You'll always be glad you waited.", theme: "stress-calm" },
  { id: "calm-53", label: "Stress tip: the '5 by 5 rule' — if it won't matter in 5 years, don't spend more than 5 minutes upset about it.", theme: "stress-calm" },
  { id: "calm-54", label: "Composure: develop 3 go-to phrases for stressful moments: 'Interesting', 'Let me think about that', 'Tell me more.' — buys you thinking time.", theme: "stress-calm" },
  { id: "calm-55", label: "Stress tip: grounding technique — feel your feet on the floor. Focus on the physical sensation. It pulls you out of mental spirals.", theme: "stress-calm" },
  { id: "calm-56", label: "Composure: when everyone is panicking, be the person who says 'Let's take this one step at a time.' — you become the natural leader.", theme: "stress-calm" },
  { id: "calm-57", label: "Stress tip: aromatherapy — lavender or peppermint oil on your wrists reduces anxiety measurably. Keep a small bottle handy.", theme: "stress-calm" },
  { id: "calm-58", label: "Composure: rehearse difficult conversations in advance. Practice your opening line, your key points, your closing. Preparation = composure.", theme: "stress-calm" },
  { id: "calm-59", label: "Stress tip: deadline stress — break the task into 25-minute Pomodoro blocks. One block at a time. You eat an elephant one bite at a time.", theme: "stress-calm" },
  { id: "calm-60", label: "Composure: after a stressful meeting, write down what happened and what you'll do differently. Then close the notebook. Don't revisit.", theme: "stress-calm" },

  { id: "calm-61", label: "Stress tip: keep a 'done today' list alongside your to-do list. On bad days, the done list proves you DID make progress.", theme: "stress-calm" },
  { id: "calm-62", label: "Composure: the 'graceful pivot' — when caught off-guard, say 'That's not what I expected. Give me a moment.' — honesty + poise.", theme: "stress-calm" },
  { id: "calm-63", label: "Stress tip: avoid decision fatigue — make small decisions fast (what to eat, what to wear). Save mental energy for big decisions.", theme: "stress-calm" },
  { id: "calm-64", label: "Composure: maintain a neutral facial expression when receiving surprising news. React internally. Respond externally only when ready.", theme: "stress-calm" },
  { id: "calm-65", label: "Stress tip: phone boundaries — set 'do not disturb' for 1 hour during your deep work time. Not every message is urgent.", theme: "stress-calm" },
  { id: "calm-66", label: "Composure: when asked to make a big decision on the spot, say 'I want to give this the attention it deserves. Can I respond by X?'", theme: "stress-calm" },
  { id: "calm-67", label: "Stress tip: end each day with a 'shutdown ritual' — close all tabs, write tomorrow's plan, say 'shutdown complete.' Mental closure.", theme: "stress-calm" },
  { id: "calm-68", label: "Composure: during conflict, lower your speaking rate by 30%. Calm people speak slowly. Panicked people speak fast.", theme: "stress-calm" },
  { id: "calm-69", label: "Stress tip: schedule recovery time. After an intense client meeting, block 30 minutes for nothing. Your brain needs transition time.", theme: "stress-calm" },
  { id: "calm-70", label: "Composure: physical stillness under stress is incredibly powerful. Don't fidget, pace, or move excessively. Be a mountain.", theme: "stress-calm" },

  { id: "calm-71", label: "Stress tip: when money anxiety hits, calculate your exact minimum monthly need. Knowing the real number is less scary than imagining it.", theme: "stress-calm" },
  { id: "calm-72", label: "Composure: use strategic silence after someone says something provocative. Let the silence hold. They'll often soften or clarify.", theme: "stress-calm" },
  { id: "calm-73", label: "Stress tip: avoid second-hand stress — don't watch the stock ticker all day. Check once in the morning, once in the evening.", theme: "stress-calm" },
  { id: "calm-74", label: "Composure: 'Never let 'em see you bleed.' — maintain professionalism even when internally struggling. This IS strength.", theme: "stress-calm" },
  { id: "calm-75", label: "Stress tip: blue light from screens increases cortisol at night. No screens 1 hour before bed. Read a physical book instead.", theme: "stress-calm" },
  { id: "calm-76", label: "Composure: the 'bathroom reset' — excuse yourself, go to the restroom, splash cold water on your face, take 5 deep breaths. Return composed.", theme: "stress-calm" },
  { id: "calm-77", label: "Stress tip: singing activates the vagus nerve and reduces cortisol. Sing in the car, in the shower. It's not silly — it's science.", theme: "stress-calm" },
  { id: "calm-78", label: "Composure: when you've made a mistake, own it immediately: 'This was my error. Here's the fix.' — speed and ownership defuse tension.", theme: "stress-calm" },
  { id: "calm-79", label: "Stress tip: the '3 good things' exercise — every night, write 3 things that went well today and why. Rewires your brain for optimism.", theme: "stress-calm" },
  { id: "calm-80", label: "Composure: practice micro-recoveries — 3 deep breaths between emails, a 30-second pause between calls. Don't redline all day.", theme: "stress-calm" },

  { id: "calm-81", label: "Stress tip: social media breaks — 3 days without Instagram/Twitter measurably reduces anxiety and comparison stress.", theme: "stress-calm" },
  { id: "calm-82", label: "Composure: when angry, channel it into writing. Write the angry email, save it, delete it tomorrow. The act of writing releases it.", theme: "stress-calm" },
  { id: "calm-83", label: "Stress tip: maintain a 'resilience file' — screenshots of positive feedback, thank you messages, wins. Read it on bad days.", theme: "stress-calm" },
  { id: "calm-84", label: "Composure: eye contact during stress signals 'I'm present and in control.' Don't look away or down when things get heated.", theme: "stress-calm" },
  { id: "calm-85", label: "Stress tip: delegate one thing you're carrying today. You don't have to do everything. Ask for help — it's strength, not weakness.", theme: "stress-calm" },
  { id: "calm-86", label: "Composure: use the phrase 'I'm calm about this' — saying it literally makes it more true. Words shape neurological states.", theme: "stress-calm" },
  { id: "calm-87", label: "Stress tip: release the need to have all answers. 'I'm working on it' is a perfectly valid status update.", theme: "stress-calm" },
  { id: "calm-88", label: "Composure: during any confrontation, plant your feet firmly. Physical grounding prevents emotional floating.", theme: "stress-calm" },
  { id: "calm-89", label: "Stress tip: morning pages — write 3 pages stream of consciousness right after waking. Clears mental clutter for the day.", theme: "stress-calm" },
  { id: "calm-90", label: "Composure: the 'regal nod' — when provoked, nod slowly and thoughtfully. Don't react. Let them wonder what you're thinking.", theme: "stress-calm" },

  { id: "calm-91", label: "Stress tip: set a 'stress budget' for the day. When you hit it, no more stress-inducing activities. Protect your nervous system.", theme: "stress-calm" },
  { id: "calm-92", label: "Composure: lead with your breathing. If you control your breath, you control your body. If you control your body, you control the room.", theme: "stress-calm" },
  { id: "calm-93", label: "Stress tip: the 'mental rehearsal' — visualize the stressful situation going WELL. Your brain processes imagined success as real experience.", theme: "stress-calm" },
  { id: "calm-94", label: "Composure: in a heated meeting, uncross everything — arms, legs. Open posture de-escalates your own stress hormones.", theme: "stress-calm" },
  { id: "calm-95", label: "Stress tip: keep a stress journal — track what triggers you, when, and how you handled it. Patterns emerge. Then you can prevent.", theme: "stress-calm" },
  { id: "calm-96", label: "Composure: 'Easy is earned. Grace under pressure is practiced.' — you get better at calm the more you practice it.", theme: "stress-calm" },
  { id: "calm-97", label: "Stress tip: the 'two-minute vacation' — close eyes, imagine your favorite peaceful place in detail. Smell, sound, feel. Quick cortisol reset.", theme: "stress-calm" },
  { id: "calm-98", label: "Composure: when everything feels urgent, remind yourself: 'I have handled every difficult situation in my life so far. I will handle this too.'", theme: "stress-calm" },
  { id: "calm-99", label: "Stress tip: physical touch reduces cortisol — hug your daughters, hold your wife's hand, pet a dog. Connection is healing.", theme: "stress-calm" },
  { id: "calm-100", label: "Composure: the ultimate calm: 'I have survived 100% of my worst days. Today won't be any different.' — unbreakable.", theme: "stress-calm" },

  // ============================================================
  // SECTION 4: HANDLING DIFFICULT PEOPLE (100)
  // ============================================================

  { id: "dp-1", label: "Difficult people: remember — their behavior is about THEM, not you. Don't take it personally. Observe, don't absorb.", theme: "difficult-people" },
  { id: "dp-2", label: "Difficult people: the 'gray rock' technique — become uninteresting to manipulators. Minimal reaction, neutral responses, boring to bait.", theme: "difficult-people" },
  { id: "dp-3", label: "Difficult people: use the 'broken record' technique — calmly repeat your boundary without escalation. 'I understand, but my price is firm.'", theme: "difficult-people" },
  { id: "dp-4", label: "Difficult people: set boundaries with the 'I' statement: 'I need X to continue working productively' — not 'You always...'", theme: "difficult-people" },
  { id: "dp-5", label: "Difficult people: when someone is passive-aggressive, name it gently: 'I'm sensing some frustration. Can we address it directly?'", theme: "difficult-people" },
  { id: "dp-6", label: "Difficult people: don't argue with emotional people. Acknowledge their feeling first: 'I can see this is important to you.' Then logic.", theme: "difficult-people" },
  { id: "dp-7", label: "Difficult people: the 'BIFF' response for written conflict — Brief, Informative, Friendly, Firm. No emotion, no engagement with drama.", theme: "difficult-people" },
  { id: "dp-8", label: "Difficult people: when someone interrupts you repeatedly: 'I'd like to finish my thought.' — firm, not angry.", theme: "difficult-people" },
  { id: "dp-9", label: "Difficult people: never engage in a power struggle publicly. You can't win — even if you're right, you look small fighting.", theme: "difficult-people" },
  { id: "dp-10", label: "Difficult people: the 'empathy first' technique — 'You must be under a lot of pressure.' — disarms hostility instantly.", theme: "difficult-people" },

  { id: "dp-11", label: "Difficult people: when someone talks behind your back, don't confront publicly. Meet privately: 'I heard X. I'd prefer we discuss directly.'", theme: "difficult-people" },
  { id: "dp-12", label: "Difficult people: never match anger with anger. One calm person in a heated exchange has ALL the power.", theme: "difficult-people" },
  { id: "dp-13", label: "Difficult people: use the 'strategic compliment' — find something genuine to praise BEFORE raising the difficult topic.", theme: "difficult-people" },
  { id: "dp-14", label: "Difficult people: for chronic complainers: 'What would you like to see happen?' — redirects from problem to solution.", theme: "difficult-people" },
  { id: "dp-15", label: "Difficult people: the 'we're on the same team' reframe — 'We both want this to succeed. Let's figure out how.'", theme: "difficult-people" },
  { id: "dp-16", label: "Difficult people: when a client's accountant blocks your work (like Uttambhai), go above: 'I'd like to discuss this with the president directly.'", theme: "difficult-people" },
  { id: "dp-17", label: "Difficult people: document everything with difficult clients. 'As discussed, here's a summary...' — paper trail protects you.", theme: "difficult-people" },
  { id: "dp-18", label: "Difficult people: learn to walk away from toxic deals. Some money isn't worth the stress. Your mental health has value.", theme: "difficult-people" },
  { id: "dp-19", label: "Difficult people: when someone dismisses your expertise: 'I've been doing this for 25 years. I'm happy to explain my reasoning.'", theme: "difficult-people" },
  { id: "dp-20", label: "Difficult people: the 'paradoxical approach' — agree with their anger: 'You're right to be upset. Here's what I'm doing about it.'", theme: "difficult-people" },

  { id: "dp-21", label: "Difficult people: for micromanagers — proactive updates: 'Here's where things stand' before they ask. Removes their need to control.", theme: "difficult-people" },
  { id: "dp-22", label: "Difficult people: for know-it-alls — 'That's one approach. Here's another perspective to consider.' — don't compete, complement.", theme: "difficult-people" },
  { id: "dp-23", label: "Difficult people: for the 'yes but' person — 'I notice we keep hitting obstacles. What would a successful outcome look like to YOU?'", theme: "difficult-people" },
  { id: "dp-24", label: "Difficult people: for ghosters (like Niyam) — one final message: 'I'm available when you're ready. No pressure.' — dignified closure.", theme: "difficult-people" },
  { id: "dp-25", label: "Difficult people: for the overdemander — 'I want to deliver quality, and that means being realistic about timeline and scope.'", theme: "difficult-people" },
  { id: "dp-26", label: "Difficult people: never sacrifice your dignity for a deal. Some clients aren't worth having. The wrong client costs you three right ones.", theme: "difficult-people" },
  { id: "dp-27", label: "Difficult people: when someone gives you the silent treatment — name it: 'I notice we haven't communicated in a while. Is everything okay?'", theme: "difficult-people" },
  { id: "dp-28", label: "Difficult people: for the blamer — 'Let's focus on solutions rather than assigning blame. What can we do now?' — redirect energy.", theme: "difficult-people" },
  { id: "dp-29", label: "Difficult people: the 'fogging' technique — agree with part of their criticism: 'You're right that it took longer than expected.' — then pivot to facts.", theme: "difficult-people" },
  { id: "dp-30", label: "Difficult people: remember the 'difficult person' may be having a difficult day. Give one chance for grace before establishing boundaries.", theme: "difficult-people" },

  { id: "dp-31", label: "Difficult people: at Gymkhana, when someone is condescending about your business: 'I appreciate the perspective. Let me share what we're actually building.'", theme: "difficult-people" },
  { id: "dp-32", label: "Difficult people: for the gossiper — don't participate. 'I don't have much to add to that.' — neutral, closed, moved on.", theme: "difficult-people" },
  { id: "dp-33", label: "Difficult people: for the person who takes credit for your work — document and share proactively: 'I built X and here's the demo.'", theme: "difficult-people" },
  { id: "dp-34", label: "Difficult people: when disrespected in front of others — stay calm, make eye contact, and say nothing. Your silence speaks volumes.", theme: "difficult-people" },
  { id: "dp-35", label: "Difficult people: the 'kill them with kindness' approach — be relentlessly polite and helpful. It's disarming and makes YOU look great.", theme: "difficult-people" },
  { id: "dp-36", label: "Difficult people: set time limits: 'I have 15 minutes. Let's focus on the key issue.' — prevents difficult people from draining you.", theme: "difficult-people" },
  { id: "dp-37", label: "Difficult people: when someone compares you to a cheaper option: 'That's a fair comparison. Here's what makes us different...' — never insult competitors.", theme: "difficult-people" },
  { id: "dp-38", label: "Difficult people: for the 'my way or highway' type — 'I respect your position. Let me share an alternative that addresses your core concern.'", theme: "difficult-people" },
  { id: "dp-39", label: "Difficult people: never respond to a WhatsApp rant immediately. Wait at least 2 hours. The emotional temperature drops significantly.", theme: "difficult-people" },
  { id: "dp-40", label: "Difficult people: the 'concerned professional' stance — 'As your technology advisor, I'd be doing you a disservice if I didn't flag this.'", theme: "difficult-people" },

  { id: "dp-41", label: "Difficult people: when someone promises and doesn't deliver — 'I want to make sure we're aligned. Can we put the commitment in writing?'", theme: "difficult-people" },
  { id: "dp-42", label: "Difficult people: for the perpetual skeptic — provide small proof points: 'Let me show you just one feature working. Then you decide.'", theme: "difficult-people" },
  { id: "dp-43", label: "Difficult people: when someone dismisses technology: 'I understand the concern. Let me show you how others in your industry are using it successfully.'", theme: "difficult-people" },
  { id: "dp-44", label: "Difficult people: never argue with someone who wants a fight. They're not looking for a solution — they're looking for a reaction.", theme: "difficult-people" },
  { id: "dp-45", label: "Difficult people: the 'respectful exit' — 'I think we've reached an impasse. Let's both think about this and reconnect next week.'", theme: "difficult-people" },
  { id: "dp-46", label: "Difficult people: for the indecisive client — create urgency gently: 'The team is available now but has other projects lined up for next month.'", theme: "difficult-people" },
  { id: "dp-47", label: "Difficult people: when someone's negative energy is affecting you — literally increase physical distance. Step back. Create space.", theme: "difficult-people" },
  { id: "dp-48", label: "Difficult people: the 'compliment sandwich' for difficult feedback: 'Great X, concern about Y, confident about Z.' — cushion the blow.", theme: "difficult-people" },
  { id: "dp-49", label: "Difficult people: know when to cut losses. If a client relationship is toxic, end it professionally: 'I don't think we're the right fit.'", theme: "difficult-people" },
  { id: "dp-50", label: "Difficult people: remember — every difficult person you handle well becomes a story you can use to show others your professionalism.", theme: "difficult-people" },

  { id: "dp-51", label: "Difficult people: for the 'everything is urgent' person — 'Let me help prioritize: what absolutely cannot wait until tomorrow?'", theme: "difficult-people" },
  { id: "dp-52", label: "Difficult people: when someone lies to you — don't accuse: 'My understanding was different. Can you walk me through your version?' — let truth emerge.", theme: "difficult-people" },
  { id: "dp-53", label: "Difficult people: for the long-winded talker — hold up a hand gently: 'Let me make sure I've got this. You're saying...' — summarize and redirect.", theme: "difficult-people" },
  { id: "dp-54", label: "Difficult people: when family questions your business choices — 'I appreciate your concern. I've thought about this carefully and I believe in my path.'", theme: "difficult-people" },
  { id: "dp-55", label: "Difficult people: for the non-paying client — professional escalation: 'I value our relationship and want to resolve this before it affects future work.'", theme: "difficult-people" },
  { id: "dp-56", label: "Difficult people: when someone raises their voice — lower yours. It's counterintuitive but forces them to lower theirs to hear you.", theme: "difficult-people" },
  { id: "dp-57", label: "Difficult people: the 'curiosity approach' — instead of 'You're wrong', try 'What led you to that conclusion?' — explore before opposing.", theme: "difficult-people" },
  { id: "dp-58", label: "Difficult people: protect your energy budget. Difficult people are expensive. Limit exposure. Increase time with energy-givers.", theme: "difficult-people" },
  { id: "dp-59", label: "Difficult people: when someone undermines you at Gymkhana — respond with competence, not confrontation. Deliver so well they can't deny it.", theme: "difficult-people" },
  { id: "dp-60", label: "Difficult people: the ultimate power move with a bully — agree calmly and move on: 'You may be right.' — there's nothing to fight.", theme: "difficult-people" },

  { id: "dp-61", label: "Difficult people: when a senior person talks down to you — maintain eye contact, nod once, then calmly share your perspective. Don't shrink.", theme: "difficult-people" },
  { id: "dp-62", label: "Difficult people: understand their motivation — are they afraid? Insecure? Under pressure? Addressing the root cause solves the behavior.", theme: "difficult-people" },
  { id: "dp-63", label: "Difficult people: for the 'can you do this for free' person — 'I'd love to help. My fee for this would be Rs X. Shall I proceed?'", theme: "difficult-people" },
  { id: "dp-64", label: "Difficult people: when someone says 'you don't understand' — 'Help me understand. I'm listening.' — turns accusation into collaboration.", theme: "difficult-people" },
  { id: "dp-65", label: "Difficult people: never explain yourself to someone who is committed to misunderstanding you. Save your energy.", theme: "difficult-people" },
  { id: "dp-66", label: "Difficult people: the 'feedback loop' — 'How can I make our interaction better? I want this to work for both of us.' — shows maturity.", theme: "difficult-people" },
  { id: "dp-67", label: "Difficult people: when they try to guilt-trip you — 'I understand you're disappointed. My decision stands. How can we move forward?'", theme: "difficult-people" },
  { id: "dp-68", label: "Difficult people: maintain your standards even when they push. Quality people notice when you stand firm. They respect it.", theme: "difficult-people" },
  { id: "dp-69", label: "Difficult people: learn the art of 'strategic agreement' — agree on small things to build rapport, then negotiate the big things.", theme: "difficult-people" },
  { id: "dp-70", label: "Difficult people: when someone is consistently late — start without them every time. They'll learn or they'll leave. Both are acceptable.", theme: "difficult-people" },

  { id: "dp-71", label: "Difficult people: for the person who changes scope constantly — 'Any changes from here require a change request with revised pricing.'", theme: "difficult-people" },
  { id: "dp-72", label: "Difficult people: when patronized — 'I appreciate the guidance. In my 25 years of experience, I've found that...' — credential check, gently.", theme: "difficult-people" },
  { id: "dp-73", label: "Difficult people: the 'time boundary' — 'I have a hard stop at 4 PM' — prevents energy-draining conversations from stretching.", theme: "difficult-people" },
  { id: "dp-74", label: "Difficult people: for committee politics (like Nirmal Bhai's samaj) — build allies one-on-one before any group discussion.", theme: "difficult-people" },
  { id: "dp-75", label: "Difficult people: when caught in someone else's conflict — 'I'd prefer to stay neutral. How can I help resolve this productively?'", theme: "difficult-people" },
  { id: "dp-76", label: "Difficult people: the 'ask for advice' technique — asking a difficult person for their opinion makes them feel valued and reduces resistance.", theme: "difficult-people" },
  { id: "dp-77", label: "Difficult people: never match pettiness with pettiness. Rise above. Your reputation is worth more than winning a small battle.", theme: "difficult-people" },
  { id: "dp-78", label: "Difficult people: when dealing with gatekeepers — respect their role: 'I appreciate you protecting his time. Could you let him know I have a brief update?'", theme: "difficult-people" },
  { id: "dp-79", label: "Difficult people: sometimes the best response is no response. Not every provocation deserves your energy. Silence IS a response.", theme: "difficult-people" },
  { id: "dp-80", label: "Difficult people: for the person who constantly one-ups — stop competing. 'That's amazing.' Then move on. They need the spotlight more than you.", theme: "difficult-people" },

  { id: "dp-81", label: "Difficult people: maintain professional warmth even when someone is cold. It unsettles them and positions you as the bigger person.", theme: "difficult-people" },
  { id: "dp-82", label: "Difficult people: the 'repeat their words' technique — 'You said X. Is that accurate?' — makes people responsible for their own statements.", theme: "difficult-people" },
  { id: "dp-83", label: "Difficult people: for someone who constantly cancels meetings — 'I've noticed we've rescheduled a few times. Is there a better time that works consistently?'", theme: "difficult-people" },
  { id: "dp-84", label: "Difficult people: don't try to change difficult people. Manage the interaction, not the person.", theme: "difficult-people" },
  { id: "dp-85", label: "Difficult people: when you're the target of sarcasm — respond literally and positively. It removes the sting: 'Thanks, I appreciate the feedback.'", theme: "difficult-people" },
  { id: "dp-86", label: "Difficult people: build a support network. Have 2-3 people you can call after a difficult interaction for perspective.", theme: "difficult-people" },
  { id: "dp-87", label: "Difficult people: the 'common enemy' technique — find something you both dislike (bureaucracy, slow internet) to build unexpected rapport.", theme: "difficult-people" },
  { id: "dp-88", label: "Difficult people: when someone gives you unsolicited business advice — 'Interesting perspective. I'll consider that.' — acknowledge without committing.", theme: "difficult-people" },
  { id: "dp-89", label: "Difficult people: keep a 'difficult interactions log' — date, person, what happened, how you handled it. You'll see your own growth.", theme: "difficult-people" },
  { id: "dp-90", label: "Difficult people: remember — the way you handle difficult people teaches everyone around you what kind of leader you are. Make it count.", theme: "difficult-people" },

  { id: "dp-91", label: "Difficult people: when someone criticizes your pricing to others — don't engage. Let your work quality be the response. Excellence is the best argument.", theme: "difficult-people" },
  { id: "dp-92", label: "Difficult people: for the 'yes man' who later backstabs — get commitments in writing: 'Great, I'll send a summary of what we agreed.'", theme: "difficult-people" },
  { id: "dp-93", label: "Difficult people: the 'mirror technique' — subtly mirror their body language, then gradually shift to calmer posture. They'll follow.", theme: "difficult-people" },
  { id: "dp-94", label: "Difficult people: when someone says 'no offense, but...' — they know it's offensive. Respond: 'I appreciate the directness. Here's my view.'", theme: "difficult-people" },
  { id: "dp-95", label: "Difficult people: for someone who withholds information — 'To deliver the best result, I need X. Can you share that with me?'", theme: "difficult-people" },
  { id: "dp-96", label: "Difficult people: protect your boundaries with action, not words. If they don't respect your time, shorten the meeting. Actions speak.", theme: "difficult-people" },
  { id: "dp-97", label: "Difficult people: when dealing with entitled behavior — stay professional and factual. Don't match entitlement with emotion.", theme: "difficult-people" },
  { id: "dp-98", label: "Difficult people: after a tough interaction, do a mental 'shake off' — physically shake your hands, exhale loudly. Release the residual tension.", theme: "difficult-people" },
  { id: "dp-99", label: "Difficult people: the ultimate test — can you maintain your composure when someone is deliberately trying to provoke you? Practice daily.", theme: "difficult-people" },
  { id: "dp-100", label: "Difficult people: remember — difficult people are your gym equipment. They make you stronger. Thank them silently and keep building.", theme: "difficult-people" },

  // ============================================================
  // SECTION 5: UNDERSTANDING & USING BODY LANGUAGE (100)
  // ============================================================

  { id: "bl-1", label: "Body language: your posture is the first thing people read. Before speaking, your body has already said 'confidence' or 'insecurity.'", theme: "body-language" },
  { id: "bl-2", label: "Body language: the 'power pose' — hands on hips, feet shoulder-width apart, for 2 minutes before a meeting. Increases testosterone, decreases cortisol.", theme: "body-language" },
  { id: "bl-3", label: "Body language: make your handshake match theirs. Too strong = aggressive. Too weak = submissive. Match and add warmth.", theme: "body-language" },
  { id: "bl-4", label: "Body language: when entering a room, pause for 1 second at the door. Scan the room. Then walk in purposefully. This signals 'I belong here.'", theme: "body-language" },
  { id: "bl-5", label: "Body language: crossed arms = 'I'm closed off.' Uncross your arms in every conversation today. Open body = open mind.", theme: "body-language" },
  { id: "bl-6", label: "Body language: lean forward slightly when listening — it signals interest and engagement. Lean back = disinterest or judgment.", theme: "body-language" },
  { id: "bl-7", label: "Body language: the 'steeple' — fingertips touching, palms apart. It's the body language of confidence. CEOs and judges use it.", theme: "body-language" },
  { id: "bl-8", label: "Body language: eye contact for 60-70% of conversation is ideal. Less = nervous. More = aggressive. Find the sweet spot.", theme: "body-language" },
  { id: "bl-9", label: "Body language: nodding while someone speaks signals 'I'm following.' Slow nods = thoughtful engagement. Fast nods = 'hurry up.'", theme: "body-language" },
  { id: "bl-10", label: "Body language: face your feet toward the person you're talking to. Feet pointing away = subconsciously wanting to leave.", theme: "body-language" },

  { id: "bl-11", label: "Read others: touching the nose or mouth while speaking — possible discomfort with what they're saying. Explore gently.", theme: "body-language" },
  { id: "bl-12", label: "Read others: feet pointing toward the door — they want to leave. Wrap up or get to the point.", theme: "body-language" },
  { id: "bl-13", label: "Read others: sudden arm crossing after you state a price — resistance. Address it: 'What concerns do you have?'", theme: "body-language" },
  { id: "bl-14", label: "Read others: rubbing the back of their neck — stress or frustration. Ease the conversation: 'Let's take a different approach.'", theme: "body-language" },
  { id: "bl-15", label: "Read others: genuine smile (Duchenne) crinkles the eyes. Fake smile only moves the mouth. Learn to spot the difference.", theme: "body-language" },
  { id: "bl-16", label: "Read others: palms up = openness and honesty. Palms down = authority and dominance. Notice which people use.", theme: "body-language" },
  { id: "bl-17", label: "Read others: head tilt = interest and curiosity. If someone tilts their head while you speak, you've got their attention.", theme: "body-language" },
  { id: "bl-18", label: "Read others: rapid blinking = stress or processing discomfort. Slow, steady blinks = calm and controlled.", theme: "body-language" },
  { id: "bl-19", label: "Read others: leg crossing toward you = openness. Leg crossing away = creating a barrier. Subtle but telling.", theme: "body-language" },
  { id: "bl-20", label: "Read others: watch clusters, not single gestures. One sign means nothing. Three signs together tell a story.", theme: "body-language" },

  { id: "bl-21", label: "Your body: walk 10% slower than usual today. A deliberate pace signals you're in no rush — you're the important one.", theme: "body-language" },
  { id: "bl-22", label: "Your body: keep your chin parallel to the floor. Chin up = arrogance. Chin down = submission. Level = confidence.", theme: "body-language" },
  { id: "bl-23", label: "Your body: sit upright, never slouch in meetings. The most powerful person in the room always has the best posture.", theme: "body-language" },
  { id: "bl-24", label: "Your body: when standing, take up space. Feet shoulder-width, hands visible (not in pockets). Occupying space = confidence.", theme: "body-language" },
  { id: "bl-25", label: "Your body: use purposeful hand gestures between waist and shoulders when speaking. It increases message retention by 30%.", theme: "body-language" },
  { id: "bl-26", label: "Your body: never touch your face during negotiations. It signals nervousness or deception, even if neither is true.", theme: "body-language" },
  { id: "bl-27", label: "Your body: the 'relaxed power' position in chairs — lean back slightly, one arm on armrest, other hand free. Comfortable authority.", theme: "body-language" },
  { id: "bl-28", label: "Your body: when presenting, don't stand behind a podium. Step to the front. Remove barriers between you and the audience.", theme: "body-language" },
  { id: "bl-29", label: "Your body: breathe from your diaphragm, not your chest. Deep belly breathing calms you AND makes your voice more resonant.", theme: "body-language" },
  { id: "bl-30", label: "Your body: stand when greeting someone. Always. It shows respect and puts you at eye level — never greet from a seated position.", theme: "body-language" },

  { id: "bl-31", label: "Mirror technique: subtly copy the other person's body language to build rapport. If they lean left, you lean left after 5 seconds.", theme: "body-language" },
  { id: "bl-32", label: "Mirror technique: match their speaking pace. Fast talkers bond with fast talkers. Slow with slow. Adapt to their rhythm.", theme: "body-language" },
  { id: "bl-33", label: "Mirror technique: if they use hand gestures, use hand gestures. If they're still, be still. Matching creates unconscious trust.", theme: "body-language" },
  { id: "bl-34", label: "Leading technique: once rapport is built through mirroring, gradually shift YOUR posture. If they follow, you have influence.", theme: "body-language" },
  { id: "bl-35", label: "Leading technique: uncross your arms after mirroring their closed posture. If they uncross too, the defensive wall is down.", theme: "body-language" },
  { id: "bl-36", label: "Space management: stand 3-4 feet from someone in a business conversation. Closer = intimate. Farther = disinterested.", theme: "body-language" },
  { id: "bl-37", label: "Space management: the 'triangle formation' in group conversations — position yourself to include everyone. Don't create closed dyads.", theme: "body-language" },
  { id: "bl-38", label: "Space management: at Gymkhana, position yourself where people naturally walk. Being in the traffic flow increases casual encounters.", theme: "body-language" },
  { id: "bl-39", label: "Space management: sit at the head of the table or center seats. Corner seats are low-status. Position matters.", theme: "body-language" },
  { id: "bl-40", label: "Space management: in a restaurant meeting, let the client take the 'power seat' facing the room. It puts them at ease.", theme: "body-language" },

  { id: "bl-41", label: "Micro-expressions: a flash of contempt (one lip corner pulled up) = they disagree but won't say it. Probe: 'What's your honest take?'", theme: "body-language" },
  { id: "bl-42", label: "Micro-expressions: raised eyebrows = surprise or interest. If you see it after your pitch, pause and let them respond.", theme: "body-language" },
  { id: "bl-43", label: "Micro-expressions: tightened lips = suppressed disagreement. They're holding back. Ask: 'Is there something you'd like to add?'", theme: "body-language" },
  { id: "bl-44", label: "Micro-expressions: a genuine 'flash' smile (quick and warm) = they actually like you. Different from a held/forced smile.", theme: "body-language" },
  { id: "bl-45", label: "Micro-expressions: jaw clenching = frustration or anger being held back. Ease the topic or acknowledge: 'This seems difficult.'", theme: "body-language" },
  { id: "bl-46", label: "Hands speak: open palms when speaking = honesty and openness. Use this in pitches. Show your palms.", theme: "body-language" },
  { id: "bl-47", label: "Hands speak: pointing = aggressive. Instead, gesture with an open hand toward the topic. It's warmer and more inclusive.", theme: "body-language" },
  { id: "bl-48", label: "Hands speak: hands behind back ('the royal') = confidence and authority. Prince Charles walks this way. Try it at Gymkhana.", theme: "body-language" },
  { id: "bl-49", label: "Hands speak: fidgeting with objects (pen, phone, keys) = anxiety. Put everything down. Stillness = composure.", theme: "body-language" },
  { id: "bl-50", label: "Hands speak: rubbing hands together = anticipation or excitement. If a client does this after your pitch, they're interested.", theme: "body-language" },

  { id: "bl-51", label: "Eye language: looking up-right = constructing/imagining. Looking up-left = remembering. Useful for assessing truthfulness.", theme: "body-language" },
  { id: "bl-52", label: "Eye language: dilated pupils = interest or attraction (to an idea, a product, a person). Watch for it when presenting solutions.", theme: "body-language" },
  { id: "bl-53", label: "Eye language: the 'business gaze' — focus on the triangle between eyes and forehead. Professional and authoritative.", theme: "body-language" },
  { id: "bl-54", label: "Eye language: the 'social gaze' — focus on the triangle between eyes and mouth. Warmer and more personal. Use at networking events.", theme: "body-language" },
  { id: "bl-55", label: "Eye language: breaking eye contact by looking down = submission. Breaking by looking to the side = neutral. Down is worse.", theme: "body-language" },
  { id: "bl-56", label: "Posture clusters: leaning forward + uncrossed arms + nodding = engaged and interested. If you see this, you're winning.", theme: "body-language" },
  { id: "bl-57", label: "Posture clusters: leaning back + crossed arms + minimal eye contact = disengaged. Change your approach immediately.", theme: "body-language" },
  { id: "bl-58", label: "Posture clusters: steepled fingers + slight head tilt + steady gaze = evaluating your proposal. Present your strongest point now.", theme: "body-language" },
  { id: "bl-59", label: "Posture clusters: touching face + looking away + shifting weight = uncomfortable with the topic. Pivot or ask what's wrong.", theme: "body-language" },
  { id: "bl-60", label: "Posture clusters: open stance + genuine smile + mirroring you = rapport achieved. This is when you move toward the close.", theme: "body-language" },

  { id: "bl-61", label: "Walking style: purposeful stride (steady pace, arms swinging naturally) = confidence. Practice this walking into Gymkhana.", theme: "body-language" },
  { id: "bl-62", label: "Walking style: shuffling or dragging feet = low energy/depression. Consciously pick up your feet and walk with intention.", theme: "body-language" },
  { id: "bl-63", label: "Walking style: head up, eyes forward when walking = you know where you're going. Looking down = uncertain, submissive.", theme: "body-language" },
  { id: "bl-64", label: "Sitting style: 'open sitting' — ankles uncrossed, knees apart, hands visible = confident and approachable. Default to this.", theme: "body-language" },
  { id: "bl-65", label: "Sitting style: the 'figure four' (ankle on opposite knee) = relaxed confidence. But can seem too casual in formal settings.", theme: "body-language" },
  { id: "bl-66", label: "Voice as body language: your voice IS physical. Low pitch = authority. Varied pitch = engaging. Monotone = boring. Practice range.", theme: "body-language" },
  { id: "bl-67", label: "Voice as body language: speaking from the chest vs. throat. Put your hand on your chest and hum. Feel the vibration. Speak from there.", theme: "body-language" },
  { id: "bl-68", label: "Voice as body language: the 'command voice' — slightly louder, slightly slower, deeper pitch. Use when making important statements.", theme: "body-language" },
  { id: "bl-69", label: "Voice as body language: upward inflection at the end of sentences makes statements sound like questions. Avoid. Go DOWN at the end.", theme: "body-language" },
  { id: "bl-70", label: "Voice as body language: strategic pauses before key words add weight: 'We saved them... forty percent.' — the pause creates impact.", theme: "body-language" },

  { id: "bl-71", label: "First impressions: people form an opinion in 7 seconds. In that time: posture, eye contact, smile, handshake. Make them count.", theme: "body-language" },
  { id: "bl-72", label: "First impressions: show your palms early in an interaction — it's an ancient trust signal. Open hands = no weapons = safe.", theme: "body-language" },
  { id: "bl-73", label: "First impressions: say their name while making eye contact and slightly nodding. Triple-impact first impression.", theme: "body-language" },
  { id: "bl-74", label: "First impressions: your clothing IS body language. Crisp, fitted, well-maintained clothes say 'I pay attention to detail.'", theme: "body-language" },
  { id: "bl-75", label: "First impressions: the 'eyebrow flash' — a quick raise of both eyebrows when you recognize someone. Universal signal of friendliness.", theme: "body-language" },
  { id: "bl-76", label: "Cultural awareness: in Indian business, a slight forward bow shows respect to elders. Use with senior Gymkhana members.", theme: "body-language" },
  { id: "bl-77", label: "Cultural awareness: touching feet or a respectful namaste with senior Kutchi businessmen — shows you understand the community culture.", theme: "body-language" },
  { id: "bl-78", label: "Cultural awareness: personal space is closer in Indian culture than Western. Don't step back if someone stands close — it signals rejection.", theme: "body-language" },
  { id: "bl-79", label: "Cultural awareness: head wobble (the Indian nod) can mean yes, ok, or I'm listening. Context determines meaning. You know this — use it.", theme: "body-language" },
  { id: "bl-80", label: "Cultural awareness: accepting chai/water when offered is a rapport signal in Indian business. Never refuse the first offer of hospitality.", theme: "body-language" },

  { id: "bl-81", label: "Power dynamics: the person who sits while others stand holds the power position (if intentional). Use this in your office.", theme: "body-language" },
  { id: "bl-82", label: "Power dynamics: touching someone's shoulder briefly while speaking = dominance signal. Use sparingly and appropriately.", theme: "body-language" },
  { id: "bl-83", label: "Power dynamics: keeping your back straight against the chair while others slouch = automatic authority elevation.", theme: "body-language" },
  { id: "bl-84", label: "Power dynamics: the person who speaks last in a group often has the most influence. Observe + synthesize + deliver.", theme: "body-language" },
  { id: "bl-85", label: "Power dynamics: holding eye contact for 1 beat longer than expected signals 'I'm not intimidated by you.' Use with equals and seniors.", theme: "body-language" },
  { id: "bl-86", label: "Deception detection: baseline first — observe how someone normally behaves. Deception shows as CHANGES from their baseline.", theme: "body-language" },
  { id: "bl-87", label: "Deception detection: inconsistency between words and body = red flag. 'I love this idea' + crossed arms + no smile = they don't.", theme: "body-language" },
  { id: "bl-88", label: "Deception detection: excessive detail in explanations can signal fabrication. Truth is usually simple and direct.", theme: "body-language" },
  { id: "bl-89", label: "Deception detection: sudden stillness (freeze response) after a question = they're carefully constructing a response. Probe further.", theme: "body-language" },
  { id: "bl-90", label: "Deception detection: grooming gestures (adjusting collar, smoothing hair) during difficult questions = self-soothing under stress.", theme: "body-language" },

  { id: "bl-91", label: "Daily practice: check your posture 5 times today. Set phone alarms. Posture awareness becomes posture habit in 21 days.", theme: "body-language" },
  { id: "bl-92", label: "Daily practice: watch a TED talk on mute. Study the speaker's body language. What makes them compelling without words?", theme: "body-language" },
  { id: "bl-93", label: "Daily practice: observe one person at Gymkhana closely today. What does their body language tell you about their state of mind?", theme: "body-language" },
  { id: "bl-94", label: "Daily practice: video record yourself talking for 1 minute. Watch it back. You'll immediately see habits you didn't know you had.", theme: "body-language" },
  { id: "bl-95", label: "Daily practice: the 'power morning' routine — shower, groom, dress well, check posture, make eye contact with yourself. Then step out.", theme: "body-language" },
  { id: "bl-96", label: "Daily practice: smile at the first 3 people you see today. Notice how they respond. Smiling is the universal opener.", theme: "body-language" },
  { id: "bl-97", label: "Daily practice: practice the steeple gesture while sitting. It should feel natural, not forced. Comfort comes with repetition.", theme: "body-language" },
  { id: "bl-98", label: "Daily practice: walk through a doorway today as if you own the building. Shoulders back, head up, purposeful stride. Own every entrance.", theme: "body-language" },
  { id: "bl-99", label: "Daily practice: in one conversation today, focus ONLY on reading the other person's body language. What do you notice that words hide?", theme: "body-language" },
  { id: "bl-100", label: "Daily practice: remember — your body speaks before you do, louder than you do, and more honestly than you do. Master it.", theme: "body-language" },
];
